[hls]
relative_roots=/home/superkooks/Uni/COMP4601/assign/canny_hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=output_row/VITIS_LOOP_20_1 
syn.directive.pipeline=hysteresis<4>/VITIS_LOOP_72_1 
syn.directive.pipeline=hysteresis<4>/VITIS_LOOP_110_2 
syn.directive.pipeline=double_threshold/VITIS_LOOP_16_1 
syn.directive.pipeline=non_maximum_suppression/VITIS_LOOP_45_1 
syn.directive.pipeline=non_maximum_suppression/VITIS_LOOP_74_2 
syn.directive.pipeline=sobel/VITIS_LOOP_100_1 
syn.directive.pipeline=sobel/VITIS_LOOP_116_2 
syn.directive.pipeline=gaussian_blur/VITIS_LOOP_57_1 
syn.directive.pipeline=gaussian_blur/VITIS_LOOP_70_2 
syn.directive.pipeline=grayscale/VITIS_LOOP_7_1 
syn.directive.pipeline=canny_top/VITIS_LOOP_42_2 
syn.directive.pipeline=canny_top/VITIS_LOOP_80_2 
syn.directive.pipeline=canny_top/VITIS_LOOP_23_2 
syn.directive.pipeline=canny_top/VITIS_LOOP_50_2 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=canny_top/VITIS_LOOP_41_1  
syn.directive.loop_flatten=canny_top/VITIS_LOOP_49_1  
syn.directive.loop_flatten=canny_top/VITIS_LOOP_22_1  
syn.directive.loop_flatten=canny_top/VITIS_LOOP_79_1  


