[hls]
relative_roots=/home/superkooks/Uni/COMP4601/assign/canny_hls
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=grayscale/row_bytes dim=1 type=cyclic factor=32 variable=row_bytes
syn.directive.loop_flatten=write_frame/VITIS_LOOP_7_1  


