# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline output_row/VITIS_LOOP_20_1
set_directive_pipeline hysteresis<4>/VITIS_LOOP_72_1
set_directive_pipeline hysteresis<4>/VITIS_LOOP_110_2
set_directive_pipeline double_threshold/VITIS_LOOP_16_1
set_directive_pipeline non_maximum_suppression/VITIS_LOOP_45_1
set_directive_pipeline non_maximum_suppression/VITIS_LOOP_74_2
set_directive_pipeline sobel/VITIS_LOOP_100_1
set_directive_pipeline sobel/VITIS_LOOP_116_2
set_directive_pipeline gaussian_blur/VITIS_LOOP_57_1
set_directive_pipeline gaussian_blur/VITIS_LOOP_70_2
set_directive_pipeline grayscale/VITIS_LOOP_7_1
set_directive_pipeline canny_top/VITIS_LOOP_42_2
set_directive_pipeline canny_top/VITIS_LOOP_80_2
set_directive_pipeline canny_top/VITIS_LOOP_23_2
set_directive_pipeline canny_top/VITIS_LOOP_50_2
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten canny_top/VITIS_LOOP_41_1
set_directive_loop_flatten canny_top/VITIS_LOOP_49_1
set_directive_loop_flatten canny_top/VITIS_LOOP_22_1
set_directive_loop_flatten canny_top/VITIS_LOOP_79_1
