[hls]
relative_roots=C:/Users/twhsaw/Projects/comp4601/canny_hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=output_row/VITIS_LOOP_20_1 
syn.directive.pipeline=double_threshold/VITIS_LOOP_16_1 
syn.directive.pipeline=grayscale/VITIS_LOOP_7_1 
syn.directive.pipeline=canny_top/VITIS_LOOP_48_2 
syn.directive.pipeline=canny_top/VITIS_LOOP_80_2 
syn.directive.pipeline=canny_top/VITIS_LOOP_33_2 
syn.directive.pipeline=canny_top/VITIS_LOOP_60_2 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=canny_top/VITIS_LOOP_47_1  
syn.directive.loop_flatten=canny_top/VITIS_LOOP_59_1  
syn.directive.loop_flatten=canny_top/VITIS_LOOP_32_1  
syn.directive.loop_flatten=canny_top/VITIS_LOOP_79_1  


