// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module canny_top_hysteresis_4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        hyst3_out_dout,
        hyst3_out_empty_n,
        hyst3_out_read,
        hyst3_out_num_data_valid,
        hyst3_out_fifo_cap,
        hyst4_out_din,
        hyst4_out_full_n,
        hyst4_out_write,
        hyst4_out_num_data_valid,
        hyst4_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] hyst3_out_dout;
input   hyst3_out_empty_n;
output   hyst3_out_read;
input  [10:0] hyst3_out_num_data_valid;
input  [10:0] hyst3_out_fifo_cap;
output  [7:0] hyst4_out_din;
input   hyst4_out_full_n;
output   hyst4_out_write;
input  [31:0] hyst4_out_num_data_valid;
input  [31:0] hyst4_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [9:0] rowsReceived_fu_224_p2;
reg   [9:0] rowsReceived_reg_530;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_24_fu_230_p3;
reg   [0:0] tmp_24_reg_535;
wire   [1:0] trunc_ln80_fu_238_p1;
reg   [1:0] trunc_ln80_reg_539;
wire   [0:0] tmp_25_fu_248_p3;
reg   [0:0] tmp_25_reg_544;
wire    ap_CS_fsm_state3;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done;
reg    ap_block_state3_on_subcall_done;
wire   [0:0] hasTop_fu_256_p2;
reg   [0:0] hasTop_reg_548;
wire   [0:0] hasBottom_fu_262_p2;
reg   [0:0] hasBottom_reg_553;
reg   [7:0] buffer_load_reg_563;
wire    ap_CS_fsm_state5;
reg   [7:0] buffer_1_load_reg_570;
reg   [7:0] buffer_2_load_reg_577;
reg   [7:0] buffer_load_1_reg_584;
reg   [7:0] buffer_1_load_1_reg_591;
reg   [7:0] buffer_2_load_1_reg_598;
wire   [1:0] select_ln12_fu_297_p3;
reg   [1:0] select_ln12_reg_605;
wire    ap_CS_fsm_state16;
wire   [1:0] trunc_ln10_fu_306_p1;
reg   [1:0] trunc_ln10_reg_610;
wire   [7:0] tmp_fu_311_p9;
reg   [7:0] tmp_reg_615;
wire   [7:0] tmp_s_fu_329_p9;
reg   [7:0] tmp_s_reg_620;
wire   [7:0] tmp_12_fu_347_p9;
reg   [7:0] tmp_12_reg_625;
wire   [7:0] tmp_13_fu_365_p9;
reg   [7:0] tmp_13_reg_630;
wire   [7:0] tmp_14_fu_383_p9;
reg   [7:0] tmp_14_reg_635;
wire   [7:0] tmp_15_fu_401_p9;
reg   [7:0] tmp_15_reg_640;
reg   [8:0] buffer_address0;
reg    buffer_ce0;
reg    buffer_we0;
wire   [7:0] buffer_q0;
wire   [8:0] buffer_address1;
wire   [7:0] buffer_q1;
reg   [8:0] buffer_1_address0;
reg    buffer_1_ce0;
reg    buffer_1_we0;
wire   [7:0] buffer_1_q0;
wire   [8:0] buffer_1_address1;
wire   [7:0] buffer_1_q1;
reg   [8:0] buffer_2_address0;
reg    buffer_2_ce0;
reg    buffer_2_we0;
wire   [7:0] buffer_2_q0;
wire   [8:0] buffer_2_address1;
wire   [7:0] buffer_2_q1;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_idle;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_ready;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_hyst3_out_read;
wire   [8:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0;
wire   [7:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_d0;
wire   [8:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0;
wire   [7:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_d0;
wire   [8:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0;
wire   [7:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_d0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_idle;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_ready;
wire   [7:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_hyst4_out_din;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_hyst4_out_write;
wire   [8:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0;
wire   [8:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0;
wire   [8:0] grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0;
wire    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0;
reg    grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg;
wire   [0:0] icmp_ln74_fu_218_p2;
reg    grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg;
wire    ap_CS_fsm_state17;
reg   [9:0] phi_urem69_fu_66;
wire   [9:0] select_ln72_fu_431_p3;
reg    ap_block_state17_on_subcall_done;
reg   [9:0] phi_urem_fu_70;
wire   [9:0] select_ln72_1_fu_451_p3;
reg   [9:0] row_3_fu_74;
reg    buffer_ce1_local;
wire    ap_CS_fsm_state4;
reg    buffer_ce0_local;
reg    buffer_1_ce1_local;
reg    buffer_1_ce0_local;
reg    buffer_2_ce1_local;
reg    buffer_2_ce0_local;
wire   [9:0] outputRow_fu_243_p2;
wire   [9:0] grp_fu_273_p0;
wire   [2:0] grp_fu_273_p1;
wire   [9:0] grp_fu_273_p2;
wire   [1:0] trunc_ln11_fu_279_p1;
wire   [0:0] tmp_26_fu_283_p3;
wire   [1:0] add_ln12_fu_291_p2;
wire   [7:0] tmp_fu_311_p7;
wire   [7:0] tmp_s_fu_329_p7;
wire   [7:0] tmp_12_fu_347_p7;
wire   [7:0] tmp_13_fu_365_p7;
wire   [7:0] tmp_14_fu_383_p7;
wire   [7:0] tmp_15_fu_401_p7;
wire   [0:0] icmp_ln72_fu_425_p2;
wire   [9:0] add_ln72_fu_419_p2;
wire   [0:0] icmp_ln72_1_fu_445_p2;
wire   [9:0] add_ln72_1_fu_439_p2;
reg    grp_fu_273_ap_start;
wire    grp_fu_273_ap_done;
reg    grp_fu_273_ce;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire   [1:0] tmp_fu_311_p1;
wire   [1:0] tmp_fu_311_p3;
wire  signed [1:0] tmp_fu_311_p5;
wire   [1:0] tmp_s_fu_329_p1;
wire  signed [1:0] tmp_s_fu_329_p3;
wire   [1:0] tmp_s_fu_329_p5;
wire   [1:0] tmp_12_fu_347_p1;
wire   [1:0] tmp_12_fu_347_p3;
wire  signed [1:0] tmp_12_fu_347_p5;
wire   [1:0] tmp_13_fu_365_p1;
wire   [1:0] tmp_13_fu_365_p3;
wire  signed [1:0] tmp_13_fu_365_p5;
wire   [1:0] tmp_14_fu_383_p1;
wire  signed [1:0] tmp_14_fu_383_p3;
wire   [1:0] tmp_14_fu_383_p5;
wire   [1:0] tmp_15_fu_401_p1;
wire   [1:0] tmp_15_fu_401_p3;
wire  signed [1:0] tmp_15_fu_401_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 17'd1;
#0 grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg = 1'b0;
#0 grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg = 1'b0;
#0 phi_urem69_fu_66 = 10'd0;
#0 phi_urem_fu_70 = 10'd0;
#0 row_3_fu_74 = 10'd0;
end

canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_address0),
    .ce0(buffer_ce0),
    .we0(buffer_we0),
    .d0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_d0),
    .q0(buffer_q0),
    .address1(buffer_address1),
    .ce1(buffer_ce1_local),
    .q1(buffer_q1)
);

canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_1_address0),
    .ce0(buffer_1_ce0),
    .we0(buffer_1_we0),
    .d0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_d0),
    .q0(buffer_1_q0),
    .address1(buffer_1_address1),
    .ce1(buffer_1_ce1_local),
    .q1(buffer_1_q1)
);

canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_2_address0),
    .ce0(buffer_2_ce0),
    .we0(buffer_2_we0),
    .d0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_d0),
    .q0(buffer_2_q0),
    .address1(buffer_2_address1),
    .ce1(buffer_2_ce1_local),
    .q1(buffer_2_q1)
);

canny_top_hysteresis_4_Pipeline_VITIS_LOOP_78_2 grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start),
    .ap_done(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done),
    .ap_idle(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_idle),
    .ap_ready(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_ready),
    .hyst3_out_dout(hyst3_out_dout),
    .hyst3_out_empty_n(hyst3_out_empty_n),
    .hyst3_out_read(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_hyst3_out_read),
    .hyst3_out_num_data_valid(11'd0),
    .hyst3_out_fifo_cap(11'd0),
    .buffer_2_address0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0),
    .buffer_2_ce0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0),
    .buffer_2_we0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0),
    .buffer_2_d0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_d0),
    .buffer_1_address0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0),
    .buffer_1_ce0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0),
    .buffer_1_we0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0),
    .buffer_1_d0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_d0),
    .buffer_r_address0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0),
    .buffer_r_ce0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0),
    .buffer_r_we0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0),
    .buffer_r_d0(grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_d0),
    .empty(trunc_ln80_reg_539)
);

canny_top_hysteresis_4_Pipeline_VITIS_LOOP_143_5 grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start),
    .ap_done(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done),
    .ap_idle(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_idle),
    .ap_ready(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_ready),
    .hyst4_out_din(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_hyst4_out_din),
    .hyst4_out_full_n(hyst4_out_full_n),
    .hyst4_out_write(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_hyst4_out_write),
    .hyst4_out_num_data_valid(hyst4_out_num_data_valid),
    .hyst4_out_fifo_cap(hyst4_out_fifo_cap),
    .tmp_15(tmp_15_reg_640),
    .tmp_12(tmp_12_reg_625),
    .tmp_14(tmp_14_reg_635),
    .tmp_s(tmp_s_reg_620),
    .tmp_13(tmp_13_reg_630),
    .tmp(tmp_reg_615),
    .hasBottom(hasBottom_reg_553),
    .hasTop(hasTop_reg_548),
    .buffer_r_address0(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0),
    .buffer_r_ce0(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0),
    .buffer_r_q0(buffer_q0),
    .buffer_1_address0(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0),
    .buffer_1_ce0(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0),
    .buffer_1_q0(buffer_1_q0),
    .buffer_2_address0(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0),
    .buffer_2_ce0(grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0),
    .buffer_2_q0(buffer_2_q0),
    .select_ln12(select_ln12_reg_605),
    .empty(trunc_ln10_reg_610)
);

canny_top_srem_10ns_3ns_10_14_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 14 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 10 ))
srem_10ns_3ns_10_14_seq_1_U337(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_273_ap_start),
    .done(grp_fu_273_ap_done),
    .din0(grp_fu_273_p0),
    .din1(grp_fu_273_p1),
    .ce(grp_fu_273_ce),
    .dout(grp_fu_273_p2)
);

(* dissolve_hierarchy = "yes" *) canny_top_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U338(
    .din0(buffer_load_reg_563),
    .din1(buffer_1_load_reg_570),
    .din2(buffer_2_load_reg_577),
    .def(tmp_fu_311_p7),
    .sel(select_ln12_fu_297_p3),
    .dout(tmp_fu_311_p9)
);

(* dissolve_hierarchy = "yes" *) canny_top_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U339(
    .din0(buffer_load_reg_563),
    .din1(buffer_1_load_reg_570),
    .din2(buffer_2_load_reg_577),
    .def(tmp_s_fu_329_p7),
    .sel(trunc_ln10_fu_306_p1),
    .dout(tmp_s_fu_329_p9)
);

(* dissolve_hierarchy = "yes" *) canny_top_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U340(
    .din0(buffer_load_reg_563),
    .din1(buffer_1_load_reg_570),
    .din2(buffer_2_load_reg_577),
    .def(tmp_12_fu_347_p7),
    .sel(trunc_ln10_fu_306_p1),
    .dout(tmp_12_fu_347_p9)
);

(* dissolve_hierarchy = "yes" *) canny_top_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U341(
    .din0(buffer_load_1_reg_584),
    .din1(buffer_1_load_1_reg_591),
    .din2(buffer_2_load_1_reg_598),
    .def(tmp_13_fu_365_p7),
    .sel(select_ln12_fu_297_p3),
    .dout(tmp_13_fu_365_p9)
);

(* dissolve_hierarchy = "yes" *) canny_top_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U342(
    .din0(buffer_load_1_reg_584),
    .din1(buffer_1_load_1_reg_591),
    .din2(buffer_2_load_1_reg_598),
    .def(tmp_14_fu_383_p7),
    .sel(trunc_ln10_fu_306_p1),
    .dout(tmp_14_fu_383_p9)
);

(* dissolve_hierarchy = "yes" *) canny_top_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U343(
    .din0(buffer_load_1_reg_584),
    .din1(buffer_1_load_1_reg_591),
    .din2(buffer_2_load_1_reg_598),
    .def(tmp_15_fu_401_p7),
    .sel(trunc_ln10_fu_306_p1),
    .dout(tmp_15_fu_401_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln74_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg <= 1'b1;
        end else if ((grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_ready == 1'b1)) begin
            grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_24_fu_230_p3 == 1'd0) & (icmp_ln74_fu_218_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_ready == 1'b1)) begin
            grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_urem69_fu_66 <= 10'd0;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
        phi_urem69_fu_66 <= select_ln72_fu_431_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_urem_fu_70 <= 10'd0;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
        phi_urem_fu_70 <= select_ln72_1_fu_451_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        row_3_fu_74 <= 10'd0;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
        row_3_fu_74 <= rowsReceived_reg_530;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buffer_1_load_1_reg_591 <= buffer_1_q0;
        buffer_1_load_reg_570 <= buffer_1_q1;
        buffer_2_load_1_reg_598 <= buffer_2_q0;
        buffer_2_load_reg_577 <= buffer_2_q1;
        buffer_load_1_reg_584 <= buffer_q0;
        buffer_load_reg_563 <= buffer_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        hasBottom_reg_553 <= hasBottom_fu_262_p2;
        hasTop_reg_548 <= hasTop_fu_256_p2;
        tmp_25_reg_544 <= outputRow_fu_243_p2[32'd9];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rowsReceived_reg_530 <= rowsReceived_fu_224_p2;
        tmp_24_reg_535 <= row_3_fu_74[32'd9];
        trunc_ln80_reg_539 <= trunc_ln80_fu_238_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        select_ln12_reg_605 <= select_ln12_fu_297_p3;
        tmp_12_reg_625 <= tmp_12_fu_347_p9;
        tmp_13_reg_630 <= tmp_13_fu_365_p9;
        tmp_14_reg_635 <= tmp_14_fu_383_p9;
        tmp_15_reg_640 <= tmp_15_fu_401_p9;
        tmp_reg_615 <= tmp_fu_311_p9;
        tmp_s_reg_620 <= tmp_s_fu_329_p9;
        trunc_ln10_reg_610 <= trunc_ln10_fu_306_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state17_on_subcall_done)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln74_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln74_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_25_reg_544 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        buffer_1_address0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0;
    end else if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_1_address0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0;
    end else begin
        buffer_1_address0 = 64'd1;
    end
end

always @ (*) begin
    if (((tmp_25_reg_544 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        buffer_1_ce0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0;
    end else if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_1_ce0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0;
    end else begin
        buffer_1_ce0 = buffer_1_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_1_ce0_local = 1'b1;
    end else begin
        buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_1_ce1_local = 1'b1;
    end else begin
        buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_1_we0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0;
    end else begin
        buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_25_reg_544 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        buffer_2_address0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0;
    end else if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_2_address0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0;
    end else begin
        buffer_2_address0 = 64'd1;
    end
end

always @ (*) begin
    if (((tmp_25_reg_544 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        buffer_2_ce0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0;
    end else if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_2_ce0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0;
    end else begin
        buffer_2_ce0 = buffer_2_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_2_ce0_local = 1'b1;
    end else begin
        buffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_2_ce1_local = 1'b1;
    end else begin
        buffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_2_we0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0;
    end else begin
        buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_25_reg_544 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        buffer_address0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0;
    end else if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_address0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0;
    end else begin
        buffer_address0 = 64'd1;
    end
end

always @ (*) begin
    if (((tmp_25_reg_544 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        buffer_ce0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0;
    end else if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_ce0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0;
    end else begin
        buffer_ce0 = buffer_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_ce0_local = 1'b1;
    end else begin
        buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_ce1_local = 1'b1;
    end else begin
        buffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_24_reg_535 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        buffer_we0 = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0;
    end else begin
        buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_25_fu_248_p3 == 1'd0) & (1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_273_ap_start = 1'b1;
    end else begin
        grp_fu_273_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_273_ce = 1'b0;
    end else begin
        grp_fu_273_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln74_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_25_fu_248_p3 == 1'd1) & (1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((tmp_25_fu_248_p3 == 1'd0) & (1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_fu_291_p2 = ($signed(trunc_ln11_fu_279_p1) + $signed(2'd3));

assign add_ln72_1_fu_439_p2 = (phi_urem_fu_70 + 10'd1);

assign add_ln72_fu_419_p2 = (phi_urem69_fu_66 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state17_on_subcall_done = ((tmp_25_reg_544 == 1'd0) & (grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done == 1'b0) & (tmp_24_reg_535 == 1'd0));
end

assign buffer_1_address1 = 64'd0;

assign buffer_2_address1 = 64'd0;

assign buffer_address1 = 64'd0;

assign grp_fu_273_p0 = ($signed(row_3_fu_74) + $signed(10'd1022));

assign grp_fu_273_p1 = 10'd3;

assign grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg;

assign grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg;

assign hasBottom_fu_262_p2 = ((outputRow_fu_243_p2 != 10'd511) ? 1'b1 : 1'b0);

assign hasTop_fu_256_p2 = (($signed(outputRow_fu_243_p2) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign hyst3_out_read = grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165_hyst3_out_read;

assign hyst4_out_din = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_hyst4_out_din;

assign hyst4_out_write = grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175_hyst4_out_write;

assign icmp_ln72_1_fu_445_p2 = ((phi_urem_fu_70 == 10'd2) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_425_p2 = ((phi_urem69_fu_66 == 10'd2) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_218_p2 = ((row_3_fu_74 == 10'd513) ? 1'b1 : 1'b0);

assign outputRow_fu_243_p2 = ($signed(row_3_fu_74) + $signed(10'd1023));

assign rowsReceived_fu_224_p2 = (row_3_fu_74 + 10'd1);

assign select_ln12_fu_297_p3 = ((tmp_26_fu_283_p3[0:0] == 1'b1) ? add_ln12_fu_291_p2 : trunc_ln11_fu_279_p1);

assign select_ln72_1_fu_451_p3 = ((icmp_ln72_1_fu_445_p2[0:0] == 1'b1) ? 10'd0 : add_ln72_1_fu_439_p2);

assign select_ln72_fu_431_p3 = ((icmp_ln72_fu_425_p2[0:0] == 1'b1) ? 10'd0 : add_ln72_fu_419_p2);

assign tmp_12_fu_347_p7 = 'bx;

assign tmp_13_fu_365_p7 = 'bx;

assign tmp_14_fu_383_p7 = 'bx;

assign tmp_15_fu_401_p7 = 'bx;

assign tmp_24_fu_230_p3 = row_3_fu_74[32'd9];

assign tmp_25_fu_248_p3 = outputRow_fu_243_p2[32'd9];

assign tmp_26_fu_283_p3 = grp_fu_273_p2[32'd2];

assign tmp_fu_311_p7 = 'bx;

assign tmp_s_fu_329_p7 = 'bx;

assign trunc_ln10_fu_306_p1 = phi_urem69_fu_66[1:0];

assign trunc_ln11_fu_279_p1 = grp_fu_273_p2[1:0];

assign trunc_ln80_fu_238_p1 = phi_urem_fu_70[1:0];

endmodule //canny_top_hysteresis_4_s
