// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module canny_top_gaussian_blur (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        p_anonymous_namespace_rowsReceived_i,
        p_anonymous_namespace_rowsReceived_o,
        p_anonymous_namespace_rowsReceived_o_ap_vld,
        lineBuffer_1_address0,
        lineBuffer_1_ce0,
        lineBuffer_1_we0,
        lineBuffer_1_d0,
        lineBuffer_1_q0,
        lineBuffer_1_address1,
        lineBuffer_1_ce1,
        lineBuffer_1_q1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 74'd1;
parameter    ap_ST_fsm_state2 = 74'd2;
parameter    ap_ST_fsm_state3 = 74'd4;
parameter    ap_ST_fsm_state4 = 74'd8;
parameter    ap_ST_fsm_state5 = 74'd16;
parameter    ap_ST_fsm_state6 = 74'd32;
parameter    ap_ST_fsm_state7 = 74'd64;
parameter    ap_ST_fsm_state8 = 74'd128;
parameter    ap_ST_fsm_state9 = 74'd256;
parameter    ap_ST_fsm_state10 = 74'd512;
parameter    ap_ST_fsm_state11 = 74'd1024;
parameter    ap_ST_fsm_state12 = 74'd2048;
parameter    ap_ST_fsm_state13 = 74'd4096;
parameter    ap_ST_fsm_state14 = 74'd8192;
parameter    ap_ST_fsm_state15 = 74'd16384;
parameter    ap_ST_fsm_state16 = 74'd32768;
parameter    ap_ST_fsm_state17 = 74'd65536;
parameter    ap_ST_fsm_state18 = 74'd131072;
parameter    ap_ST_fsm_state19 = 74'd262144;
parameter    ap_ST_fsm_state20 = 74'd524288;
parameter    ap_ST_fsm_state21 = 74'd1048576;
parameter    ap_ST_fsm_state22 = 74'd2097152;
parameter    ap_ST_fsm_state23 = 74'd4194304;
parameter    ap_ST_fsm_state24 = 74'd8388608;
parameter    ap_ST_fsm_state25 = 74'd16777216;
parameter    ap_ST_fsm_state26 = 74'd33554432;
parameter    ap_ST_fsm_state27 = 74'd67108864;
parameter    ap_ST_fsm_state28 = 74'd134217728;
parameter    ap_ST_fsm_state29 = 74'd268435456;
parameter    ap_ST_fsm_state30 = 74'd536870912;
parameter    ap_ST_fsm_state31 = 74'd1073741824;
parameter    ap_ST_fsm_state32 = 74'd2147483648;
parameter    ap_ST_fsm_state33 = 74'd4294967296;
parameter    ap_ST_fsm_state34 = 74'd8589934592;
parameter    ap_ST_fsm_state35 = 74'd17179869184;
parameter    ap_ST_fsm_state36 = 74'd34359738368;
parameter    ap_ST_fsm_state37 = 74'd68719476736;
parameter    ap_ST_fsm_state38 = 74'd137438953472;
parameter    ap_ST_fsm_state39 = 74'd274877906944;
parameter    ap_ST_fsm_state40 = 74'd549755813888;
parameter    ap_ST_fsm_state41 = 74'd1099511627776;
parameter    ap_ST_fsm_state42 = 74'd2199023255552;
parameter    ap_ST_fsm_state43 = 74'd4398046511104;
parameter    ap_ST_fsm_state44 = 74'd8796093022208;
parameter    ap_ST_fsm_state45 = 74'd17592186044416;
parameter    ap_ST_fsm_state46 = 74'd35184372088832;
parameter    ap_ST_fsm_state47 = 74'd70368744177664;
parameter    ap_ST_fsm_state48 = 74'd140737488355328;
parameter    ap_ST_fsm_state49 = 74'd281474976710656;
parameter    ap_ST_fsm_state50 = 74'd562949953421312;
parameter    ap_ST_fsm_state51 = 74'd1125899906842624;
parameter    ap_ST_fsm_state52 = 74'd2251799813685248;
parameter    ap_ST_fsm_state53 = 74'd4503599627370496;
parameter    ap_ST_fsm_state54 = 74'd9007199254740992;
parameter    ap_ST_fsm_state55 = 74'd18014398509481984;
parameter    ap_ST_fsm_state56 = 74'd36028797018963968;
parameter    ap_ST_fsm_state57 = 74'd72057594037927936;
parameter    ap_ST_fsm_state58 = 74'd144115188075855872;
parameter    ap_ST_fsm_state59 = 74'd288230376151711744;
parameter    ap_ST_fsm_state60 = 74'd576460752303423488;
parameter    ap_ST_fsm_state61 = 74'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 74'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 74'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 74'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 74'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 74'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 74'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 74'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 74'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 74'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 74'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 74'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 74'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 74'd9444732965739290427392;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [8:0] input_r_address0;
output   input_r_ce0;
input  [7:0] input_r_q0;
output  [8:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;
input  [31:0] p_anonymous_namespace_rowsReceived_i;
output  [31:0] p_anonymous_namespace_rowsReceived_o;
output   p_anonymous_namespace_rowsReceived_o_ap_vld;
output  [11:0] lineBuffer_1_address0;
output   lineBuffer_1_ce0;
output   lineBuffer_1_we0;
output  [7:0] lineBuffer_1_d0;
input  [7:0] lineBuffer_1_q0;
output  [11:0] lineBuffer_1_address1;
output   lineBuffer_1_ce1;
input  [7:0] lineBuffer_1_q1;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[7:0] output_r_d0;
reg[31:0] p_anonymous_namespace_rowsReceived_o;
reg p_anonymous_namespace_rowsReceived_o_ap_vld;
reg[11:0] lineBuffer_1_address0;
reg lineBuffer_1_ce0;
reg lineBuffer_1_we0;
reg lineBuffer_1_ce1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [73:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] p_anonymous_namespace_rowsReceived_load_reg_355;
reg    ap_block_state1;
wire   [11:0] tmp_s_fu_139_p3;
reg   [11:0] tmp_s_reg_376;
wire    ap_CS_fsm_state36;
wire   [31:0] outputRow_fu_148_p2;
reg   [31:0] outputRow_reg_381;
reg   [0:0] tmp_reg_387;
wire   [31:0] sub_ln28_fu_161_p2;
reg   [31:0] sub_ln28_reg_391;
wire    ap_CS_fsm_state37;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done;
wire   [31:0] add_ln78_fu_199_p2;
reg   [31:0] add_ln78_reg_401;
wire    ap_CS_fsm_state72;
reg   [0:0] tmp_61_reg_406;
wire   [31:0] sub_ln28_1_fu_212_p2;
reg   [31:0] sub_ln28_1_reg_411;
reg   [22:0] tmp_62_reg_416;
wire   [31:0] sub_ln30_fu_227_p2;
reg   [31:0] sub_ln30_reg_421;
wire   [31:0] add_ln78_1_fu_232_p2;
reg   [31:0] add_ln78_1_reg_426;
reg   [0:0] tmp_63_reg_431;
wire   [31:0] sub_ln28_2_fu_245_p2;
reg   [31:0] sub_ln28_2_reg_436;
reg   [22:0] tmp_64_reg_441;
wire   [31:0] sub_ln30_1_fu_260_p2;
reg   [31:0] sub_ln30_1_reg_446;
wire   [2:0] select_ln23_fu_283_p3;
reg   [2:0] select_ln23_reg_451;
wire   [31:0] add_ln78_2_fu_291_p2;
reg   [31:0] add_ln78_2_reg_457;
reg   [0:0] tmp_67_reg_462;
wire   [31:0] sub_ln28_3_fu_304_p2;
reg   [31:0] sub_ln28_3_reg_467;
reg   [22:0] tmp_68_reg_472;
wire   [31:0] sub_ln30_3_fu_319_p2;
reg   [31:0] sub_ln30_3_reg_477;
wire   [31:0] sub_ln30_4_fu_324_p2;
reg   [31:0] sub_ln30_4_reg_482;
wire   [11:0] tmp_59_fu_329_p3;
reg   [11:0] tmp_59_reg_487;
wire    ap_CS_fsm_state73;
reg   [0:0] tmp_69_reg_492;
reg   [22:0] tmp_70_reg_497;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_idle;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_ready;
wire   [8:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_address0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_ce0;
wire   [8:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_address0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_ce0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_we0;
wire   [7:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_d0;
wire   [11:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_address0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_ce0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_we0;
wire   [7:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_d0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_done;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_idle;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_ready;
wire   [8:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_address0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_ce0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_we0;
wire   [7:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_d0;
wire   [11:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_address0;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_ce0;
wire   [11:0] grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_address1;
wire    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_ce1;
reg   [0:0] ap_phi_mux_valid_out_write_assign_phi_fu_64_p4;
reg   [0:0] valid_out_write_assign_reg_60;
wire    ap_CS_fsm_state74;
reg    ap_block_state74_on_subcall_done;
reg    grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg;
reg    grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start_reg;
wire   [31:0] add_ln61_fu_123_p2;
wire   [3:0] grp_fu_117_p1;
wire   [2:0] grp_fu_117_p2;
wire   [2:0] trunc_ln58_fu_135_p1;
wire   [22:0] tmp_65_fu_166_p4;
wire   [0:0] icmp_ln29_fu_175_p2;
wire   [31:0] sub_ln30_2_fu_181_p2;
wire   [31:0] grp_fu_193_p0;
wire   [3:0] grp_fu_193_p1;
wire   [31:0] grp_fu_193_p2;
wire   [2:0] trunc_ln23_fu_265_p1;
wire   [0:0] tmp_66_fu_269_p3;
wire   [2:0] add_ln23_fu_277_p2;
reg    grp_fu_117_ap_start;
wire    grp_fu_117_ap_done;
reg    grp_fu_117_ce;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state35;
reg    grp_fu_193_ap_start;
wire    grp_fu_193_ap_done;
reg    grp_fu_193_ce;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state47;
wire    ap_CS_fsm_state48;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state50;
wire    ap_CS_fsm_state51;
wire    ap_CS_fsm_state52;
wire    ap_CS_fsm_state53;
wire    ap_CS_fsm_state54;
wire    ap_CS_fsm_state55;
wire    ap_CS_fsm_state56;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state59;
wire    ap_CS_fsm_state60;
wire    ap_CS_fsm_state61;
wire    ap_CS_fsm_state62;
wire    ap_CS_fsm_state63;
wire    ap_CS_fsm_state64;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state66;
wire    ap_CS_fsm_state67;
wire    ap_CS_fsm_state68;
wire    ap_CS_fsm_state69;
wire    ap_CS_fsm_state70;
wire    ap_CS_fsm_state71;
reg   [73:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
reg    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 74'd1;
#0 grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg = 1'b0;
#0 grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start_reg = 1'b0;
end

canny_top_gaussian_blur_Pipeline_VITIS_LOOP_57_1 grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start),
    .ap_done(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done),
    .ap_idle(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_idle),
    .ap_ready(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_ready),
    .zext_ln58(tmp_s_reg_376),
    .input_r_address0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_address0),
    .input_r_ce0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_ce0),
    .input_r_q0(input_r_q0),
    .output_r_address0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_address0),
    .output_r_ce0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_ce0),
    .output_r_we0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_we0),
    .output_r_d0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_d0),
    .lineBuffer_1_address0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_address0),
    .lineBuffer_1_ce0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_ce0),
    .lineBuffer_1_we0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_we0),
    .lineBuffer_1_d0(grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_d0)
);

canny_top_gaussian_blur_Pipeline_VITIS_LOOP_70_2 grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start),
    .ap_done(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_done),
    .ap_idle(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_idle),
    .ap_ready(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_ready),
    .empty_38(tmp_70_reg_497),
    .empty_39(tmp_68_reg_472),
    .empty_40(tmp_64_reg_441),
    .empty_41(tmp_62_reg_416),
    .sub_ln30(sub_ln30_reg_421),
    .add_ln78(add_ln78_reg_401),
    .empty_42(tmp_61_reg_406),
    .sub_ln28_1(sub_ln28_1_reg_411),
    .zext_ln95(tmp_59_reg_487),
    .select_ln23(select_ln23_reg_451),
    .sub_ln30_1(sub_ln30_1_reg_446),
    .add_ln78_1(add_ln78_1_reg_426),
    .empty_43(tmp_63_reg_431),
    .sub_ln28_2(sub_ln28_2_reg_436),
    .sub_ln30_3(sub_ln30_3_reg_477),
    .add_ln78_2(add_ln78_2_reg_457),
    .empty_44(tmp_67_reg_462),
    .sub_ln28_3(sub_ln28_3_reg_467),
    .sub_ln30_4(sub_ln30_4_reg_482),
    .p_anonymous_namespace_rowsReceived_load(p_anonymous_namespace_rowsReceived_load_reg_355),
    .empty(tmp_69_reg_492),
    .sub_ln28(sub_ln28_reg_391),
    .output_r_address0(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_address0),
    .output_r_ce0(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_ce0),
    .output_r_we0(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_we0),
    .output_r_d0(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_d0),
    .lineBuffer_1_address0(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_address0),
    .lineBuffer_1_ce0(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_ce0),
    .lineBuffer_1_q0(lineBuffer_1_q0),
    .lineBuffer_1_address1(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_address1),
    .lineBuffer_1_ce1(grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_ce1),
    .lineBuffer_1_q1(lineBuffer_1_q1)
);

canny_top_srem_32ns_4ns_3_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
srem_32ns_4ns_3_36_seq_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_117_ap_start),
    .done(grp_fu_117_ap_done),
    .din0(p_anonymous_namespace_rowsReceived_i),
    .din1(grp_fu_117_p1),
    .ce(grp_fu_117_ce),
    .dout(grp_fu_117_p2)
);

canny_top_srem_32ns_4ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
srem_32ns_4ns_32_36_seq_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_193_ap_start),
    .done(grp_fu_193_ap_done),
    .din0(grp_fu_193_p0),
    .din1(grp_fu_193_p1),
    .ce(grp_fu_193_ce),
    .dout(grp_fu_193_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state74) & (1'b0 == ap_block_state74_on_subcall_done))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state36)) begin
            grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_ready == 1'b1)) begin
            grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state73)) begin
            grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start_reg <= 1'b1;
        end else if ((grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_ready == 1'b1)) begin
            grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0) & (1'b0 == ap_block_state74_on_subcall_done))) begin
        valid_out_write_assign_reg_60 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state37) & (grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b1) & (tmp_reg_387 == 1'd1))) begin
        valid_out_write_assign_reg_60 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state72)) begin
        add_ln78_1_reg_426 <= add_ln78_1_fu_232_p2;
        add_ln78_2_reg_457 <= add_ln78_2_fu_291_p2;
        add_ln78_reg_401 <= add_ln78_fu_199_p2;
        select_ln23_reg_451 <= select_ln23_fu_283_p3;
        sub_ln28_1_reg_411 <= sub_ln28_1_fu_212_p2;
        sub_ln28_2_reg_436 <= sub_ln28_2_fu_245_p2;
        sub_ln28_3_reg_467 <= sub_ln28_3_fu_304_p2;
        sub_ln30_1_reg_446 <= sub_ln30_1_fu_260_p2;
        sub_ln30_3_reg_477 <= sub_ln30_3_fu_319_p2;
        sub_ln30_4_reg_482 <= sub_ln30_4_fu_324_p2;
        sub_ln30_reg_421 <= sub_ln30_fu_227_p2;
        tmp_61_reg_406 <= add_ln78_fu_199_p2[32'd31];
        tmp_62_reg_416 <= {{add_ln78_fu_199_p2[31:9]}};
        tmp_63_reg_431 <= add_ln78_1_fu_232_p2[32'd31];
        tmp_64_reg_441 <= {{add_ln78_1_fu_232_p2[31:9]}};
        tmp_67_reg_462 <= add_ln78_2_fu_291_p2[32'd31];
        tmp_68_reg_472 <= {{add_ln78_2_fu_291_p2[31:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        outputRow_reg_381 <= outputRow_fu_148_p2;
        tmp_reg_387 <= outputRow_fu_148_p2[32'd31];
        tmp_s_reg_376[11 : 9] <= tmp_s_fu_139_p3[11 : 9];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_anonymous_namespace_rowsReceived_load_reg_355 <= p_anonymous_namespace_rowsReceived_i;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state37) & (grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b1))) begin
        sub_ln28_reg_391 <= sub_ln28_fu_161_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        tmp_59_reg_487[11 : 9] <= tmp_59_fu_329_p3[11 : 9];
        tmp_69_reg_492 <= p_anonymous_namespace_rowsReceived_load_reg_355[32'd31];
        tmp_70_reg_497 <= {{p_anonymous_namespace_rowsReceived_load_reg_355[31:9]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

always @ (*) begin
    if ((grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state37_blk = 1'b1;
    end else begin
        ap_ST_fsm_state37_blk = 1'b0;
    end
end

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state74_on_subcall_done)) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (1'b0 == ap_block_state74_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        ap_phi_mux_valid_out_write_assign_phi_fu_64_p4 = 1'd1;
    end else begin
        ap_phi_mux_valid_out_write_assign_phi_fu_64_p4 = valid_out_write_assign_reg_60;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (1'b0 == ap_block_state74_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        grp_fu_117_ap_start = 1'b1;
    end else begin
        grp_fu_117_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) 
    | (1'b1 == ap_CS_fsm_state36))) begin
        grp_fu_117_ce = 1'b1;
    end else begin
        grp_fu_117_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) & (grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b1) & (tmp_reg_387 == 1'd0))) begin
        grp_fu_193_ap_start = 1'b1;
    end else begin
        grp_fu_193_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 
    == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state37))) begin
        grp_fu_193_ce = 1'b1;
    end else begin
        grp_fu_193_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        lineBuffer_1_address0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        lineBuffer_1_address0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_address0;
    end else begin
        lineBuffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        lineBuffer_1_ce0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        lineBuffer_1_ce0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_ce0;
    end else begin
        lineBuffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        lineBuffer_1_ce1 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_ce1;
    end else begin
        lineBuffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        lineBuffer_1_we0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_we0;
    end else begin
        lineBuffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        output_r_address0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_address0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_address0;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        output_r_ce0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_ce0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_ce0;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        output_r_d0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_d0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_d0;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) & (tmp_reg_387 == 1'd0))) begin
        output_r_we0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_output_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_we0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_output_r_we0;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_anonymous_namespace_rowsReceived_o = add_ln61_fu_123_p2;
    end else begin
        p_anonymous_namespace_rowsReceived_o = p_anonymous_namespace_rowsReceived_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_anonymous_namespace_rowsReceived_o_ap_vld = 1'b1;
    end else begin
        p_anonymous_namespace_rowsReceived_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((1'b1 == ap_CS_fsm_state37) & (grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b1) & (tmp_reg_387 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else if (((1'b1 == ap_CS_fsm_state37) & (grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_done == 1'b1) & (tmp_reg_387 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            if (((1'b1 == ap_CS_fsm_state74) & (1'b0 == ap_block_state74_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_fu_277_p2 = ($signed(trunc_ln23_fu_265_p1) + $signed(3'd5));

assign add_ln61_fu_123_p2 = (p_anonymous_namespace_rowsReceived_i + 32'd1);

assign add_ln78_1_fu_232_p2 = ($signed(p_anonymous_namespace_rowsReceived_load_reg_355) + $signed(32'd4294967293));

assign add_ln78_2_fu_291_p2 = ($signed(p_anonymous_namespace_rowsReceived_load_reg_355) + $signed(32'd4294967295));

assign add_ln78_fu_199_p2 = ($signed(p_anonymous_namespace_rowsReceived_load_reg_355) + $signed(32'd4294967292));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state74_on_subcall_done = ((grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_done == 1'b0) & (tmp_reg_387 == 1'd0));
end

assign ap_return = ap_phi_mux_valid_out_write_assign_phi_fu_64_p4;

assign grp_fu_117_p1 = 32'd5;

assign grp_fu_193_p0 = ((icmp_ln29_fu_175_p2[0:0] == 1'b1) ? sub_ln30_2_fu_181_p2 : outputRow_reg_381);

assign grp_fu_193_p1 = 32'd5;

assign grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_ap_start_reg;

assign grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_ap_start_reg;

assign icmp_ln29_fu_175_p2 = (($signed(tmp_65_fu_166_p4) > $signed(23'd0)) ? 1'b1 : 1'b0);

assign input_r_address0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_address0;

assign input_r_ce0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_input_r_ce0;

assign lineBuffer_1_address1 = grp_gaussian_blur_Pipeline_VITIS_LOOP_70_2_fu_83_lineBuffer_1_address1;

assign lineBuffer_1_d0 = grp_gaussian_blur_Pipeline_VITIS_LOOP_57_1_fu_72_lineBuffer_1_d0;

assign outputRow_fu_148_p2 = ($signed(p_anonymous_namespace_rowsReceived_load_reg_355) + $signed(32'd4294967294));

assign select_ln23_fu_283_p3 = ((tmp_66_fu_269_p3[0:0] == 1'b1) ? add_ln23_fu_277_p2 : trunc_ln23_fu_265_p1);

assign sub_ln28_1_fu_212_p2 = (32'd4 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln28_2_fu_245_p2 = (32'd3 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln28_3_fu_304_p2 = (32'd1 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln28_fu_161_p2 = (32'd0 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln30_1_fu_260_p2 = (32'd1025 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln30_2_fu_181_p2 = (32'd1024 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln30_3_fu_319_p2 = (32'd1023 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln30_4_fu_324_p2 = (32'd1022 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign sub_ln30_fu_227_p2 = (32'd1026 - p_anonymous_namespace_rowsReceived_load_reg_355);

assign tmp_59_fu_329_p3 = {{select_ln23_reg_451}, {9'd0}};

assign tmp_65_fu_166_p4 = {{outputRow_reg_381[31:9]}};

assign tmp_66_fu_269_p3 = grp_fu_193_p2[32'd3];

assign tmp_s_fu_139_p3 = {{trunc_ln58_fu_135_p1}, {9'd0}};

assign trunc_ln23_fu_265_p1 = grp_fu_193_p2[2:0];

assign trunc_ln58_fu_135_p1 = grp_fu_117_p2[2:0];

always @ (posedge ap_clk) begin
    tmp_s_reg_376[8:0] <= 9'b000000000;
    tmp_59_reg_487[8:0] <= 9'b000000000;
end

endmodule //canny_top_gaussian_blur
