// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module canny_top_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_nonmax_address0,
        out_nonmax_ce0,
        out_nonmax_we0,
        out_nonmax_d0,
        result_2,
        result,
        empty,
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0,
        p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0,
        p_anonymous_namespace_lineBuffer_25_magnitude_0_q0,
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address1,
        p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1,
        p_anonymous_namespace_lineBuffer_25_magnitude_0_q1,
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0,
        p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0,
        p_anonymous_namespace_lineBuffer_25_magnitude_1_q0,
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address1,
        p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1,
        p_anonymous_namespace_lineBuffer_25_magnitude_1_q1,
        p_anonymous_namespace_lineBuffer_direction_address0,
        p_anonymous_namespace_lineBuffer_direction_ce0,
        p_anonymous_namespace_lineBuffer_direction_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] out_nonmax_address0;
output   out_nonmax_ce0;
output   out_nonmax_we0;
output  [10:0] out_nonmax_d0;
input  [1:0] result_2;
input  [1:0] result;
input  [1:0] empty;
output  [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_0_address0;
output   p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0;
input  [10:0] p_anonymous_namespace_lineBuffer_25_magnitude_0_q0;
output  [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_0_address1;
output   p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1;
input  [10:0] p_anonymous_namespace_lineBuffer_25_magnitude_0_q1;
output  [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_1_address0;
output   p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0;
input  [10:0] p_anonymous_namespace_lineBuffer_25_magnitude_1_q0;
output  [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_1_address1;
output   p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1;
input  [10:0] p_anonymous_namespace_lineBuffer_25_magnitude_1_q1;
output  [10:0] p_anonymous_namespace_lineBuffer_direction_address0;
output   p_anonymous_namespace_lineBuffer_direction_ce0;
input  [1:0] p_anonymous_namespace_lineBuffer_direction_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln81_reg_619;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] column_2_reg_610;
reg   [8:0] column_2_reg_610_pp0_iter1_reg;
wire   [0:0] icmp_ln81_fu_352_p2;
wire   [7:0] lshr_ln3_fu_371_p4;
reg   [7:0] lshr_ln3_reg_628;
wire   [0:0] trunc_ln81_fu_395_p1;
reg   [0:0] trunc_ln81_reg_644;
wire    ap_block_pp0_stage1_11001;
wire   [10:0] centre_magnitude_fu_422_p3;
reg   [10:0] centre_magnitude_reg_672;
wire   [1:0] p_anonymous_namespace_lineBuffer_direction_q0_local;
reg   [1:0] centre_direction_reg_679;
wire   [10:0] select_ln123_fu_572_p3;
reg   [10:0] select_ln123_reg_743;
reg   [10:0] ap_phi_mux_neighbourOne_4_phi_fu_271_p8;
wire   [10:0] grp_fu_324_p3;
wire   [10:0] ap_phi_reg_pp0_iter1_neighbourOne_4_reg_268;
wire   [10:0] neighbourOne_3_fu_528_p3;
reg   [10:0] ap_phi_mux_neighbourTwo_4_phi_fu_284_p8;
wire   [10:0] grp_fu_334_p3;
wire   [10:0] ap_phi_reg_pp0_iter1_neighbourTwo_4_reg_281;
wire   [10:0] neighbourTwo_3_fu_536_p3;
wire   [63:0] zext_ln83_fu_366_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln83_1_fu_389_p1;
wire   [63:0] zext_ln107_fu_404_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln110_fu_416_p1;
wire   [63:0] zext_ln99_fu_447_p1;
wire   [63:0] zext_ln102_fu_460_p1;
wire   [63:0] zext_ln115_fu_473_p1;
wire   [63:0] zext_ln118_fu_486_p1;
wire   [63:0] zext_ln91_fu_499_p1;
wire   [63:0] zext_ln94_fu_512_p1;
wire   [63:0] zext_ln81_fu_579_p1;
reg   [8:0] column_fu_58;
wire   [8:0] add_ln81_fu_518_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_column_2;
reg    p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0_local;
reg   [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local;
reg    p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1_local;
reg   [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local;
reg    p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0_local;
reg   [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local;
reg    p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1_local;
reg   [9:0] p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local;
reg    p_anonymous_namespace_lineBuffer_direction_ce0_local;
reg    out_nonmax_we0_local;
reg    out_nonmax_ce0_local;
wire   [8:0] grp_fu_294_p2;
wire   [8:0] grp_fu_309_p2;
wire   [10:0] tmp_s_fu_358_p3;
wire   [9:0] tmp_9_fu_381_p3;
wire   [9:0] tmp_10_fu_398_p3;
wire   [9:0] tmp_11_fu_410_p3;
wire   [7:0] grp_fu_299_p4;
wire   [9:0] tmp_16_fu_440_p3;
wire   [7:0] grp_fu_314_p4;
wire   [9:0] tmp_17_fu_453_p3;
wire   [9:0] tmp_14_fu_466_p3;
wire   [9:0] tmp_15_fu_479_p3;
wire   [9:0] tmp_12_fu_492_p3;
wire   [9:0] tmp_13_fu_505_p3;
wire   [0:0] icmp_ln123_fu_544_p2;
wire   [0:0] icmp_ln124_fu_555_p2;
wire   [0:0] xor_ln123_fu_549_p2;
wire   [0:0] xor_ln124_fu_560_p2;
wire   [0:0] and_ln123_fu_566_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_209;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 column_fu_58 = 9'd0;
#0 ap_done_reg = 1'b0;
end

canny_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        column_fu_58 <= 9'd1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        column_fu_58 <= add_ln81_fu_518_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        centre_direction_reg_679 <= p_anonymous_namespace_lineBuffer_direction_q0;
        centre_magnitude_reg_672 <= centre_magnitude_fu_422_p3;
        trunc_ln81_reg_644 <= trunc_ln81_fu_395_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        column_2_reg_610 <= ap_sig_allocacmp_column_2;
        column_2_reg_610_pp0_iter1_reg <= column_2_reg_610;
        icmp_ln81_reg_619 <= icmp_ln81_fu_352_p2;
        lshr_ln3_reg_628 <= {{ap_sig_allocacmp_column_2[8:1]}};
        select_ln123_reg_743 <= select_ln123_fu_572_p3;
    end
end

always @ (*) begin
    if (((icmp_ln81_reg_619 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd2))) begin
        ap_phi_mux_neighbourOne_4_phi_fu_271_p8 = neighbourOne_3_fu_528_p3;
    end else if ((((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd0)) | ((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd1)) | ((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd3)))) begin
        ap_phi_mux_neighbourOne_4_phi_fu_271_p8 = grp_fu_324_p3;
    end else begin
        ap_phi_mux_neighbourOne_4_phi_fu_271_p8 = ap_phi_reg_pp0_iter1_neighbourOne_4_reg_268;
    end
end

always @ (*) begin
    if (((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd2))) begin
        ap_phi_mux_neighbourTwo_4_phi_fu_284_p8 = neighbourTwo_3_fu_536_p3;
    end else if ((((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd0)) | ((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd1)) | ((icmp_ln81_reg_619 == 1'd0) & (centre_direction_reg_679 == 2'd3)))) begin
        ap_phi_mux_neighbourTwo_4_phi_fu_284_p8 = grp_fu_334_p3;
    end else begin
        ap_phi_mux_neighbourTwo_4_phi_fu_284_p8 = ap_phi_reg_pp0_iter1_neighbourTwo_4_reg_281;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_column_2 = 9'd1;
    end else begin
        ap_sig_allocacmp_column_2 = column_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_nonmax_ce0_local = 1'b1;
    end else begin
        out_nonmax_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_nonmax_we0_local = 1'b1;
    end else begin
        out_nonmax_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local = zext_ln94_fu_512_p1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local = zext_ln118_fu_486_p1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local = zext_ln102_fu_460_p1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local = zext_ln110_fu_416_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local = zext_ln83_1_fu_389_p1;
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_209)) begin
        if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local = zext_ln91_fu_499_p1;
        end else if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local = zext_ln115_fu_473_p1;
        end else if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local = zext_ln99_fu_447_p1;
        end else if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local = zext_ln107_fu_404_p1;
        end else begin
            p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local = 'bx;
        end
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1)))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1)))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local = zext_ln94_fu_512_p1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local = zext_ln118_fu_486_p1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local = zext_ln102_fu_460_p1;
    end else if (((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local = zext_ln110_fu_416_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local = zext_ln83_1_fu_389_p1;
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_209)) begin
        if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local = zext_ln91_fu_499_p1;
        end else if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local = zext_ln115_fu_473_p1;
        end else if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local = zext_ln99_fu_447_p1;
        end else if ((p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2)) begin
            p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local = zext_ln107_fu_404_p1;
        end else begin
            p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local = 'bx;
        end
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1)))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd2)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd0)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd3)) | ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (p_anonymous_namespace_lineBuffer_direction_q0_local == 2'd1)))) begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_lineBuffer_direction_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_direction_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln81_fu_518_p2 = (column_2_reg_610 + 9'd1);

assign and_ln123_fu_566_p2 = (xor_ln124_fu_560_p2 & xor_ln123_fu_549_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_209 = ((icmp_ln81_reg_619 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter1_neighbourOne_4_reg_268 = 'bx;

assign ap_phi_reg_pp0_iter1_neighbourTwo_4_reg_281 = 'bx;

assign ap_ready = ap_ready_sig;

assign centre_magnitude_fu_422_p3 = ((trunc_ln81_fu_395_p1[0:0] == 1'b1) ? p_anonymous_namespace_lineBuffer_25_magnitude_1_q0 : p_anonymous_namespace_lineBuffer_25_magnitude_0_q0);

assign grp_fu_294_p2 = ($signed(column_2_reg_610) + $signed(9'd511));

assign grp_fu_299_p4 = {{grp_fu_294_p2[8:1]}};

assign grp_fu_309_p2 = (column_2_reg_610 + 9'd1);

assign grp_fu_314_p4 = {{grp_fu_309_p2[8:1]}};

assign grp_fu_324_p3 = ((trunc_ln81_reg_644[0:0] == 1'b1) ? p_anonymous_namespace_lineBuffer_25_magnitude_0_q1 : p_anonymous_namespace_lineBuffer_25_magnitude_1_q1);

assign grp_fu_334_p3 = ((trunc_ln81_reg_644[0:0] == 1'b1) ? p_anonymous_namespace_lineBuffer_25_magnitude_0_q0 : p_anonymous_namespace_lineBuffer_25_magnitude_1_q0);

assign icmp_ln123_fu_544_p2 = ((centre_magnitude_reg_672 < ap_phi_mux_neighbourOne_4_phi_fu_271_p8) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_555_p2 = ((centre_magnitude_reg_672 < ap_phi_mux_neighbourTwo_4_phi_fu_284_p8) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_352_p2 = ((ap_sig_allocacmp_column_2 == 9'd511) ? 1'b1 : 1'b0);

assign lshr_ln3_fu_371_p4 = {{ap_sig_allocacmp_column_2[8:1]}};

assign neighbourOne_3_fu_528_p3 = ((trunc_ln81_reg_644[0:0] == 1'b1) ? p_anonymous_namespace_lineBuffer_25_magnitude_1_q1 : p_anonymous_namespace_lineBuffer_25_magnitude_0_q1);

assign neighbourTwo_3_fu_536_p3 = ((trunc_ln81_reg_644[0:0] == 1'b1) ? p_anonymous_namespace_lineBuffer_25_magnitude_1_q0 : p_anonymous_namespace_lineBuffer_25_magnitude_0_q0);

assign out_nonmax_address0 = zext_ln81_fu_579_p1;

assign out_nonmax_ce0 = out_nonmax_ce0_local;

assign out_nonmax_d0 = select_ln123_reg_743;

assign out_nonmax_we0 = out_nonmax_we0_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_0_address0 = p_anonymous_namespace_lineBuffer_25_magnitude_0_address0_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_0_address1 = p_anonymous_namespace_lineBuffer_25_magnitude_0_address1_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0 = p_anonymous_namespace_lineBuffer_25_magnitude_0_ce0_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1 = p_anonymous_namespace_lineBuffer_25_magnitude_0_ce1_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_1_address0 = p_anonymous_namespace_lineBuffer_25_magnitude_1_address0_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_1_address1 = p_anonymous_namespace_lineBuffer_25_magnitude_1_address1_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0 = p_anonymous_namespace_lineBuffer_25_magnitude_1_ce0_local;

assign p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1 = p_anonymous_namespace_lineBuffer_25_magnitude_1_ce1_local;

assign p_anonymous_namespace_lineBuffer_direction_address0 = zext_ln83_fu_366_p1;

assign p_anonymous_namespace_lineBuffer_direction_ce0 = p_anonymous_namespace_lineBuffer_direction_ce0_local;

assign p_anonymous_namespace_lineBuffer_direction_q0_local = p_anonymous_namespace_lineBuffer_direction_q0;

assign select_ln123_fu_572_p3 = ((and_ln123_fu_566_p2[0:0] == 1'b1) ? centre_magnitude_reg_672 : 11'd0);

assign tmp_10_fu_398_p3 = {{result}, {lshr_ln3_reg_628}};

assign tmp_11_fu_410_p3 = {{empty}, {lshr_ln3_reg_628}};

assign tmp_12_fu_492_p3 = {{result_2}, {grp_fu_299_p4}};

assign tmp_13_fu_505_p3 = {{result_2}, {grp_fu_314_p4}};

assign tmp_14_fu_466_p3 = {{result}, {grp_fu_314_p4}};

assign tmp_15_fu_479_p3 = {{empty}, {grp_fu_299_p4}};

assign tmp_16_fu_440_p3 = {{result}, {grp_fu_299_p4}};

assign tmp_17_fu_453_p3 = {{empty}, {grp_fu_314_p4}};

assign tmp_9_fu_381_p3 = {{result_2}, {lshr_ln3_fu_371_p4}};

assign tmp_s_fu_358_p3 = {{result_2}, {ap_sig_allocacmp_column_2}};

assign trunc_ln81_fu_395_p1 = column_2_reg_610[0:0];

assign xor_ln123_fu_549_p2 = (icmp_ln123_fu_544_p2 ^ 1'd1);

assign xor_ln124_fu_560_p2 = (icmp_ln124_fu_555_p2 ^ 1'd1);

assign zext_ln102_fu_460_p1 = tmp_17_fu_453_p3;

assign zext_ln107_fu_404_p1 = tmp_10_fu_398_p3;

assign zext_ln110_fu_416_p1 = tmp_11_fu_410_p3;

assign zext_ln115_fu_473_p1 = tmp_14_fu_466_p3;

assign zext_ln118_fu_486_p1 = tmp_15_fu_479_p3;

assign zext_ln81_fu_579_p1 = column_2_reg_610_pp0_iter1_reg;

assign zext_ln83_1_fu_389_p1 = tmp_9_fu_381_p3;

assign zext_ln83_fu_366_p1 = tmp_s_fu_358_p3;

assign zext_ln91_fu_499_p1 = tmp_12_fu_492_p3;

assign zext_ln94_fu_512_p1 = tmp_13_fu_505_p3;

assign zext_ln99_fu_447_p1 = tmp_16_fu_440_p3;

endmodule //canny_top_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2
