-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity canny_top_sobel_Pipeline_VITIS_LOOP_118_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    result : IN STD_LOGIC_VECTOR (1 downto 0);
    writeSlot : IN STD_LOGIC_VECTOR (1 downto 0);
    result_1 : IN STD_LOGIC_VECTOR (1 downto 0);
    out_sobel_magnitude_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    out_sobel_magnitude_ce0 : OUT STD_LOGIC;
    out_sobel_magnitude_we0 : OUT STD_LOGIC;
    out_sobel_magnitude_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    out_sobel_direction_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    out_sobel_direction_ce0 : OUT STD_LOGIC;
    out_sobel_direction_we0 : OUT STD_LOGIC;
    out_sobel_direction_d0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_anonymous_namespace_lineBuffer_32_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_anonymous_namespace_lineBuffer_32_0_ce0 : OUT STD_LOGIC;
    p_anonymous_namespace_lineBuffer_32_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_anonymous_namespace_lineBuffer_32_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_anonymous_namespace_lineBuffer_32_0_ce1 : OUT STD_LOGIC;
    p_anonymous_namespace_lineBuffer_32_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_anonymous_namespace_lineBuffer_32_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_anonymous_namespace_lineBuffer_32_1_ce0 : OUT STD_LOGIC;
    p_anonymous_namespace_lineBuffer_32_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_anonymous_namespace_lineBuffer_32_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_anonymous_namespace_lineBuffer_32_1_ce1 : OUT STD_LOGIC;
    p_anonymous_namespace_lineBuffer_32_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of canny_top_sobel_Pipeline_VITIS_LOOP_118_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv20_3E8 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001111101000";
    constant ap_const_lv19_19E : STD_LOGIC_VECTOR (18 downto 0) := "0000000000110011110";
    constant ap_const_lv22_96E : STD_LOGIC_VECTOR (21 downto 0) := "0000000000100101101110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln118_reg_913 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal column_reg_905 : STD_LOGIC_VECTOR (8 downto 0);
    signal column_reg_905_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln118_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln118_fu_308_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln118_reg_917 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln118_reg_917_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal lshr_ln2_fu_352_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln2_reg_947 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln143_1_fu_380_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln143_1_reg_963 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal pixel_fu_420_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_reg_989 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_1_fu_450_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_1_reg_1004 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp3_fu_468_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp3_reg_1009 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln149_fu_540_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln149_reg_1034 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln145_fu_546_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln145_reg_1039 : STD_LOGIC_VECTOR (10 downto 0);
    signal gradientX_fu_593_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gradientX_reg_1044 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln149_fu_599_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln149_reg_1051 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln149_2_fu_613_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln149_2_reg_1057 : STD_LOGIC_VECTOR (9 downto 0);
    signal gradientY_fu_619_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gradientY_reg_1063 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln118_fu_625_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_1070 : STD_LOGIC_VECTOR (63 downto 0);
    signal absoluteX_fu_648_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal absoluteX_reg_1075 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln41_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_reg_1081 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln45_fu_706_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal mul_ln45_reg_1087 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln45_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_1093 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_i_i_fu_854_p11 : STD_LOGIC_VECTOR (1 downto 0);
    signal retval_0_i_i_reg_1099 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln143_fu_328_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln143_1_fu_341_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln143_2_fu_369_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln143_6_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln143_3_fu_414_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln143_7_fu_444_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln143_5_fu_480_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln143_8_fu_495_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal column_1_fu_86 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln140_1_fu_375_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_column : STD_LOGIC_VECTOR (8 downto 0);
    signal p_anonymous_namespace_lineBuffer_32_0_ce1_local : STD_LOGIC;
    signal p_anonymous_namespace_lineBuffer_32_0_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal p_anonymous_namespace_lineBuffer_32_0_ce0_local : STD_LOGIC;
    signal p_anonymous_namespace_lineBuffer_32_0_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal p_anonymous_namespace_lineBuffer_32_1_ce1_local : STD_LOGIC;
    signal p_anonymous_namespace_lineBuffer_32_1_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal p_anonymous_namespace_lineBuffer_32_1_ce0_local : STD_LOGIC;
    signal p_anonymous_namespace_lineBuffer_32_1_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal out_sobel_magnitude_we0_local : STD_LOGIC;
    signal add_ln156_fu_687_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal out_sobel_magnitude_ce0_local : STD_LOGIC;
    signal out_sobel_direction_we0_local : STD_LOGIC;
    signal out_sobel_direction_ce0_local : STD_LOGIC;
    signal grp_fu_280_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_287_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1_fu_312_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_321_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_334_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln140_fu_347_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_9_fu_362_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_fu_390_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_408_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln143_fu_427_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_438_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln143_5_fu_457_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln143_6_cast_fu_464_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln140_fu_434_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_fu_474_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_489_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_280_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_287_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln142_1_fu_501_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln142_fu_486_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln145_fu_512_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln25_fu_508_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln143_4_fu_504_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_522_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_6_fu_528_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln119_fu_536_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln145_cast1_fu_518_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_fu_560_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln142_2_fu_556_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln149_fu_571_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln142_4_fu_552_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal gradientX_2_fu_588_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln142_5_fu_580_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln149_fu_574_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln142_3_fu_584_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln149_1_fu_603_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln149_2_fu_609_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln149_fu_567_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln149_1_fu_629_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_635_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln31_fu_643_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln120_fu_632_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_655_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln31_1_fu_663_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal absoluteY_fu_668_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln156_2_fu_683_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln156_1_fu_679_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln41_fu_694_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln45_fu_706_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln45_fu_706_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln45_1_fu_718_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln45_1_fu_718_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln45_1_fu_718_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln45_1_fu_715_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln45_2_fu_724_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln49_fu_740_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln49_fu_740_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln49_fu_740_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln45_fu_737_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln49_fu_746_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln54_fu_756_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal and_ln55_fu_764_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal xor_ln45_fu_772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln41_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln45_fu_787_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln49_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln55_fu_760_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln45_fu_768_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_812_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_804_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_2_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln45_fu_777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln49_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_3_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_i_i_fu_854_p9 : STD_LOGIC_VECTOR (1 downto 0);
    signal retval_0_i_i_fu_854_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln45_1_fu_718_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln45_fu_706_p00 : STD_LOGIC_VECTOR (19 downto 0);
    signal mul_ln49_fu_740_p00 : STD_LOGIC_VECTOR (21 downto 0);
    signal retval_0_i_i_fu_854_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_0_i_i_fu_854_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_0_i_i_fu_854_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_0_i_i_fu_854_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component canny_top_mul_10ns_11ns_20_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component canny_top_mul_10ns_10ns_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component canny_top_mul_10ns_13ns_22_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component canny_top_sparsemux_9_3_2_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (1 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (1 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        def : IN STD_LOGIC_VECTOR (1 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component canny_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_10ns_11ns_20_1_1_U61 : component canny_top_mul_10ns_11ns_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 11,
        dout_WIDTH => 20)
    port map (
        din0 => mul_ln45_fu_706_p0,
        din1 => mul_ln45_fu_706_p1,
        dout => mul_ln45_fu_706_p2);

    mul_10ns_10ns_19_1_1_U62 : component canny_top_mul_10ns_10ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln45_1_fu_718_p0,
        din1 => mul_ln45_1_fu_718_p1,
        dout => mul_ln45_1_fu_718_p2);

    mul_10ns_13ns_22_1_1_U63 : component canny_top_mul_10ns_13ns_22_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 13,
        dout_WIDTH => 22)
    port map (
        din0 => mul_ln49_fu_740_p0,
        din1 => mul_ln49_fu_740_p1,
        dout => mul_ln49_fu_740_p2);

    sparsemux_9_3_2_1_1_U64 : component canny_top_sparsemux_9_3_2_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 2,
        CASE1 => "010",
        din1_WIDTH => 2,
        CASE2 => "001",
        din2_WIDTH => 2,
        CASE3 => "000",
        din3_WIDTH => 2,
        def_WIDTH => 2,
        sel_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        din0 => ap_const_lv2_0,
        din1 => ap_const_lv2_2,
        din2 => ap_const_lv2_3,
        din3 => ap_const_lv2_1,
        def => retval_0_i_i_fu_854_p9,
        sel => retval_0_i_i_fu_854_p10,
        dout => retval_0_i_i_fu_854_p11);

    flow_control_loop_pipe_sequential_init_U : component canny_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    column_1_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                column_1_fu_86 <= ap_const_lv9_1;
            elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                column_1_fu_86 <= add_ln140_1_fu_375_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                absoluteX_reg_1075 <= absoluteX_fu_648_p3;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln41_reg_1081 <= icmp_ln41_fu_700_p2;
                mul_ln45_reg_1087 <= mul_ln45_fu_706_p2;
                pixel_1_reg_1004 <= pixel_1_fu_450_p3;
                pixel_reg_989 <= pixel_fu_420_p3;
                tmp3_reg_1009 <= tmp3_fu_468_p2;
                    zext_ln118_reg_1070(8 downto 0) <= zext_ln118_fu_625_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln145_reg_1039 <= add_ln145_fu_546_p2;
                add_ln149_reg_1034 <= add_ln149_fu_540_p2;
                column_reg_905 <= ap_sig_allocacmp_column;
                column_reg_905_pp0_iter1_reg <= column_reg_905;
                icmp_ln118_reg_913 <= icmp_ln118_fu_302_p2;
                icmp_ln45_reg_1093 <= icmp_ln45_fu_728_p2;
                trunc_ln118_reg_917 <= trunc_ln118_fu_308_p1;
                trunc_ln118_reg_917_pp0_iter1_reg <= trunc_ln118_reg_917;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln149_2_reg_1057 <= add_ln149_2_fu_613_p2;
                gradientX_reg_1044 <= gradientX_fu_593_p2;
                gradientY_reg_1063 <= gradientY_fu_619_p2;
                lshr_ln143_1_reg_963 <= add_ln140_1_fu_375_p2(8 downto 1);
                lshr_ln2_reg_947 <= add_ln140_fu_347_p2(8 downto 1);
                retval_0_i_i_reg_1099 <= retval_0_i_i_fu_854_p11;
                trunc_ln149_reg_1051 <= trunc_ln149_fu_599_p1;
            end if;
        end if;
    end process;
    zext_ln118_reg_1070(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    absoluteX_fu_648_p3 <= 
        sub_ln31_fu_643_p2 when (tmp_10_fu_635_p3(0) = '1') else 
        trunc_ln149_reg_1051;
    absoluteY_fu_668_p3 <= 
        sub_ln31_1_fu_663_p2 when (tmp_11_fu_655_p3(0) = '1') else 
        add_ln149_2_reg_1057;
    add_ln140_1_fu_375_p2 <= std_logic_vector(unsigned(column_reg_905) + unsigned(ap_const_lv9_1));
    add_ln140_fu_347_p2 <= std_logic_vector(unsigned(column_reg_905) + unsigned(ap_const_lv9_1FF));
    add_ln145_fu_546_p2 <= std_logic_vector(signed(sext_ln119_fu_536_p1) + signed(sub_ln145_cast1_fu_518_p1));
    add_ln149_1_fu_603_p2 <= std_logic_vector(unsigned(sub_ln149_fu_574_p2) + unsigned(zext_ln142_3_fu_584_p1));
    add_ln149_2_fu_613_p2 <= std_logic_vector(signed(add_ln149_1_fu_603_p2) + signed(tmp_8_fu_560_p3));
    add_ln149_fu_540_p2 <= std_logic_vector(unsigned(zext_ln142_1_fu_501_p1) + unsigned(zext_ln142_fu_486_p1));
    add_ln156_fu_687_p2 <= std_logic_vector(unsigned(zext_ln156_2_fu_683_p1) + unsigned(zext_ln156_1_fu_679_p1));
    and_ln45_fu_787_p2 <= (xor_ln41_fu_782_p2 and icmp_ln45_reg_1093);
    and_ln49_fu_798_p2 <= (xor_ln49_fu_792_p2 and and_ln45_fu_787_p2);
    and_ln55_1_fu_826_p2 <= (icmp_ln49_fu_750_p2 and and_ln45_fu_787_p2);
    and_ln55_2_fu_832_p2 <= (xor_ln55_fu_820_p2 and tmp_12_fu_804_p3);
    and_ln55_3_fu_838_p2 <= (and_ln55_2_fu_832_p2 and and_ln55_1_fu_826_p2);
    and_ln55_fu_764_p2 <= (gradientY_reg_1063 and gradientX_reg_1044);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913)
    begin
        if (((icmp_ln118_reg_913 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_column_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, column_1_fu_86, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_column <= ap_const_lv9_1;
        else 
            ap_sig_allocacmp_column <= column_1_fu_86;
        end if; 
    end process;

    gradientX_2_fu_588_p2 <= std_logic_vector(unsigned(add_ln145_reg_1039) - unsigned(zext_ln142_4_fu_552_p1));
    gradientX_fu_593_p2 <= std_logic_vector(unsigned(gradientX_2_fu_588_p2) + unsigned(zext_ln142_5_fu_580_p1));
    gradientY_fu_619_p2 <= std_logic_vector(signed(sext_ln149_2_fu_609_p1) + signed(sext_ln149_fu_567_p1));

    grp_fu_280_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln118_reg_917, trunc_ln118_reg_917_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_280_p0 <= trunc_ln118_reg_917_pp0_iter1_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_280_p0 <= trunc_ln118_reg_917;
            else 
                grp_fu_280_p0 <= "X";
            end if;
        else 
            grp_fu_280_p0 <= "X";
        end if; 
    end process;

    grp_fu_280_p3 <= 
        p_anonymous_namespace_lineBuffer_32_0_q1 when (grp_fu_280_p0(0) = '1') else 
        p_anonymous_namespace_lineBuffer_32_1_q1;

    grp_fu_287_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln118_reg_917, trunc_ln118_reg_917_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_287_p0 <= trunc_ln118_reg_917_pp0_iter1_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_287_p0 <= trunc_ln118_reg_917;
            else 
                grp_fu_287_p0 <= "X";
            end if;
        else 
            grp_fu_287_p0 <= "X";
        end if; 
    end process;

    grp_fu_287_p3 <= 
        p_anonymous_namespace_lineBuffer_32_0_q0 when (grp_fu_287_p0(0) = '1') else 
        p_anonymous_namespace_lineBuffer_32_1_q0;
    icmp_ln118_fu_302_p2 <= "1" when (ap_sig_allocacmp_column = ap_const_lv9_1FF) else "0";
    icmp_ln41_fu_700_p2 <= "1" when (or_ln41_fu_694_p2 = ap_const_lv10_0) else "0";
    icmp_ln45_fu_728_p2 <= "1" when (unsigned(zext_ln45_1_fu_715_p1) > unsigned(zext_ln45_2_fu_724_p1)) else "0";
    icmp_ln49_fu_750_p2 <= "1" when (unsigned(zext_ln45_fu_737_p1) < unsigned(zext_ln49_fu_746_p1)) else "0";
    lshr_ln143_1_fu_380_p4 <= add_ln140_1_fu_375_p2(8 downto 1);
    lshr_ln1_fu_312_p4 <= column_reg_905(8 downto 1);
    lshr_ln2_fu_352_p4 <= add_ln140_fu_347_p2(8 downto 1);
    mul_ln45_1_fu_718_p0 <= mul_ln45_1_fu_718_p00(10 - 1 downto 0);
    mul_ln45_1_fu_718_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(absoluteX_reg_1075),19));
    mul_ln45_1_fu_718_p1 <= ap_const_lv19_19E(10 - 1 downto 0);
    mul_ln45_fu_706_p0 <= mul_ln45_fu_706_p00(10 - 1 downto 0);
    mul_ln45_fu_706_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(absoluteY_fu_668_p3),20));
    mul_ln45_fu_706_p1 <= ap_const_lv20_3E8(11 - 1 downto 0);
    mul_ln49_fu_740_p0 <= mul_ln49_fu_740_p00(10 - 1 downto 0);
    mul_ln49_fu_740_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(absoluteX_reg_1075),22));
    mul_ln49_fu_740_p1 <= ap_const_lv22_96E(13 - 1 downto 0);
    or_ln41_fu_694_p2 <= (absoluteY_fu_668_p3 or absoluteX_fu_648_p3);
    or_ln45_fu_777_p2 <= (xor_ln45_fu_772_p2 or icmp_ln41_reg_1081);
    or_ln54_fu_756_p2 <= (gradientY_reg_1063 or gradientX_reg_1044);
    out_sobel_direction_address0 <= zext_ln118_reg_1070(9 - 1 downto 0);
    out_sobel_direction_ce0 <= out_sobel_direction_ce0_local;

    out_sobel_direction_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            out_sobel_direction_ce0_local <= ap_const_logic_1;
        else 
            out_sobel_direction_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_sobel_direction_d0 <= retval_0_i_i_reg_1099;
    out_sobel_direction_we0 <= out_sobel_direction_we0_local;

    out_sobel_direction_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            out_sobel_direction_we0_local <= ap_const_logic_1;
        else 
            out_sobel_direction_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_sobel_magnitude_address0 <= zext_ln118_fu_625_p1(9 - 1 downto 0);
    out_sobel_magnitude_ce0 <= out_sobel_magnitude_ce0_local;

    out_sobel_magnitude_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            out_sobel_magnitude_ce0_local <= ap_const_logic_1;
        else 
            out_sobel_magnitude_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_sobel_magnitude_d0 <= add_ln156_fu_687_p2;
    out_sobel_magnitude_we0 <= out_sobel_magnitude_we0_local;

    out_sobel_magnitude_we0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            out_sobel_magnitude_we0_local <= ap_const_logic_1;
        else 
            out_sobel_magnitude_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_0_address0 <= p_anonymous_namespace_lineBuffer_32_0_address0_local;

    p_anonymous_namespace_lineBuffer_32_0_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln143_1_fu_341_p1, zext_ln143_6_fu_397_p1, ap_block_pp0_stage2, zext_ln143_7_fu_444_p1, ap_block_pp0_stage0, zext_ln143_8_fu_495_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_anonymous_namespace_lineBuffer_32_0_address0_local <= zext_ln143_8_fu_495_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_anonymous_namespace_lineBuffer_32_0_address0_local <= zext_ln143_7_fu_444_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0))) then 
            p_anonymous_namespace_lineBuffer_32_0_address0_local <= zext_ln143_1_fu_341_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1))) then 
            p_anonymous_namespace_lineBuffer_32_0_address0_local <= zext_ln143_6_fu_397_p1(10 - 1 downto 0);
        else 
            p_anonymous_namespace_lineBuffer_32_0_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_0_address1 <= p_anonymous_namespace_lineBuffer_32_0_address1_local;

    p_anonymous_namespace_lineBuffer_32_0_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, zext_ln143_fu_328_p1, ap_block_pp0_stage1, zext_ln143_2_fu_369_p1, zext_ln143_3_fu_414_p1, ap_block_pp0_stage2, zext_ln143_5_fu_480_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_anonymous_namespace_lineBuffer_32_0_address1_local <= zext_ln143_5_fu_480_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_anonymous_namespace_lineBuffer_32_0_address1_local <= zext_ln143_3_fu_414_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0))) then 
            p_anonymous_namespace_lineBuffer_32_0_address1_local <= zext_ln143_fu_328_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1))) then 
            p_anonymous_namespace_lineBuffer_32_0_address1_local <= zext_ln143_2_fu_369_p1(10 - 1 downto 0);
        else 
            p_anonymous_namespace_lineBuffer_32_0_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_0_ce0 <= p_anonymous_namespace_lineBuffer_32_0_ce0_local;

    p_anonymous_namespace_lineBuffer_32_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, ap_block_pp0_stage0_11001, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0)))) then 
            p_anonymous_namespace_lineBuffer_32_0_ce0_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_lineBuffer_32_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_0_ce1 <= p_anonymous_namespace_lineBuffer_32_0_ce1_local;

    p_anonymous_namespace_lineBuffer_32_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, ap_block_pp0_stage0_11001, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0)))) then 
            p_anonymous_namespace_lineBuffer_32_0_ce1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_lineBuffer_32_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_1_address0 <= p_anonymous_namespace_lineBuffer_32_1_address0_local;

    p_anonymous_namespace_lineBuffer_32_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln143_1_fu_341_p1, zext_ln143_6_fu_397_p1, ap_block_pp0_stage2, zext_ln143_7_fu_444_p1, ap_block_pp0_stage0, zext_ln143_8_fu_495_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_anonymous_namespace_lineBuffer_32_1_address0_local <= zext_ln143_8_fu_495_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_anonymous_namespace_lineBuffer_32_1_address0_local <= zext_ln143_7_fu_444_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1))) then 
            p_anonymous_namespace_lineBuffer_32_1_address0_local <= zext_ln143_1_fu_341_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0))) then 
            p_anonymous_namespace_lineBuffer_32_1_address0_local <= zext_ln143_6_fu_397_p1(10 - 1 downto 0);
        else 
            p_anonymous_namespace_lineBuffer_32_1_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_1_address1 <= p_anonymous_namespace_lineBuffer_32_1_address1_local;

    p_anonymous_namespace_lineBuffer_32_1_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, zext_ln143_fu_328_p1, ap_block_pp0_stage1, zext_ln143_2_fu_369_p1, zext_ln143_3_fu_414_p1, ap_block_pp0_stage2, zext_ln143_5_fu_480_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_anonymous_namespace_lineBuffer_32_1_address1_local <= zext_ln143_5_fu_480_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_anonymous_namespace_lineBuffer_32_1_address1_local <= zext_ln143_3_fu_414_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1))) then 
            p_anonymous_namespace_lineBuffer_32_1_address1_local <= zext_ln143_fu_328_p1(10 - 1 downto 0);
        elsif (((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0))) then 
            p_anonymous_namespace_lineBuffer_32_1_address1_local <= zext_ln143_2_fu_369_p1(10 - 1 downto 0);
        else 
            p_anonymous_namespace_lineBuffer_32_1_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_1_ce0 <= p_anonymous_namespace_lineBuffer_32_1_ce0_local;

    p_anonymous_namespace_lineBuffer_32_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, ap_block_pp0_stage0_11001, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0)))) then 
            p_anonymous_namespace_lineBuffer_32_1_ce0_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_lineBuffer_32_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_lineBuffer_32_1_ce1 <= p_anonymous_namespace_lineBuffer_32_1_ce1_local;

    p_anonymous_namespace_lineBuffer_32_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, icmp_ln118_reg_913, ap_block_pp0_stage0_11001, trunc_ln118_reg_917, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_1)) or ((icmp_ln118_reg_913 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (trunc_ln118_reg_917 = ap_const_lv1_0)))) then 
            p_anonymous_namespace_lineBuffer_32_1_ce1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_lineBuffer_32_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pixel_1_fu_450_p3 <= 
        p_anonymous_namespace_lineBuffer_32_0_q0 when (trunc_ln118_reg_917(0) = '1') else 
        p_anonymous_namespace_lineBuffer_32_1_q0;
    pixel_fu_420_p3 <= 
        p_anonymous_namespace_lineBuffer_32_0_q1 when (trunc_ln118_reg_917(0) = '1') else 
        p_anonymous_namespace_lineBuffer_32_1_q1;
    retval_0_i_i_fu_854_p10 <= ((or_ln45_fu_777_p2 & and_ln49_fu_798_p2) & and_ln55_3_fu_838_p2);
    retval_0_i_i_fu_854_p9 <= "XX";
    select_ln143_5_fu_457_p3 <= 
        p_anonymous_namespace_lineBuffer_32_1_q0 when (trunc_ln118_reg_917(0) = '1') else 
        p_anonymous_namespace_lineBuffer_32_0_q0;
    select_ln143_6_cast_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln143_5_fu_457_p3),9));
    select_ln143_fu_427_p3 <= 
        p_anonymous_namespace_lineBuffer_32_1_q1 when (trunc_ln118_reg_917(0) = '1') else 
        p_anonymous_namespace_lineBuffer_32_0_q1;
        sext_ln119_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_528_p3),11));

        sext_ln120_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gradientY_reg_1063),32));

        sext_ln149_1_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gradientX_reg_1044),32));

        sext_ln149_2_fu_609_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln149_1_fu_603_p2),11));

        sext_ln149_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_560_p3),11));

        sext_ln45_fu_768_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln55_fu_764_p2),32));

        sext_ln55_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln54_fu_756_p2),32));

        sub_ln145_cast1_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln145_fu_512_p2),11));

    sub_ln145_fu_512_p2 <= std_logic_vector(unsigned(zext_ln142_1_fu_501_p1) - unsigned(zext_ln142_fu_486_p1));
    sub_ln149_fu_574_p2 <= std_logic_vector(unsigned(zext_ln142_2_fu_556_p1) - unsigned(zext_ln149_fu_571_p1));
    sub_ln31_1_fu_663_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(add_ln149_2_reg_1057));
    sub_ln31_fu_643_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(trunc_ln149_reg_1051));
    tmp3_fu_468_p2 <= std_logic_vector(unsigned(select_ln143_6_cast_fu_464_p1) - unsigned(zext_ln140_fu_434_p1));
    tmp_10_fu_635_p3 <= sext_ln149_1_fu_629_p1(31 downto 31);
    tmp_11_fu_655_p3 <= sext_ln120_fu_632_p1(31 downto 31);
    tmp_12_fu_804_p3 <= sext_ln55_fu_760_p1(31 downto 31);
    tmp_13_fu_812_p3 <= sext_ln45_fu_768_p1(31 downto 31);
    tmp_1_fu_474_p3 <= (writeSlot & lshr_ln2_reg_947);
    tmp_2_fu_390_p3 <= (result & lshr_ln143_1_fu_380_p4);
    tmp_3_fu_438_p3 <= (result_1 & lshr_ln143_1_reg_963);
    tmp_4_fu_489_p3 <= (writeSlot & lshr_ln143_1_reg_963);
    tmp_5_fu_321_p3 <= (result & lshr_ln1_fu_312_p4);
    tmp_6_fu_528_p3 <= (tmp_fu_522_p2 & ap_const_lv1_0);
    tmp_7_fu_334_p3 <= (writeSlot & lshr_ln1_fu_312_p4);
    tmp_8_fu_560_p3 <= (tmp3_reg_1009 & ap_const_lv1_0);
    tmp_9_fu_362_p3 <= (result & lshr_ln2_fu_352_p4);
    tmp_fu_522_p2 <= std_logic_vector(unsigned(zext_ln25_fu_508_p1) - unsigned(zext_ln143_4_fu_504_p1));
    tmp_s_fu_408_p3 <= (result_1 & lshr_ln2_reg_947);
    trunc_ln118_fu_308_p1 <= ap_sig_allocacmp_column(1 - 1 downto 0);
    trunc_ln149_fu_599_p1 <= gradientX_fu_593_p2(10 - 1 downto 0);
    xor_ln41_fu_782_p2 <= (icmp_ln41_reg_1081 xor ap_const_lv1_1);
    xor_ln45_fu_772_p2 <= (icmp_ln45_reg_1093 xor ap_const_lv1_1);
    xor_ln49_fu_792_p2 <= (icmp_ln49_fu_750_p2 xor ap_const_lv1_1);
    xor_ln55_fu_820_p2 <= (tmp_13_fu_812_p3 xor ap_const_lv1_1);
    zext_ln118_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(column_reg_905_pp0_iter1_reg),64));
    zext_ln140_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln143_fu_427_p3),9));
    zext_ln142_1_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pixel_1_reg_1004),9));
    zext_ln142_2_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_280_p3),10));
    zext_ln142_3_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_287_p3),10));
    zext_ln142_4_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_280_p3),11));
    zext_ln142_5_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_287_p3),11));
    zext_ln142_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pixel_reg_989),9));
    zext_ln143_1_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_334_p3),64));
    zext_ln143_2_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_362_p3),64));
    zext_ln143_3_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_408_p3),64));
    zext_ln143_4_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_280_p3),9));
    zext_ln143_5_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_474_p3),64));
    zext_ln143_6_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_390_p3),64));
    zext_ln143_7_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_438_p3),64));
    zext_ln143_8_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_489_p3),64));
    zext_ln143_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_321_p3),64));
    zext_ln149_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln149_reg_1034),10));
    zext_ln156_1_fu_679_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(absoluteY_fu_668_p3),11));
    zext_ln156_2_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(absoluteX_fu_648_p3),11));
    zext_ln25_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_287_p3),9));
    zext_ln45_1_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln45_reg_1087),21));
    zext_ln45_2_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln45_1_fu_718_p2),21));
    zext_ln45_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln45_reg_1087),23));
    zext_ln49_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln49_fu_740_p2),23));
end behav;
