-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity canny_top_hysteresis_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    hyst2_out_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    hyst2_out_empty_n : IN STD_LOGIC;
    hyst2_out_read : OUT STD_LOGIC;
    hyst2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    hyst2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    hyst3_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    hyst3_out_full_n : IN STD_LOGIC;
    hyst3_out_write : OUT STD_LOGIC;
    hyst3_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    hyst3_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of canny_top_hysteresis_3_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv10_201 : STD_LOGIC_VECTOR (9 downto 0) := "1000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_3FE : STD_LOGIC_VECTOR (9 downto 0) := "1111111110";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal rowsReceived_fu_224_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal rowsReceived_reg_530 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_29_fu_230_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_535 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln80_fu_238_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln80_reg_539 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_248_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_reg_544 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal hasTop_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasTop_reg_548 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasBottom_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasBottom_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal buffer_load_reg_563 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal buffer_1_load_reg_570 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_2_load_reg_577 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_load_2_reg_584 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_1_load_1_reg_591 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_2_load_1_reg_598 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln12_fu_297_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln12_reg_605 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal trunc_ln10_fu_306_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln10_reg_610 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_311_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_615 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_329_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_reg_620 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_347_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_reg_625 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_365_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_reg_630 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_383_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_reg_635 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_401_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_reg_640 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_ce0 : STD_LOGIC;
    signal buffer_we0 : STD_LOGIC;
    signal buffer_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_1_ce0 : STD_LOGIC;
    signal buffer_1_we0 : STD_LOGIC;
    signal buffer_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_1_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_2_ce0 : STD_LOGIC;
    signal buffer_2_we0 : STD_LOGIC;
    signal buffer_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_2_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal buffer_2_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_idle : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_ready : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_hyst2_out_read : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_idle : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_ready : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_hyst3_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_hyst3_out_write : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0 : STD_LOGIC;
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln74_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal phi_urem69_fu_66 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln72_fu_431_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state17_on_subcall_done : BOOLEAN;
    signal phi_urem_fu_70 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal select_ln72_2_fu_451_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal row_4_fu_74 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal buffer_ce1_local : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal buffer_ce0_local : STD_LOGIC;
    signal buffer_1_ce1_local : STD_LOGIC;
    signal buffer_1_ce0_local : STD_LOGIC;
    signal buffer_2_ce1_local : STD_LOGIC;
    signal buffer_2_ce0_local : STD_LOGIC;
    signal outputRow_fu_243_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_273_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_273_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_273_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln11_fu_279_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_283_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln12_fu_291_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_311_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_329_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_347_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_365_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_383_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_401_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln72_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln72_fu_419_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln72_2_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln72_2_fu_439_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_273_ap_start : STD_LOGIC;
    signal grp_fu_273_ap_done : STD_LOGIC;
    signal grp_fu_273_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal tmp_fu_311_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_311_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_311_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_329_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_329_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_329_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_347_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_347_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_fu_347_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_365_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_365_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_365_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_383_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_383_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_383_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_401_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_401_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_401_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component canny_top_hysteresis_3_Pipeline_VITIS_LOOP_78_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hyst2_out_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        hyst2_out_empty_n : IN STD_LOGIC;
        hyst2_out_read : OUT STD_LOGIC;
        hyst2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        hyst2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        buffer_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_2_ce0 : OUT STD_LOGIC;
        buffer_2_we0 : OUT STD_LOGIC;
        buffer_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buffer_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_1_ce0 : OUT STD_LOGIC;
        buffer_1_we0 : OUT STD_LOGIC;
        buffer_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buffer_r_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_r_ce0 : OUT STD_LOGIC;
        buffer_r_we0 : OUT STD_LOGIC;
        buffer_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component canny_top_hysteresis_3_Pipeline_VITIS_LOOP_143_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hyst3_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        hyst3_out_full_n : IN STD_LOGIC;
        hyst3_out_write : OUT STD_LOGIC;
        hyst3_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        hyst3_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_22 : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp_19 : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp_21 : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp_s : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp_20 : IN STD_LOGIC_VECTOR (7 downto 0);
        tmp : IN STD_LOGIC_VECTOR (7 downto 0);
        hasBottom : IN STD_LOGIC_VECTOR (0 downto 0);
        hasTop : IN STD_LOGIC_VECTOR (0 downto 0);
        buffer_r_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_r_ce0 : OUT STD_LOGIC;
        buffer_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buffer_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_1_ce0 : OUT STD_LOGIC;
        buffer_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        buffer_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        buffer_2_ce0 : OUT STD_LOGIC;
        buffer_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln12 : IN STD_LOGIC_VECTOR (1 downto 0);
        empty : IN STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component canny_top_srem_10ns_3ns_10_14_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component canny_top_sparsemux_7_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    buffer_U : component canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buffer_address0,
        ce0 => buffer_ce0,
        we0 => buffer_we0,
        d0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_d0,
        q0 => buffer_q0,
        address1 => buffer_address1,
        ce1 => buffer_ce1_local,
        q1 => buffer_q1);

    buffer_1_U : component canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buffer_1_address0,
        ce0 => buffer_1_ce0,
        we0 => buffer_1_we0,
        d0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_d0,
        q0 => buffer_1_q0,
        address1 => buffer_1_address1,
        ce1 => buffer_1_ce1_local,
        q1 => buffer_1_q1);

    buffer_2_U : component canny_top_gaussian_blur_row_in_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buffer_2_address0,
        ce0 => buffer_2_ce0,
        we0 => buffer_2_we0,
        d0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_d0,
        q0 => buffer_2_q0,
        address1 => buffer_2_address1,
        ce1 => buffer_2_ce1_local,
        q1 => buffer_2_q1);

    grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165 : component canny_top_hysteresis_3_Pipeline_VITIS_LOOP_78_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start,
        ap_done => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done,
        ap_idle => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_idle,
        ap_ready => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_ready,
        hyst2_out_dout => hyst2_out_dout,
        hyst2_out_empty_n => hyst2_out_empty_n,
        hyst2_out_read => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_hyst2_out_read,
        hyst2_out_num_data_valid => ap_const_lv11_0,
        hyst2_out_fifo_cap => ap_const_lv11_0,
        buffer_2_address0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0,
        buffer_2_ce0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0,
        buffer_2_we0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0,
        buffer_2_d0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_d0,
        buffer_1_address0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0,
        buffer_1_ce0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0,
        buffer_1_we0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0,
        buffer_1_d0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_d0,
        buffer_r_address0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0,
        buffer_r_ce0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0,
        buffer_r_we0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0,
        buffer_r_d0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_d0,
        empty => trunc_ln80_reg_539);

    grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175 : component canny_top_hysteresis_3_Pipeline_VITIS_LOOP_143_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start,
        ap_done => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done,
        ap_idle => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_idle,
        ap_ready => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_ready,
        hyst3_out_din => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_hyst3_out_din,
        hyst3_out_full_n => hyst3_out_full_n,
        hyst3_out_write => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_hyst3_out_write,
        hyst3_out_num_data_valid => hyst3_out_num_data_valid,
        hyst3_out_fifo_cap => hyst3_out_fifo_cap,
        tmp_22 => tmp_22_reg_640,
        tmp_19 => tmp_19_reg_625,
        tmp_21 => tmp_21_reg_635,
        tmp_s => tmp_s_reg_620,
        tmp_20 => tmp_20_reg_630,
        tmp => tmp_reg_615,
        hasBottom => hasBottom_reg_553,
        hasTop => hasTop_reg_548,
        buffer_r_address0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0,
        buffer_r_ce0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0,
        buffer_r_q0 => buffer_q0,
        buffer_1_address0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0,
        buffer_1_ce0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0,
        buffer_1_q0 => buffer_1_q0,
        buffer_2_address0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0,
        buffer_2_ce0 => grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0,
        buffer_2_q0 => buffer_2_q0,
        select_ln12 => select_ln12_reg_605,
        empty => trunc_ln10_reg_610);

    srem_10ns_3ns_10_14_seq_1_U306 : component canny_top_srem_10ns_3ns_10_14_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 14,
        din0_WIDTH => 10,
        din1_WIDTH => 3,
        dout_WIDTH => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_273_ap_start,
        done => grp_fu_273_ap_done,
        din0 => grp_fu_273_p0,
        din1 => grp_fu_273_p1,
        ce => grp_fu_273_ce,
        dout => grp_fu_273_p2);

    sparsemux_7_2_8_1_1_U307 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buffer_load_reg_563,
        din1 => buffer_1_load_reg_570,
        din2 => buffer_2_load_reg_577,
        def => tmp_fu_311_p7,
        sel => select_ln12_fu_297_p3,
        dout => tmp_fu_311_p9);

    sparsemux_7_2_8_1_1_U308 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 8,
        CASE1 => "10",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buffer_load_reg_563,
        din1 => buffer_1_load_reg_570,
        din2 => buffer_2_load_reg_577,
        def => tmp_s_fu_329_p7,
        sel => trunc_ln10_fu_306_p1,
        dout => tmp_s_fu_329_p9);

    sparsemux_7_2_8_1_1_U309 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buffer_load_reg_563,
        din1 => buffer_1_load_reg_570,
        din2 => buffer_2_load_reg_577,
        def => tmp_19_fu_347_p7,
        sel => trunc_ln10_fu_306_p1,
        dout => tmp_19_fu_347_p9);

    sparsemux_7_2_8_1_1_U310 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buffer_load_2_reg_584,
        din1 => buffer_1_load_1_reg_591,
        din2 => buffer_2_load_1_reg_598,
        def => tmp_20_fu_365_p7,
        sel => select_ln12_fu_297_p3,
        dout => tmp_20_fu_365_p9);

    sparsemux_7_2_8_1_1_U311 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 8,
        CASE1 => "10",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buffer_load_2_reg_584,
        din1 => buffer_1_load_1_reg_591,
        din2 => buffer_2_load_1_reg_598,
        def => tmp_21_fu_383_p7,
        sel => trunc_ln10_fu_306_p1,
        dout => tmp_21_fu_383_p9);

    sparsemux_7_2_8_1_1_U312 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buffer_load_2_reg_584,
        din1 => buffer_1_load_1_reg_591,
        din2 => buffer_2_load_1_reg_598,
        def => tmp_22_fu_401_p7,
        sel => trunc_ln10_fu_306_p1,
        dout => tmp_22_fu_401_p9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln74_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_ready = ap_const_logic_1)) then 
                    grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg <= ap_const_logic_0;
            else
                if (((tmp_29_fu_230_p3 = ap_const_lv1_0) and (icmp_ln74_fu_218_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_ready = ap_const_logic_1)) then 
                    grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    phi_urem69_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_urem69_fu_66 <= ap_const_lv10_0;
            elsif (((ap_const_boolean_0 = ap_block_state17_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                phi_urem69_fu_66 <= select_ln72_fu_431_p3;
            end if; 
        end if;
    end process;

    phi_urem_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_urem_fu_70 <= ap_const_lv10_0;
            elsif (((ap_const_boolean_0 = ap_block_state17_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                phi_urem_fu_70 <= select_ln72_2_fu_451_p3;
            end if; 
        end if;
    end process;

    row_4_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                row_4_fu_74 <= ap_const_lv10_0;
            elsif (((ap_const_boolean_0 = ap_block_state17_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                row_4_fu_74 <= rowsReceived_reg_530;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                buffer_1_load_1_reg_591 <= buffer_1_q0;
                buffer_1_load_reg_570 <= buffer_1_q1;
                buffer_2_load_1_reg_598 <= buffer_2_q0;
                buffer_2_load_reg_577 <= buffer_2_q1;
                buffer_load_2_reg_584 <= buffer_q0;
                buffer_load_reg_563 <= buffer_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hasBottom_reg_553 <= hasBottom_fu_262_p2;
                hasTop_reg_548 <= hasTop_fu_256_p2;
                tmp_30_reg_544 <= outputRow_fu_243_p2(9 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                rowsReceived_reg_530 <= rowsReceived_fu_224_p2;
                tmp_29_reg_535 <= row_4_fu_74(9 downto 9);
                trunc_ln80_reg_539 <= trunc_ln80_fu_238_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                select_ln12_reg_605 <= select_ln12_fu_297_p3;
                tmp_19_reg_625 <= tmp_19_fu_347_p9;
                tmp_20_reg_630 <= tmp_20_fu_365_p9;
                tmp_21_reg_635 <= tmp_21_fu_383_p9;
                tmp_22_reg_640 <= tmp_22_fu_401_p9;
                tmp_reg_615 <= tmp_fu_311_p9;
                tmp_s_reg_620 <= tmp_s_fu_329_p9;
                trunc_ln10_reg_610 <= trunc_ln10_fu_306_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, tmp_30_fu_248_p3, ap_CS_fsm_state3, ap_block_state3_on_subcall_done, icmp_ln74_fu_218_p2, ap_CS_fsm_state17, ap_block_state17_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln74_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((tmp_30_fu_248_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                elsif (((tmp_30_fu_248_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((ap_const_boolean_0 = ap_block_state17_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln12_fu_291_p2 <= std_logic_vector(unsigned(trunc_ln11_fu_279_p1) + unsigned(ap_const_lv2_3));
    add_ln72_2_fu_439_p2 <= std_logic_vector(unsigned(phi_urem_fu_70) + unsigned(ap_const_lv10_1));
    add_ln72_fu_419_p2 <= std_logic_vector(unsigned(phi_urem69_fu_66) + unsigned(ap_const_lv10_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state17_blk_assign_proc : process(ap_block_state17_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state17_on_subcall_done)) then 
            ap_ST_fsm_state17_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state17_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state17_on_subcall_done_assign_proc : process(tmp_30_reg_544, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done)
    begin
                ap_block_state17_on_subcall_done <= ((tmp_30_reg_544 = ap_const_lv1_0) and (grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_done = ap_const_logic_0));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(tmp_29_reg_535, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((tmp_29_reg_535 = ap_const_lv1_0) and (grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln74_fu_218_p2)
    begin
        if (((icmp_ln74_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    buffer_1_address0_assign_proc : process(tmp_29_reg_535, tmp_30_reg_544, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0, ap_CS_fsm_state17)
    begin
        if (((tmp_30_reg_544 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buffer_1_address0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_address0;
        elsif (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_1_address0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_address0;
        else 
            buffer_1_address0 <= ap_const_lv64_1(9 - 1 downto 0);
        end if; 
    end process;

    buffer_1_address1 <= ap_const_lv64_0(9 - 1 downto 0);

    buffer_1_ce0_assign_proc : process(tmp_29_reg_535, tmp_30_reg_544, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0, ap_CS_fsm_state17, buffer_1_ce0_local)
    begin
        if (((tmp_30_reg_544 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buffer_1_ce0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_1_ce0;
        elsif (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_1_ce0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_ce0;
        else 
            buffer_1_ce0 <= buffer_1_ce0_local;
        end if; 
    end process;


    buffer_1_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_1_ce0_local <= ap_const_logic_1;
        else 
            buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_1_ce1_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_1_ce1_local <= ap_const_logic_1;
        else 
            buffer_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_1_we0_assign_proc : process(tmp_29_reg_535, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0)
    begin
        if (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_1_we0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_1_we0;
        else 
            buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buffer_2_address0_assign_proc : process(tmp_29_reg_535, tmp_30_reg_544, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0, ap_CS_fsm_state17)
    begin
        if (((tmp_30_reg_544 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buffer_2_address0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_address0;
        elsif (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_2_address0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_address0;
        else 
            buffer_2_address0 <= ap_const_lv64_1(9 - 1 downto 0);
        end if; 
    end process;

    buffer_2_address1 <= ap_const_lv64_0(9 - 1 downto 0);

    buffer_2_ce0_assign_proc : process(tmp_29_reg_535, tmp_30_reg_544, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0, ap_CS_fsm_state17, buffer_2_ce0_local)
    begin
        if (((tmp_30_reg_544 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buffer_2_ce0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_2_ce0;
        elsif (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_2_ce0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_ce0;
        else 
            buffer_2_ce0 <= buffer_2_ce0_local;
        end if; 
    end process;


    buffer_2_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_2_ce0_local <= ap_const_logic_1;
        else 
            buffer_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_2_ce1_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_2_ce1_local <= ap_const_logic_1;
        else 
            buffer_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_2_we0_assign_proc : process(tmp_29_reg_535, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0)
    begin
        if (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_2_we0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_2_we0;
        else 
            buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buffer_address0_assign_proc : process(tmp_29_reg_535, tmp_30_reg_544, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0, ap_CS_fsm_state17)
    begin
        if (((tmp_30_reg_544 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buffer_address0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_address0;
        elsif (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_address0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_address0;
        else 
            buffer_address0 <= ap_const_lv64_1(9 - 1 downto 0);
        end if; 
    end process;

    buffer_address1 <= ap_const_lv64_0(9 - 1 downto 0);

    buffer_ce0_assign_proc : process(tmp_29_reg_535, tmp_30_reg_544, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0, grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0, ap_CS_fsm_state17, buffer_ce0_local)
    begin
        if (((tmp_30_reg_544 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            buffer_ce0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_buffer_r_ce0;
        elsif (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_ce0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_ce0;
        else 
            buffer_ce0 <= buffer_ce0_local;
        end if; 
    end process;


    buffer_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_ce0_local <= ap_const_logic_1;
        else 
            buffer_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_ce1_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_ce1_local <= ap_const_logic_1;
        else 
            buffer_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    buffer_we0_assign_proc : process(tmp_29_reg_535, ap_CS_fsm_state3, grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0)
    begin
        if (((tmp_29_reg_535 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            buffer_we0 <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_buffer_r_we0;
        else 
            buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_273_ap_start_assign_proc : process(tmp_30_fu_248_p3, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((tmp_30_fu_248_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            grp_fu_273_ap_start <= ap_const_logic_1;
        else 
            grp_fu_273_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_273_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            grp_fu_273_ce <= ap_const_logic_0;
        else 
            grp_fu_273_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_273_p0 <= std_logic_vector(unsigned(row_4_fu_74) + unsigned(ap_const_lv10_3FE));
    grp_fu_273_p1 <= ap_const_lv10_3(3 - 1 downto 0);
    grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_ap_start_reg;
    grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_ap_start_reg;
    hasBottom_fu_262_p2 <= "0" when (outputRow_fu_243_p2 = ap_const_lv10_1FF) else "1";
    hasTop_fu_256_p2 <= "1" when (signed(outputRow_fu_243_p2) > signed(ap_const_lv10_0)) else "0";
    hyst2_out_read <= grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165_hyst2_out_read;
    hyst3_out_din <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_hyst3_out_din;
    hyst3_out_write <= grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175_hyst3_out_write;
    icmp_ln72_2_fu_445_p2 <= "1" when (phi_urem_fu_70 = ap_const_lv10_2) else "0";
    icmp_ln72_fu_425_p2 <= "1" when (phi_urem69_fu_66 = ap_const_lv10_2) else "0";
    icmp_ln74_fu_218_p2 <= "1" when (row_4_fu_74 = ap_const_lv10_201) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln74_fu_218_p2)
    begin
        if (((icmp_ln74_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    outputRow_fu_243_p2 <= std_logic_vector(unsigned(row_4_fu_74) + unsigned(ap_const_lv10_3FF));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rowsReceived_fu_224_p2 <= std_logic_vector(unsigned(row_4_fu_74) + unsigned(ap_const_lv10_1));
    select_ln12_fu_297_p3 <= 
        add_ln12_fu_291_p2 when (tmp_31_fu_283_p3(0) = '1') else 
        trunc_ln11_fu_279_p1;
    select_ln72_2_fu_451_p3 <= 
        ap_const_lv10_0 when (icmp_ln72_2_fu_445_p2(0) = '1') else 
        add_ln72_2_fu_439_p2;
    select_ln72_fu_431_p3 <= 
        ap_const_lv10_0 when (icmp_ln72_fu_425_p2(0) = '1') else 
        add_ln72_fu_419_p2;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_19_fu_347_p7 <= "XXXXXXXX";
    tmp_20_fu_365_p7 <= "XXXXXXXX";
    tmp_21_fu_383_p7 <= "XXXXXXXX";
    tmp_22_fu_401_p7 <= "XXXXXXXX";
    tmp_29_fu_230_p3 <= row_4_fu_74(9 downto 9);
    tmp_30_fu_248_p3 <= outputRow_fu_243_p2(9 downto 9);
    tmp_31_fu_283_p3 <= grp_fu_273_p2(2 downto 2);
    tmp_fu_311_p7 <= "XXXXXXXX";
    tmp_s_fu_329_p7 <= "XXXXXXXX";
    trunc_ln10_fu_306_p1 <= phi_urem69_fu_66(2 - 1 downto 0);
    trunc_ln11_fu_279_p1 <= grp_fu_273_p2(2 - 1 downto 0);
    trunc_ln80_fu_238_p1 <= phi_urem_fu_70(2 - 1 downto 0);
end behav;
