-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity canny_top_double_threshold is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    out_nonmax_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    out_nonmax_ce0 : OUT STD_LOGIC;
    out_nonmax_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    out_double_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    out_double_ce0 : OUT STD_LOGIC;
    out_double_we0 : OUT STD_LOGIC;
    out_double_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of canny_top_double_threshold is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_read_9_read_fu_14_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read_9_reg_40 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_done : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_idle : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_ready : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_nonmax_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_nonmax_ce0 : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_ce0 : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_we0 : STD_LOGIC;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_valid_out_write_assign_phi_fu_24_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_out_write_assign_reg_20 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call0 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component canny_top_double_threshold_Pipeline_VITIS_LOOP_16_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_nonmax_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        out_nonmax_ce0 : OUT STD_LOGIC;
        out_nonmax_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
        out_double_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        out_double_ce0 : OUT STD_LOGIC;
        out_double_we0 : OUT STD_LOGIC;
        out_double_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32 : component canny_top_double_threshold_Pipeline_VITIS_LOOP_16_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start,
        ap_done => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_done,
        ap_idle => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_idle,
        ap_ready => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_ready,
        out_nonmax_address0 => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_nonmax_address0,
        out_nonmax_ce0 => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_nonmax_ce0,
        out_nonmax_q0 => out_nonmax_q0,
        out_double_address0 => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_address0,
        out_double_ce0 => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_ce0,
        out_double_we0 => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_we0,
        out_double_d0 => grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call0) and (p_read_9_read_fu_14_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_ready = ap_const_logic_1)) then 
                    grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    valid_out_write_assign_reg_20_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (p_read_9_reg_40 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                valid_out_write_assign_reg_20 <= ap_const_lv1_1;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (p_read_9_read_fu_14_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                valid_out_write_assign_reg_20 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_read_9_reg_40 <= p_read;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call0_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(p_read_9_reg_40, grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_done = ap_const_logic_0) and (p_read_9_reg_40 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_valid_out_write_assign_phi_fu_24_p4_assign_proc : process(p_read_9_reg_40, valid_out_write_assign_reg_20, ap_CS_fsm_state2)
    begin
        if (((p_read_9_reg_40 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_phi_mux_valid_out_write_assign_phi_fu_24_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_valid_out_write_assign_phi_fu_24_p4 <= valid_out_write_assign_reg_20;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_valid_out_write_assign_phi_fu_24_p4;
    grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_ap_start_reg;
    out_double_address0 <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_address0;
    out_double_ce0 <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_ce0;
    out_double_d0 <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_d0;
    out_double_we0 <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_double_we0;
    out_nonmax_address0 <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_nonmax_address0;
    out_nonmax_ce0 <= grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32_out_nonmax_ce0;
    p_read_9_read_fu_14_p2 <= p_read;
end behav;
