-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity canny_top_hysteresis_2_Pipeline_VITIS_LOOP_154_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_28 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_25 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_27 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_s : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_26 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp : IN STD_LOGIC_VECTOR (7 downto 0);
    outputRow : IN STD_LOGIC_VECTOR (30 downto 0);
    select_ln18 : IN STD_LOGIC_VECTOR (1 downto 0);
    p_smodpost : IN STD_LOGIC_VECTOR (1 downto 0);
    select_ln18_3 : IN STD_LOGIC_VECTOR (1 downto 0);
    out_hysteresis2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    out_hysteresis2_ce0 : OUT STD_LOGIC;
    out_hysteresis2_we0 : OUT STD_LOGIC;
    out_hysteresis2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0 : OUT STD_LOGIC;
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0 : OUT STD_LOGIC;
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0 : OUT STD_LOGIC;
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of canny_top_hysteresis_2_Pipeline_VITIS_LOOP_154_4 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv31_1FF : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000111111111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln154_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal hasBottom_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasBottom_reg_748 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasTop_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasTop_reg_754 : STD_LOGIC_VECTOR (0 downto 0);
    signal column_reg_759 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln154_reg_766 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln191_fu_385_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln154_fu_416_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal centre_3_load_fu_397_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln43_3_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_6_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln48_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln48_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln50_3_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_hysteresis2_addr_2_gep_fu_243_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_hysteresis2_addr_1_gep_fu_252_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_hysteresis2_addr_gep_fu_260_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal column_5_fu_90 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln154_fu_345_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_column : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_94 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_62_fu_98 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_63_fu_102 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal centre_fu_106 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_64_fu_110 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_65_fu_114 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_29_fu_561_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_66_fu_118 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_30_fu_580_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_67_fu_122 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_68_fu_126 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_31_fu_599_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0_local : STD_LOGIC;
    signal p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0_local : STD_LOGIC;
    signal p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0_local : STD_LOGIC;
    signal out_hysteresis2_we0_local : STD_LOGIC;
    signal out_hysteresis2_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal out_hysteresis2_ce0_local : STD_LOGIC;
    signal out_hysteresis2_address0_local : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln184_fu_351_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln184_fu_355_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln184_fu_359_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_37_fu_369_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln21_fu_365_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal nextColumn_fu_377_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal hasLeft_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hasRight_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_5_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_6_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_5_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln50_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_561_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_580_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_fu_599_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_161 : BOOLEAN;
    signal ap_condition_194 : BOOLEAN;
    signal ap_condition_205 : BOOLEAN;
    signal ap_condition_114 : BOOLEAN;
    signal tmp_29_fu_561_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_29_fu_561_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_29_fu_561_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_580_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_580_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_580_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_599_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_599_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_599_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component canny_top_sparsemux_7_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component canny_top_sparsemux_7_2_8_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component canny_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_7_2_8_1_1_U249 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_q0,
        din1 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_q0,
        din2 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_q0,
        def => tmp_29_fu_561_p7,
        sel => select_ln18,
        dout => tmp_29_fu_561_p9);

    sparsemux_7_2_8_1_1_x_U250 : component canny_top_sparsemux_7_2_8_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "01",
        din0_WIDTH => 8,
        CASE1 => "10",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_q0,
        din1 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_q0,
        din2 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_q0,
        def => tmp_30_fu_580_p7,
        sel => p_smodpost,
        dout => tmp_30_fu_580_p9);

    sparsemux_7_2_8_1_1_U251 : component canny_top_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_q0,
        din1 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_q0,
        din2 => p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_q0,
        def => tmp_31_fu_599_p7,
        sel => select_ln18_3,
        dout => tmp_31_fu_599_p9);

    flow_control_loop_pipe_sequential_init_U : component canny_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    centre_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    centre_fu_106 <= tmp_s;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    centre_fu_106 <= empty_66_fu_118;
                end if;
            end if; 
        end if;
    end process;

    column_5_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln154_fu_339_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    column_5_fu_90 <= add_ln154_fu_345_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    column_5_fu_90 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    empty_62_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_62_fu_98 <= tmp_s;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_62_fu_98 <= centre_fu_106;
                end if;
            end if; 
        end if;
    end process;

    empty_63_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_63_fu_102 <= tmp_25;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_63_fu_102 <= empty_67_fu_122;
                end if;
            end if; 
        end if;
    end process;

    empty_64_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_64_fu_110 <= tmp;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_64_fu_110 <= empty_65_fu_114;
                end if;
            end if; 
        end if;
    end process;

    empty_65_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_65_fu_114 <= tmp_26;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_65_fu_114 <= tmp_29_fu_561_p9;
                end if;
            end if; 
        end if;
    end process;

    empty_66_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_66_fu_118 <= tmp_27;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_66_fu_118 <= tmp_30_fu_580_p9;
                end if;
            end if; 
        end if;
    end process;

    empty_67_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_67_fu_122 <= tmp_25;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_67_fu_122 <= empty_68_fu_126;
                end if;
            end if; 
        end if;
    end process;

    empty_68_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_68_fu_126 <= tmp_28;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_68_fu_126 <= tmp_31_fu_599_p9;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_94 <= tmp;
                elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_fu_94 <= empty_64_fu_110;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                column_reg_759 <= ap_sig_allocacmp_column;
                hasBottom_reg_748 <= hasBottom_fu_274_p2;
                hasTop_reg_754 <= hasTop_fu_280_p2;
                icmp_ln154_reg_766 <= icmp_ln154_fu_339_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln154_fu_345_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_column) + unsigned(ap_const_lv10_1));
    add_ln184_fu_359_p2 <= std_logic_vector(unsigned(zext_ln184_fu_355_p1) + unsigned(ap_const_lv10_2));
    and_ln43_3_fu_456_p2 <= (hasTop_reg_754 and and_ln43_fu_450_p2);
    and_ln43_fu_450_p2 <= (icmp_ln43_fu_444_p2 and hasLeft_fu_423_p2);
    and_ln44_5_fu_482_p2 <= (icmp_ln47_fu_470_p2 and hasRight_fu_428_p2);
    and_ln44_6_fu_506_p2 <= (icmp_ln45_fu_500_p2 and hasRight_fu_428_p2);
    and_ln44_fu_476_p2 <= (icmp_ln46_fu_464_p2 and hasLeft_fu_423_p2);
    and_ln48_fu_524_p2 <= (hasLeft_fu_423_p2 and hasBottom_reg_748);
    and_ln50_3_fu_555_p2 <= (hasRight_fu_428_p2 and and_ln50_fu_550_p2);
    and_ln50_fu_550_p2 <= (icmp_ln50_fu_544_p2 and hasBottom_reg_748);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_114_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_114 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_161_assign_proc : process(hasBottom_reg_748, hasTop_reg_754, icmp_ln154_reg_766, centre_3_load_fu_397_p1, and_ln43_3_fu_456_p2, or_ln44_6_fu_518_p2, and_ln48_fu_524_p2, or_ln48_fu_538_p2, and_ln50_3_fu_555_p2, grp_fu_269_p2, or_ln44_fu_488_p2)
    begin
                ap_condition_161 <= (((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) 
    and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (or_ln48_fu_538_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)));
    end process;


    ap_condition_194_assign_proc : process(hasBottom_reg_748, hasTop_reg_754, icmp_ln154_reg_766, centre_3_load_fu_397_p1, and_ln43_3_fu_456_p2, or_ln44_6_fu_518_p2, and_ln48_fu_524_p2, or_ln48_fu_538_p2, and_ln50_3_fu_555_p2, grp_fu_269_p2, or_ln44_fu_488_p2)
    begin
                ap_condition_194 <= ((((((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (or_ln44_6_fu_518_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) 
    and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln43_3_fu_456_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)));
    end process;


    ap_condition_205_assign_proc : process(icmp_ln154_reg_766, centre_3_load_fu_397_p1)
    begin
                ap_condition_205 <= (not((centre_3_load_fu_397_p1 = ap_const_lv8_FF)) and not((centre_3_load_fu_397_p1 = ap_const_lv8_80)) and (icmp_ln154_reg_766 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln154_fu_339_p2)
    begin
        if (((icmp_ln154_fu_339_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_column_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, column_5_fu_90, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_column <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_column <= column_5_fu_90;
        end if; 
    end process;

    centre_3_load_fu_397_p1 <= centre_fu_106;
    grp_fu_269_p2 <= "1" when (empty_67_fu_122 = ap_const_lv8_FF) else "0";
    hasBottom_fu_274_p2 <= "1" when (unsigned(outputRow) < unsigned(ap_const_lv31_1FF)) else "0";
    hasLeft_fu_423_p2 <= "0" when (column_reg_759 = ap_const_lv10_0) else "1";
    hasRight_fu_428_p2 <= "1" when (unsigned(column_reg_759) < unsigned(ap_const_lv10_1FF)) else "0";
    hasTop_fu_280_p2 <= "0" when (outputRow = ap_const_lv31_0) else "1";
    icmp_ln154_fu_339_p2 <= "1" when (ap_sig_allocacmp_column = ap_const_lv10_200) else "0";
    icmp_ln43_fu_444_p2 <= "1" when (empty_fu_94 = ap_const_lv8_FF) else "0";
    icmp_ln44_fu_494_p2 <= "1" when (empty_64_fu_110 = ap_const_lv8_FF) else "0";
    icmp_ln45_fu_500_p2 <= "1" when (empty_65_fu_114 = ap_const_lv8_FF) else "0";
    icmp_ln46_fu_464_p2 <= "1" when (empty_62_fu_98 = ap_const_lv8_FF) else "0";
    icmp_ln47_fu_470_p2 <= "1" when (empty_66_fu_118 = ap_const_lv8_FF) else "0";
    icmp_ln48_fu_532_p2 <= "1" when (empty_63_fu_102 = ap_const_lv8_FF) else "0";
    icmp_ln50_fu_544_p2 <= "1" when (empty_68_fu_126 = ap_const_lv8_FF) else "0";
    nextColumn_fu_377_p3 <= 
        ap_const_lv9_1FF when (tmp_37_fu_369_p3(0) = '1') else 
        trunc_ln21_fu_365_p1;
    or_ln44_5_fu_512_p2 <= (icmp_ln44_fu_494_p2 or and_ln44_6_fu_506_p2);
    or_ln44_6_fu_518_p2 <= (or_ln44_fu_488_p2 or or_ln44_5_fu_512_p2);
    or_ln44_fu_488_p2 <= (and_ln44_fu_476_p2 or and_ln44_5_fu_482_p2);
    or_ln48_fu_538_p2 <= (icmp_ln48_fu_532_p2 or grp_fu_269_p2);
    out_hysteresis2_addr_1_gep_fu_252_p3 <= zext_ln154_fu_416_p1(9 - 1 downto 0);
    out_hysteresis2_addr_2_gep_fu_243_p3 <= zext_ln154_fu_416_p1(9 - 1 downto 0);
    out_hysteresis2_addr_gep_fu_260_p3 <= zext_ln154_fu_416_p1(9 - 1 downto 0);
    out_hysteresis2_address0 <= out_hysteresis2_address0_local;

    out_hysteresis2_address0_local_assign_proc : process(icmp_ln154_reg_766, zext_ln154_fu_416_p1, centre_3_load_fu_397_p1, out_hysteresis2_addr_2_gep_fu_243_p3, out_hysteresis2_addr_1_gep_fu_252_p3, out_hysteresis2_addr_gep_fu_260_p3, ap_condition_161, ap_condition_194, ap_condition_205, ap_condition_114)
    begin
        if ((ap_const_boolean_1 = ap_condition_114)) then
            if ((ap_const_boolean_1 = ap_condition_205)) then 
                out_hysteresis2_address0_local <= out_hysteresis2_addr_gep_fu_260_p3;
            elsif (((icmp_ln154_reg_766 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_FF))) then 
                out_hysteresis2_address0_local <= out_hysteresis2_addr_1_gep_fu_252_p3;
            elsif ((ap_const_boolean_1 = ap_condition_194)) then 
                out_hysteresis2_address0_local <= out_hysteresis2_addr_2_gep_fu_243_p3;
            elsif ((ap_const_boolean_1 = ap_condition_161)) then 
                out_hysteresis2_address0_local <= zext_ln154_fu_416_p1(9 - 1 downto 0);
            else 
                out_hysteresis2_address0_local <= "XXXXXXXXX";
            end if;
        else 
            out_hysteresis2_address0_local <= "XXXXXXXXX";
        end if; 
    end process;

    out_hysteresis2_ce0 <= out_hysteresis2_ce0_local;

    out_hysteresis2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, hasBottom_reg_748, hasTop_reg_754, icmp_ln154_reg_766, centre_3_load_fu_397_p1, and_ln43_3_fu_456_p2, or_ln44_6_fu_518_p2, and_ln48_fu_524_p2, or_ln48_fu_538_p2, and_ln50_3_fu_555_p2, grp_fu_269_p2, or_ln44_fu_488_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((((((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (or_ln44_6_fu_518_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 
    = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln43_3_fu_456_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) 
    and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (or_ln48_fu_538_p2 = ap_const_lv1_0) 
    and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)))) or (not((centre_3_load_fu_397_p1 = ap_const_lv8_FF)) and not((centre_3_load_fu_397_p1 = ap_const_lv8_80)) and (icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (centre_3_load_fu_397_p1 = ap_const_lv8_FF)))) then 
            out_hysteresis2_ce0_local <= ap_const_logic_1;
        else 
            out_hysteresis2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_hysteresis2_d0 <= out_hysteresis2_d0_local;

    out_hysteresis2_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, hasBottom_reg_748, hasTop_reg_754, icmp_ln154_reg_766, ap_block_pp0_stage0, centre_3_load_fu_397_p1, and_ln43_3_fu_456_p2, or_ln44_6_fu_518_p2, and_ln48_fu_524_p2, or_ln48_fu_538_p2, and_ln50_3_fu_555_p2, grp_fu_269_p2, or_ln44_fu_488_p2)
    begin
        if ((not((centre_3_load_fu_397_p1 = ap_const_lv8_FF)) and not((centre_3_load_fu_397_p1 = ap_const_lv8_80)) and (icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_hysteresis2_d0_local <= ap_const_lv8_0;
        elsif ((((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (centre_3_load_fu_397_p1 = ap_const_lv8_FF)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((((((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_1) 
    and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (or_ln44_6_fu_518_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln43_3_fu_456_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)))))) then 
            out_hysteresis2_d0_local <= ap_const_lv8_FF;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) 
    and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (or_ln48_fu_538_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 
    = and_ln43_3_fu_456_p2))))) then 
            out_hysteresis2_d0_local <= ap_const_lv8_80;
        else 
            out_hysteresis2_d0_local <= "XXXXXXXX";
        end if; 
    end process;

    out_hysteresis2_we0 <= out_hysteresis2_we0_local;

    out_hysteresis2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, hasBottom_reg_748, hasTop_reg_754, icmp_ln154_reg_766, centre_3_load_fu_397_p1, and_ln43_3_fu_456_p2, or_ln44_6_fu_518_p2, and_ln48_fu_524_p2, or_ln48_fu_538_p2, and_ln50_3_fu_555_p2, grp_fu_269_p2, or_ln44_fu_488_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and ((((((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (or_ln44_6_fu_518_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 
    = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln50_3_fu_555_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_1) and (centre_3_load_fu_397_p1 = ap_const_lv8_80))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln43_3_fu_456_p2) and (centre_3_load_fu_397_p1 = ap_const_lv8_80)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((((((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (grp_fu_269_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) 
    and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln48_fu_538_p2 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_1) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_6_fu_518_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln48_fu_524_p2) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (or_ln48_fu_538_p2 = ap_const_lv1_0) 
    and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (grp_fu_269_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln50_3_fu_555_p2) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2))) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (hasTop_reg_754 = ap_const_lv1_0) and (hasBottom_reg_748 = ap_const_lv1_0) and (or_ln44_fu_488_p2 = ap_const_lv1_0) and (centre_3_load_fu_397_p1 = ap_const_lv8_80) and (ap_const_lv1_0 = and_ln48_fu_524_p2) and (ap_const_lv1_0 = and_ln43_3_fu_456_p2)))) or (not((centre_3_load_fu_397_p1 = ap_const_lv8_FF)) and not((centre_3_load_fu_397_p1 = ap_const_lv8_80)) and (icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln154_reg_766 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (centre_3_load_fu_397_p1 = ap_const_lv8_FF)))) then 
            out_hysteresis2_we0_local <= ap_const_logic_1;
        else 
            out_hysteresis2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_address0 <= zext_ln191_fu_385_p1(9 - 1 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0 <= p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0_local;

    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZN12_GLOBAL_N_110lineBufferILi2EEE_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_address0 <= zext_ln191_fu_385_p1(9 - 1 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0 <= p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0_local;

    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZN12_GLOBAL_N_110lineBufferILi2EEE_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_address0 <= zext_ln191_fu_385_p1(9 - 1 downto 0);
    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0 <= p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0_local;

    p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZN12_GLOBAL_N_110lineBufferILi2EEE_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_29_fu_561_p7 <= "XXXXXXXX";
    tmp_30_fu_580_p7 <= "XXXXXXXX";
    tmp_31_fu_599_p7 <= "XXXXXXXX";
    tmp_37_fu_369_p3 <= add_ln184_fu_359_p2(9 downto 9);
    trunc_ln184_fu_351_p1 <= ap_sig_allocacmp_column(9 - 1 downto 0);
    trunc_ln21_fu_365_p1 <= add_ln184_fu_359_p2(9 - 1 downto 0);
    zext_ln154_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(column_reg_759),64));
    zext_ln184_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln184_fu_351_p1),10));
    zext_ln191_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nextColumn_fu_377_p3),64));
end behav;
