

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "51", "74", "96", "122", "124", "143", "162", "181", "199", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "216", "217", "218", "219"],
		"CDFG" : "canny_top",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "802629", "EstimateLatencyMax" : "803979",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "entry_proc_U0"},
			{"ID" : "5", "Name" : "grayscale_U0"}],
		"OutputProcess" : [
			{"ID" : "199", "Name" : "write_frame_U0"}],
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grayscale_U0", "Port" : "gmem0"}]},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "199", "SubInstance" : "write_frame_U0", "Port" : "gmem"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["199"], "DependentChan" : "201", "DependentChanDepth" : "11", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grayscale_U0", "Parent" : "0", "Child" : ["6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "41", "43"],
		"CDFG" : "grayscale",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "332801", "EstimateLatencyMax" : "332801",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "39", "SubInstance" : "grp_grayscale_Pipeline_burst_read_fu_225", "Port" : "gmem0", "Inst_start_state" : "74", "Inst_end_state" : "75"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["51"], "DependentChan" : "202", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_grayscale_Pipeline_unpack_pixels_fu_269", "Port" : "gray_out", "Inst_start_state" : "78", "Inst_end_state" : "79"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_7_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "79", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state79"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_words_U", "Parent" : "5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_U", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_1_U", "Parent" : "5"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_2_U", "Parent" : "5"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_3_U", "Parent" : "5"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_4_U", "Parent" : "5"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_5_U", "Parent" : "5"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_6_U", "Parent" : "5"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_7_U", "Parent" : "5"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_8_U", "Parent" : "5"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_9_U", "Parent" : "5"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_10_U", "Parent" : "5"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_11_U", "Parent" : "5"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_12_U", "Parent" : "5"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_13_U", "Parent" : "5"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_14_U", "Parent" : "5"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_15_U", "Parent" : "5"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_16_U", "Parent" : "5"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_17_U", "Parent" : "5"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_18_U", "Parent" : "5"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_19_U", "Parent" : "5"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_20_U", "Parent" : "5"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_21_U", "Parent" : "5"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_22_U", "Parent" : "5"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_23_U", "Parent" : "5"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_24_U", "Parent" : "5"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_25_U", "Parent" : "5"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_26_U", "Parent" : "5"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_27_U", "Parent" : "5"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_28_U", "Parent" : "5"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_29_U", "Parent" : "5"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_30_U", "Parent" : "5"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_31_U", "Parent" : "5"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_burst_read_fu_225", "Parent" : "5", "Child" : ["40"],
		"CDFG" : "grayscale_Pipeline_burst_read",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27", "EstimateLatencyMax" : "27",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "row_words", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "burst_read", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_burst_read_fu_225.flow_control_loop_pipe_sequential_init_U", "Parent" : "39"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_bytes_fu_232", "Parent" : "5", "Child" : ["42"],
		"CDFG" : "grayscale_Pipeline_unpack_bytes",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "26", "EstimateLatencyMax" : "26",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "row_bytes_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_words", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "unpack_bytes", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_bytes_fu_232.flow_control_loop_pipe_sequential_init_U", "Parent" : "41"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269", "Parent" : "5", "Child" : ["44", "45", "46", "47", "48", "49", "50"],
		"CDFG" : "grayscale_Pipeline_unpack_pixels",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "519", "EstimateLatencyMax" : "519",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "row_bytes", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_31", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gray_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "unpack_pixels", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.sparsemux_65_5_8_1_1_U38", "Parent" : "43"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.sparsemux_65_5_8_1_1_U39", "Parent" : "43"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.sparsemux_65_5_8_1_1_U40", "Parent" : "43"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.mul_8ns_8ns_15_1_1_U41", "Parent" : "43"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.mac_muladd_8ns_5ns_15s_15_4_1_U42", "Parent" : "43"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.mac_muladd_8ns_8ns_15ns_16_4_1_U43", "Parent" : "43"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.flow_control_loop_pipe_sequential_init_U", "Parent" : "43"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0", "Parent" : "0", "Child" : ["52", "53", "54", "55", "56", "57", "58", "60", "62", "69", "70", "71", "72", "73"],
		"CDFG" : "gaussian_blur",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1543", "EstimateLatencyMax" : "803897",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "5",
		"StartFifo" : "start_for_gaussian_blur_U0_U",
		"Port" : [
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "202", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_63_2_fu_135", "Port" : "gray_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["74"], "DependentChan" : "203", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156", "Port" : "gauss_out", "Inst_start_state" : "20", "Inst_end_state" : "21"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_59_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "21", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state21"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_U", "Parent" : "51"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_1_U", "Parent" : "51"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_2_U", "Parent" : "51"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_3_U", "Parent" : "51"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_4_U", "Parent" : "51"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.row_in_U", "Parent" : "51"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_63_2_fu_135", "Parent" : "51", "Child" : ["59"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_63_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gray_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "row_in", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_63_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_63_2_fu_135.flow_control_loop_pipe_sequential_init_U", "Parent" : "58"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_82_4_fu_142", "Parent" : "51", "Child" : ["61"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_82_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "row_in_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_in_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_in_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_in", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_82_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_82_4_fu_142.flow_control_loop_pipe_sequential_init_U", "Parent" : "60"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156", "Parent" : "51", "Child" : ["63", "64", "65", "66", "67", "68"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_130_8",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "empty_46", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_47", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_48", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_49", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gauss_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_130_8", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156.sparsemux_11_3_12_1_1_U100", "Parent" : "62"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156.sparsemux_11_3_12_1_1_U101", "Parent" : "62"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156.sparsemux_11_3_12_1_1_U102", "Parent" : "62"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156.sparsemux_11_3_12_1_1_U103", "Parent" : "62"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156.sparsemux_11_3_12_1_1_U104", "Parent" : "62"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_130_8_fu_156.flow_control_loop_pipe_sequential_init_U", "Parent" : "62"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.urem_9ns_4ns_3_13_seq_1_U117", "Parent" : "51"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.urem_9ns_4ns_3_13_seq_1_U118", "Parent" : "51"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.urem_9ns_4ns_3_13_seq_1_U119", "Parent" : "51"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.urem_9ns_4ns_3_13_seq_1_U120", "Parent" : "51"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.urem_9ns_4ns_3_13_seq_1_U121", "Parent" : "51"},
	{"ID" : "74", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sobel_U0", "Parent" : "0", "Child" : ["75", "76", "77", "78", "80", "89", "90", "91", "92", "93", "94", "95"],
		"CDFG" : "sobel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "547885",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "51",
		"StartFifo" : "start_for_sobel_U0_U",
		"Port" : [
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["51"], "DependentChan" : "203", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "78", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_96_2_fu_159", "Port" : "gauss_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["96"], "DependentChan" : "204", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "80", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169", "Port" : "sobel_out", "Inst_start_state" : "38", "Inst_end_state" : "39"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_92_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "39", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state39"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.lineBuffer_U", "Parent" : "74"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.lineBuffer_1_U", "Parent" : "74"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.lineBuffer_2_U", "Parent" : "74"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_96_2_fu_159", "Parent" : "74", "Child" : ["79"],
		"CDFG" : "sobel_Pipeline_VITIS_LOOP_96_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gauss_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_96_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_96_2_fu_159.flow_control_loop_pipe_sequential_init_U", "Parent" : "78"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169", "Parent" : "74", "Child" : ["81", "82", "83", "84", "85", "86", "87", "88"],
		"CDFG" : "sobel_Pipeline_VITIS_LOOP_149_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "516", "EstimateLatencyMax" : "516",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "sobel_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln23", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln23_1", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_149_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_7_2_8_1_1_U132", "Parent" : "80"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_7_2_8_1_1_U133", "Parent" : "80"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_7_2_8_1_1_U134", "Parent" : "80"},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.mul_10ns_11ns_20_1_1_U135", "Parent" : "80"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.mul_10ns_10ns_19_1_1_U136", "Parent" : "80"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.mul_10ns_13ns_22_1_1_U137", "Parent" : "80"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_9_3_2_1_1_U138", "Parent" : "80"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.flow_control_loop_pipe_sequential_init_U", "Parent" : "80"},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.urem_32s_3ns_2_36_seq_1_U158", "Parent" : "74"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U159", "Parent" : "74"},
	{"ID" : "91", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U160", "Parent" : "74"},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U161", "Parent" : "74"},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U162", "Parent" : "74"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U163", "Parent" : "74"},
	{"ID" : "95", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U164", "Parent" : "74"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0", "Parent" : "0", "Child" : ["97", "98", "99", "100", "101", "102", "103", "105", "113", "114", "115", "116", "117", "118", "119", "120", "121"],
		"CDFG" : "non_maximum_suppression",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "74",
		"StartFifo" : "start_for_non_maximum_suppression_U0_U",
		"Port" : [
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["74"], "DependentChan" : "204", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "103", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_50_2_fu_254", "Port" : "sobel_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "nms_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["122"], "DependentChan" : "205", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "105", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267", "Port" : "nms_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_46_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "97", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_magnitude_U", "Parent" : "96"},
	{"ID" : "98", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_magnitude_1_U", "Parent" : "96"},
	{"ID" : "99", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_magnitude_2_U", "Parent" : "96"},
	{"ID" : "100", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_direction_U", "Parent" : "96"},
	{"ID" : "101", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_direction_1_U", "Parent" : "96"},
	{"ID" : "102", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_direction_2_U", "Parent" : "96"},
	{"ID" : "103", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_50_2_fu_254", "Parent" : "96", "Child" : ["104"],
		"CDFG" : "non_maximum_suppression_Pipeline_VITIS_LOOP_50_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lineBuffer_direction_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_direction_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_direction", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_magnitude_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_magnitude_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_magnitude", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "sobel_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_50_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "104", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_50_2_fu_254.flow_control_loop_pipe_sequential_init_U", "Parent" : "103"},
	{"ID" : "105", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267", "Parent" : "96", "Child" : ["106", "107", "108", "109", "110", "111", "112"],
		"CDFG" : "non_maximum_suppression_Pipeline_VITIS_LOOP_105_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "outputRow", "Type" : "None", "Direction" : "I"},
			{"Name" : "lineBuffer_magnitude", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_direction", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_magnitude_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_direction_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_magnitude_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_direction_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln11", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "nms_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "nms_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_105_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "106", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_11_4_16_1_1_U176", "Parent" : "105"},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_11_4_16_1_1_U177", "Parent" : "105"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_16_1_1_U178", "Parent" : "105"},
	{"ID" : "109", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_16_1_1_U179", "Parent" : "105"},
	{"ID" : "110", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_16_1_1_U180", "Parent" : "105"},
	{"ID" : "111", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_8_1_1_U181", "Parent" : "105"},
	{"ID" : "112", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.flow_control_loop_pipe_sequential_init_U", "Parent" : "105"},
	{"ID" : "113", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.srem_10ns_3ns_10_14_seq_1_U203", "Parent" : "96"},
	{"ID" : "114", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_8_1_1_U204", "Parent" : "96"},
	{"ID" : "115", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_8_1_1_U205", "Parent" : "96"},
	{"ID" : "116", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U206", "Parent" : "96"},
	{"ID" : "117", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U207", "Parent" : "96"},
	{"ID" : "118", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U208", "Parent" : "96"},
	{"ID" : "119", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U209", "Parent" : "96"},
	{"ID" : "120", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U210", "Parent" : "96"},
	{"ID" : "121", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U211", "Parent" : "96"},
	{"ID" : "122", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.double_threshold_U0", "Parent" : "0", "Child" : ["123"],
		"CDFG" : "double_threshold",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "262146", "EstimateLatencyMax" : "262146",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "96",
		"StartFifo" : "start_for_double_threshold_U0_U",
		"Port" : [
			{"Name" : "nms_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["96"], "DependentChan" : "205", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "nms_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "thresh_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["124"], "DependentChan" : "206", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "thresh_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "123", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.double_threshold_U0.flow_control_loop_pipe_U", "Parent" : "122"},
	{"ID" : "124", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0", "Parent" : "0", "Child" : ["125", "126", "127", "128", "130", "136", "137", "138", "139", "140", "141", "142"],
		"CDFG" : "hysteresis_1_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "122",
		"StartFifo" : "start_for_hysteresis_1_U0_U",
		"Port" : [
			{"Name" : "thresh_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["122"], "DependentChan" : "206", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "128", "SubInstance" : "grp_hysteresis_1_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "thresh_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["143"], "DependentChan" : "207", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "130", "SubInstance" : "grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst1_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "125", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.buffer_U", "Parent" : "124"},
	{"ID" : "126", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.buffer_1_U", "Parent" : "124"},
	{"ID" : "127", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.buffer_2_U", "Parent" : "124"},
	{"ID" : "128", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "124", "Child" : ["129"],
		"CDFG" : "hysteresis_1_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "thresh_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "thresh_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "129", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "128"},
	{"ID" : "130", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "124", "Child" : ["131", "132", "133", "134", "135"],
		"CDFG" : "hysteresis_1_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_36", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_33", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_35", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst1_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "131", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U223", "Parent" : "130"},
	{"ID" : "132", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U224", "Parent" : "130"},
	{"ID" : "133", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U225", "Parent" : "130"},
	{"ID" : "134", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_x_U226", "Parent" : "130"},
	{"ID" : "135", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "130"},
	{"ID" : "136", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.srem_10ns_3ns_10_14_seq_1_U242", "Parent" : "124"},
	{"ID" : "137", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U243", "Parent" : "124"},
	{"ID" : "138", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U244", "Parent" : "124"},
	{"ID" : "139", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U245", "Parent" : "124"},
	{"ID" : "140", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U246", "Parent" : "124"},
	{"ID" : "141", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U247", "Parent" : "124"},
	{"ID" : "142", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U248", "Parent" : "124"},
	{"ID" : "143", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0", "Parent" : "0", "Child" : ["144", "145", "146", "147", "149", "155", "156", "157", "158", "159", "160", "161"],
		"CDFG" : "hysteresis_2_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "124",
		"StartFifo" : "start_for_hysteresis_2_U0_U",
		"Port" : [
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["124"], "DependentChan" : "207", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "147", "SubInstance" : "grp_hysteresis_2_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "hyst1_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["162"], "DependentChan" : "208", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "149", "SubInstance" : "grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst2_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "144", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.buffer_U", "Parent" : "143"},
	{"ID" : "145", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.buffer_1_U", "Parent" : "143"},
	{"ID" : "146", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.buffer_2_U", "Parent" : "143"},
	{"ID" : "147", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "143", "Child" : ["148"],
		"CDFG" : "hysteresis_2_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "hyst1_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "148", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "147"},
	{"ID" : "149", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "143", "Child" : ["150", "151", "152", "153", "154"],
		"CDFG" : "hysteresis_2_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst2_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "150", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U256", "Parent" : "149"},
	{"ID" : "151", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U257", "Parent" : "149"},
	{"ID" : "152", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U258", "Parent" : "149"},
	{"ID" : "153", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_x_U259", "Parent" : "149"},
	{"ID" : "154", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "149"},
	{"ID" : "155", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.srem_10ns_3ns_10_14_seq_1_U274", "Parent" : "143"},
	{"ID" : "156", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U275", "Parent" : "143"},
	{"ID" : "157", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U276", "Parent" : "143"},
	{"ID" : "158", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U277", "Parent" : "143"},
	{"ID" : "159", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U278", "Parent" : "143"},
	{"ID" : "160", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U279", "Parent" : "143"},
	{"ID" : "161", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U280", "Parent" : "143"},
	{"ID" : "162", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0", "Parent" : "0", "Child" : ["163", "164", "165", "166", "168", "174", "175", "176", "177", "178", "179", "180"],
		"CDFG" : "hysteresis_3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "143",
		"StartFifo" : "start_for_hysteresis_3_U0_U",
		"Port" : [
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["143"], "DependentChan" : "208", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "166", "SubInstance" : "grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "hyst2_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["181"], "DependentChan" : "209", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "168", "SubInstance" : "grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst3_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "163", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.buffer_U", "Parent" : "162"},
	{"ID" : "164", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.buffer_1_U", "Parent" : "162"},
	{"ID" : "165", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.buffer_2_U", "Parent" : "162"},
	{"ID" : "166", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "162", "Child" : ["167"],
		"CDFG" : "hysteresis_3_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "hyst2_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "167", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "166"},
	{"ID" : "168", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "162", "Child" : ["169", "170", "171", "172", "173"],
		"CDFG" : "hysteresis_3_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "169", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U288", "Parent" : "168"},
	{"ID" : "170", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U289", "Parent" : "168"},
	{"ID" : "171", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U290", "Parent" : "168"},
	{"ID" : "172", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_x_U291", "Parent" : "168"},
	{"ID" : "173", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "168"},
	{"ID" : "174", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.srem_10ns_3ns_10_14_seq_1_U306", "Parent" : "162"},
	{"ID" : "175", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U307", "Parent" : "162"},
	{"ID" : "176", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U308", "Parent" : "162"},
	{"ID" : "177", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U309", "Parent" : "162"},
	{"ID" : "178", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U310", "Parent" : "162"},
	{"ID" : "179", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U311", "Parent" : "162"},
	{"ID" : "180", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U312", "Parent" : "162"},
	{"ID" : "181", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0", "Parent" : "0", "Child" : ["182", "183", "184", "185", "187", "192", "193", "194", "195", "196", "197", "198"],
		"CDFG" : "hysteresis_4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "162",
		"StartFifo" : "start_for_hysteresis_4_U0_U",
		"Port" : [
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["162"], "DependentChan" : "209", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "185", "SubInstance" : "grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "hyst3_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst4_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["199"], "DependentChan" : "210", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "187", "SubInstance" : "grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst4_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "182", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.buffer_U", "Parent" : "181"},
	{"ID" : "183", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.buffer_1_U", "Parent" : "181"},
	{"ID" : "184", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.buffer_2_U", "Parent" : "181"},
	{"ID" : "185", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "181", "Child" : ["186"],
		"CDFG" : "hysteresis_4_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "hyst3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "186", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "185"},
	{"ID" : "187", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "181", "Child" : ["188", "189", "190", "191"],
		"CDFG" : "hysteresis_4_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst4_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "188", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U320", "Parent" : "187"},
	{"ID" : "189", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U321", "Parent" : "187"},
	{"ID" : "190", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U322", "Parent" : "187"},
	{"ID" : "191", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "187"},
	{"ID" : "192", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.srem_10ns_3ns_10_14_seq_1_U337", "Parent" : "181"},
	{"ID" : "193", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U338", "Parent" : "181"},
	{"ID" : "194", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U339", "Parent" : "181"},
	{"ID" : "195", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U340", "Parent" : "181"},
	{"ID" : "196", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U341", "Parent" : "181"},
	{"ID" : "197", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U342", "Parent" : "181"},
	{"ID" : "198", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U343", "Parent" : "181"},
	{"ID" : "199", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_frame_U0", "Parent" : "0", "Child" : ["200"],
		"CDFG" : "write_frame",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "262216", "EstimateLatencyMax" : "262216",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "4",
		"StartFifo" : "start_for_write_frame_U0_U",
		"Port" : [
			{"Name" : "hyst4_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["181"], "DependentChan" : "210", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "hyst4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "out_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["4"], "DependentChan" : "201", "DependentChanDepth" : "11", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_7_1_VITIS_LOOP_8_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter71", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter71", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "200", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_frame_U0.flow_control_loop_delay_pipe_U", "Parent" : "199"},
	{"ID" : "201", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_c_U", "Parent" : "0"},
	{"ID" : "202", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gray_out_U", "Parent" : "0"},
	{"ID" : "203", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gauss_out_U", "Parent" : "0"},
	{"ID" : "204", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sobel_out_U", "Parent" : "0"},
	{"ID" : "205", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.nms_out_U", "Parent" : "0"},
	{"ID" : "206", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.thresh_out_U", "Parent" : "0"},
	{"ID" : "207", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst1_out_U", "Parent" : "0"},
	{"ID" : "208", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst2_out_U", "Parent" : "0"},
	{"ID" : "209", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst3_out_U", "Parent" : "0"},
	{"ID" : "210", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst4_out_U", "Parent" : "0"},
	{"ID" : "211", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_frame_U0_U", "Parent" : "0"},
	{"ID" : "212", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_gaussian_blur_U0_U", "Parent" : "0"},
	{"ID" : "213", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_sobel_U0_U", "Parent" : "0"},
	{"ID" : "214", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_non_maximum_suppression_U0_U", "Parent" : "0"},
	{"ID" : "215", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_double_threshold_U0_U", "Parent" : "0"},
	{"ID" : "216", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_1_U0_U", "Parent" : "0"},
	{"ID" : "217", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_2_U0_U", "Parent" : "0"},
	{"ID" : "218", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_3_U0_U", "Parent" : "0"},
	{"ID" : "219", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_4_U0_U", "Parent" : "0"}]}
