

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "51", "71", "93", "119", "121", "140", "159", "178", "196", "198", "199", "200", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "216"],
		"CDFG" : "canny_top",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "547115", "EstimateLatencyMax" : "548071",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "entry_proc_U0"},
			{"ID" : "5", "Name" : "grayscale_U0"}],
		"OutputProcess" : [
			{"ID" : "196", "Name" : "write_frame_U0"}],
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grayscale_U0", "Port" : "gmem0"}]},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "196", "SubInstance" : "write_frame_U0", "Port" : "gmem"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["196"], "DependentChan" : "198", "DependentChanDepth" : "11", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grayscale_U0", "Parent" : "0", "Child" : ["6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "41", "43"],
		"CDFG" : "grayscale",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "332801", "EstimateLatencyMax" : "332801",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "39", "SubInstance" : "grp_grayscale_Pipeline_burst_read_fu_225", "Port" : "gmem0", "Inst_start_state" : "74", "Inst_end_state" : "75"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["51"], "DependentChan" : "199", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "43", "SubInstance" : "grp_grayscale_Pipeline_unpack_pixels_fu_269", "Port" : "gray_out", "Inst_start_state" : "78", "Inst_end_state" : "79"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_7_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "79", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state79"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_words_U", "Parent" : "5"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_U", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_1_U", "Parent" : "5"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_2_U", "Parent" : "5"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_3_U", "Parent" : "5"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_4_U", "Parent" : "5"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_5_U", "Parent" : "5"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_6_U", "Parent" : "5"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_7_U", "Parent" : "5"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_8_U", "Parent" : "5"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_9_U", "Parent" : "5"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_10_U", "Parent" : "5"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_11_U", "Parent" : "5"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_12_U", "Parent" : "5"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_13_U", "Parent" : "5"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_14_U", "Parent" : "5"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_15_U", "Parent" : "5"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_16_U", "Parent" : "5"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_17_U", "Parent" : "5"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_18_U", "Parent" : "5"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_19_U", "Parent" : "5"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_20_U", "Parent" : "5"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_21_U", "Parent" : "5"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_22_U", "Parent" : "5"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_23_U", "Parent" : "5"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_24_U", "Parent" : "5"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_25_U", "Parent" : "5"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_26_U", "Parent" : "5"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_27_U", "Parent" : "5"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_28_U", "Parent" : "5"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_29_U", "Parent" : "5"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_30_U", "Parent" : "5"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.row_bytes_31_U", "Parent" : "5"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_burst_read_fu_225", "Parent" : "5", "Child" : ["40"],
		"CDFG" : "grayscale_Pipeline_burst_read",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27", "EstimateLatencyMax" : "27",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "row_words", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "burst_read", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_burst_read_fu_225.flow_control_loop_pipe_sequential_init_U", "Parent" : "39"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_bytes_fu_232", "Parent" : "5", "Child" : ["42"],
		"CDFG" : "grayscale_Pipeline_unpack_bytes",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "26", "EstimateLatencyMax" : "26",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "row_bytes_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_bytes", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_words", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "unpack_bytes", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_bytes_fu_232.flow_control_loop_pipe_sequential_init_U", "Parent" : "41"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269", "Parent" : "5", "Child" : ["44", "45", "46", "47", "48", "49", "50"],
		"CDFG" : "grayscale_Pipeline_unpack_pixels",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "519", "EstimateLatencyMax" : "519",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "row_bytes", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_bytes_31", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gray_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "unpack_pixels", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.sparsemux_65_5_8_1_1_U38", "Parent" : "43"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.sparsemux_65_5_8_1_1_U39", "Parent" : "43"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.sparsemux_65_5_8_1_1_U40", "Parent" : "43"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.mul_8ns_8ns_15_1_1_U41", "Parent" : "43"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.mac_muladd_8ns_5ns_15s_15_4_1_U42", "Parent" : "43"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.mac_muladd_8ns_8ns_15ns_16_4_1_U43", "Parent" : "43"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grayscale_U0.grp_grayscale_Pipeline_unpack_pixels_fu_269.flow_control_loop_pipe_sequential_init_U", "Parent" : "43"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0", "Parent" : "0", "Child" : ["52", "53", "54", "55", "56", "57", "60", "67", "68", "69", "70"],
		"CDFG" : "gaussian_blur",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1543", "EstimateLatencyMax" : "539701",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "5",
		"StartFifo" : "start_for_gaussian_blur_U0_U",
		"Port" : [
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "199", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "gray_out_blk_n", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "57", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_94_2_fu_114", "Port" : "gray_out", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["71"], "DependentChan" : "200", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "60", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129", "Port" : "gauss_out", "Inst_start_state" : "20", "Inst_end_state" : "21"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_59_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "21", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state21"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_U", "Parent" : "51"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_1_U", "Parent" : "51"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_2_U", "Parent" : "51"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_3_U", "Parent" : "51"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.lineBuffer_4_U", "Parent" : "51"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_94_2_fu_114", "Parent" : "51", "Child" : ["58", "59"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_94_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "sample2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sample1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sample0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gray_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gray_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "lineBuffer_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_94_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_94_2_fu_114.sparsemux_9_2_8_1_1_U88", "Parent" : "57"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_94_2_fu_114.flow_control_loop_pipe_sequential_init_U", "Parent" : "57"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129", "Parent" : "51", "Child" : ["61", "62", "63", "64", "65", "66"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_157_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln21", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln21_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_45", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln21_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gauss_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_157_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129.sparsemux_11_3_12_1_1_U100", "Parent" : "60"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129.sparsemux_11_3_12_1_1_U101", "Parent" : "60"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129.sparsemux_11_3_12_1_1_U102", "Parent" : "60"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129.sparsemux_11_3_12_1_1_U103", "Parent" : "60"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129.sparsemux_11_3_12_1_1_U104", "Parent" : "60"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_157_7_fu_129.flow_control_loop_pipe_sequential_init_U", "Parent" : "60"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.srem_10ns_4ns_10_14_seq_1_U118", "Parent" : "51"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.srem_10ns_4ns_10_14_seq_1_U119", "Parent" : "51"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.srem_11ns_4ns_11_15_seq_1_U120", "Parent" : "51"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.gaussian_blur_U0.urem_9ns_4ns_3_13_seq_1_U121", "Parent" : "51"},
	{"ID" : "71", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sobel_U0", "Parent" : "0", "Child" : ["72", "73", "74", "75", "77", "86", "87", "88", "89", "90", "91", "92"],
		"CDFG" : "sobel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "547885",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "51",
		"StartFifo" : "start_for_sobel_U0_U",
		"Port" : [
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["51"], "DependentChan" : "200", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "75", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_96_2_fu_159", "Port" : "gauss_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["93"], "DependentChan" : "201", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "77", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169", "Port" : "sobel_out", "Inst_start_state" : "38", "Inst_end_state" : "39"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_92_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "39", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state39"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.lineBuffer_U", "Parent" : "71"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.lineBuffer_1_U", "Parent" : "71"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.lineBuffer_2_U", "Parent" : "71"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_96_2_fu_159", "Parent" : "71", "Child" : ["76"],
		"CDFG" : "sobel_Pipeline_VITIS_LOOP_96_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "gauss_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gauss_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_96_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_96_2_fu_159.flow_control_loop_pipe_sequential_init_U", "Parent" : "75"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169", "Parent" : "71", "Child" : ["78", "79", "80", "81", "82", "83", "84", "85"],
		"CDFG" : "sobel_Pipeline_VITIS_LOOP_149_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "516", "EstimateLatencyMax" : "516",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "sobel_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "lineBuffer", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln23", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln23_1", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_149_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_7_2_8_1_1_U133", "Parent" : "77"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_7_2_8_1_1_U134", "Parent" : "77"},
	{"ID" : "80", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_7_2_8_1_1_U135", "Parent" : "77"},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.mul_10ns_11ns_20_1_1_U136", "Parent" : "77"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.mul_10ns_10ns_19_1_1_U137", "Parent" : "77"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.mul_10ns_13ns_22_1_1_U138", "Parent" : "77"},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.sparsemux_9_3_2_1_1_U139", "Parent" : "77"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_149_6_fu_169.flow_control_loop_pipe_sequential_init_U", "Parent" : "77"},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.urem_32s_3ns_2_36_seq_1_U159", "Parent" : "71"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U160", "Parent" : "71"},
	{"ID" : "88", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U161", "Parent" : "71"},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U162", "Parent" : "71"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U163", "Parent" : "71"},
	{"ID" : "91", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U164", "Parent" : "71"},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.sobel_U0.sparsemux_7_2_8_1_1_U165", "Parent" : "71"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0", "Parent" : "0", "Child" : ["94", "95", "96", "97", "98", "99", "100", "102", "110", "111", "112", "113", "114", "115", "116", "117", "118"],
		"CDFG" : "non_maximum_suppression",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "71",
		"StartFifo" : "start_for_non_maximum_suppression_U0_U",
		"Port" : [
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["71"], "DependentChan" : "201", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "100", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_50_2_fu_254", "Port" : "sobel_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "nms_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["119"], "DependentChan" : "202", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "102", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267", "Port" : "nms_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_46_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_magnitude_U", "Parent" : "93"},
	{"ID" : "95", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_magnitude_1_U", "Parent" : "93"},
	{"ID" : "96", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_magnitude_2_U", "Parent" : "93"},
	{"ID" : "97", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_direction_U", "Parent" : "93"},
	{"ID" : "98", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_direction_1_U", "Parent" : "93"},
	{"ID" : "99", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.lineBuffer_direction_2_U", "Parent" : "93"},
	{"ID" : "100", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_50_2_fu_254", "Parent" : "93", "Child" : ["101"],
		"CDFG" : "non_maximum_suppression_Pipeline_VITIS_LOOP_50_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lineBuffer_direction_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_direction_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_direction", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_magnitude_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_magnitude_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "lineBuffer_magnitude", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "sobel_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "sobel_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_50_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "101", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_50_2_fu_254.flow_control_loop_pipe_sequential_init_U", "Parent" : "100"},
	{"ID" : "102", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267", "Parent" : "93", "Child" : ["103", "104", "105", "106", "107", "108", "109"],
		"CDFG" : "non_maximum_suppression_Pipeline_VITIS_LOOP_105_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "outputRow", "Type" : "None", "Direction" : "I"},
			{"Name" : "lineBuffer_magnitude", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_direction", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_magnitude_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_direction_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_magnitude_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lineBuffer_direction_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln11", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "nms_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "nms_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_105_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "103", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_11_4_16_1_1_U178", "Parent" : "102"},
	{"ID" : "104", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_11_4_16_1_1_U179", "Parent" : "102"},
	{"ID" : "105", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_16_1_1_U180", "Parent" : "102"},
	{"ID" : "106", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_16_1_1_U181", "Parent" : "102"},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_16_1_1_U182", "Parent" : "102"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.sparsemux_7_2_8_1_1_U183", "Parent" : "102"},
	{"ID" : "109", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_105_5_fu_267.flow_control_loop_pipe_sequential_init_U", "Parent" : "102"},
	{"ID" : "110", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.srem_10ns_3ns_10_14_seq_1_U205", "Parent" : "93"},
	{"ID" : "111", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_8_1_1_U206", "Parent" : "93"},
	{"ID" : "112", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_8_1_1_U207", "Parent" : "93"},
	{"ID" : "113", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U208", "Parent" : "93"},
	{"ID" : "114", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U209", "Parent" : "93"},
	{"ID" : "115", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U210", "Parent" : "93"},
	{"ID" : "116", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U211", "Parent" : "93"},
	{"ID" : "117", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U212", "Parent" : "93"},
	{"ID" : "118", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.non_maximum_suppression_U0.sparsemux_7_2_16_1_1_U213", "Parent" : "93"},
	{"ID" : "119", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.double_threshold_U0", "Parent" : "0", "Child" : ["120"],
		"CDFG" : "double_threshold",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "262146", "EstimateLatencyMax" : "262146",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "93",
		"StartFifo" : "start_for_double_threshold_U0_U",
		"Port" : [
			{"Name" : "nms_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["93"], "DependentChan" : "202", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "nms_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "thresh_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["121"], "DependentChan" : "203", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "thresh_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "120", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.double_threshold_U0.flow_control_loop_pipe_U", "Parent" : "119"},
	{"ID" : "121", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0", "Parent" : "0", "Child" : ["122", "123", "124", "125", "127", "133", "134", "135", "136", "137", "138", "139"],
		"CDFG" : "hysteresis_1_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "119",
		"StartFifo" : "start_for_hysteresis_1_U0_U",
		"Port" : [
			{"Name" : "thresh_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["119"], "DependentChan" : "203", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "125", "SubInstance" : "grp_hysteresis_1_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "thresh_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["140"], "DependentChan" : "204", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "127", "SubInstance" : "grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst1_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "122", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.buffer_U", "Parent" : "121"},
	{"ID" : "123", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.buffer_1_U", "Parent" : "121"},
	{"ID" : "124", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.buffer_2_U", "Parent" : "121"},
	{"ID" : "125", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "121", "Child" : ["126"],
		"CDFG" : "hysteresis_1_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "thresh_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "thresh_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "126", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "125"},
	{"ID" : "127", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "121", "Child" : ["128", "129", "130", "131", "132"],
		"CDFG" : "hysteresis_1_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_36", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_33", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_35", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst1_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "128", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U225", "Parent" : "127"},
	{"ID" : "129", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U226", "Parent" : "127"},
	{"ID" : "130", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U227", "Parent" : "127"},
	{"ID" : "131", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_x_U228", "Parent" : "127"},
	{"ID" : "132", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.grp_hysteresis_1_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "127"},
	{"ID" : "133", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.srem_10ns_3ns_10_14_seq_1_U244", "Parent" : "121"},
	{"ID" : "134", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U245", "Parent" : "121"},
	{"ID" : "135", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U246", "Parent" : "121"},
	{"ID" : "136", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U247", "Parent" : "121"},
	{"ID" : "137", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U248", "Parent" : "121"},
	{"ID" : "138", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U249", "Parent" : "121"},
	{"ID" : "139", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_1_U0.sparsemux_7_2_8_1_1_U250", "Parent" : "121"},
	{"ID" : "140", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0", "Parent" : "0", "Child" : ["141", "142", "143", "144", "146", "152", "153", "154", "155", "156", "157", "158"],
		"CDFG" : "hysteresis_2_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "121",
		"StartFifo" : "start_for_hysteresis_2_U0_U",
		"Port" : [
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["121"], "DependentChan" : "204", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "144", "SubInstance" : "grp_hysteresis_2_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "hyst1_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["159"], "DependentChan" : "205", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "146", "SubInstance" : "grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst2_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "141", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.buffer_U", "Parent" : "140"},
	{"ID" : "142", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.buffer_1_U", "Parent" : "140"},
	{"ID" : "143", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.buffer_2_U", "Parent" : "140"},
	{"ID" : "144", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "140", "Child" : ["145"],
		"CDFG" : "hysteresis_2_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "hyst1_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "hyst1_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "145", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "144"},
	{"ID" : "146", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "140", "Child" : ["147", "148", "149", "150", "151"],
		"CDFG" : "hysteresis_2_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_29", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst2_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "147", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U258", "Parent" : "146"},
	{"ID" : "148", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U259", "Parent" : "146"},
	{"ID" : "149", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U260", "Parent" : "146"},
	{"ID" : "150", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_x_U261", "Parent" : "146"},
	{"ID" : "151", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.grp_hysteresis_2_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "146"},
	{"ID" : "152", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.srem_10ns_3ns_10_14_seq_1_U276", "Parent" : "140"},
	{"ID" : "153", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U277", "Parent" : "140"},
	{"ID" : "154", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U278", "Parent" : "140"},
	{"ID" : "155", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U279", "Parent" : "140"},
	{"ID" : "156", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U280", "Parent" : "140"},
	{"ID" : "157", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U281", "Parent" : "140"},
	{"ID" : "158", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_2_U0.sparsemux_7_2_8_1_1_U282", "Parent" : "140"},
	{"ID" : "159", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0", "Parent" : "0", "Child" : ["160", "161", "162", "163", "165", "171", "172", "173", "174", "175", "176", "177"],
		"CDFG" : "hysteresis_3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "140",
		"StartFifo" : "start_for_hysteresis_3_U0_U",
		"Port" : [
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["140"], "DependentChan" : "205", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "163", "SubInstance" : "grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "hyst2_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["178"], "DependentChan" : "206", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "165", "SubInstance" : "grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst3_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "160", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.buffer_U", "Parent" : "159"},
	{"ID" : "161", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.buffer_1_U", "Parent" : "159"},
	{"ID" : "162", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.buffer_2_U", "Parent" : "159"},
	{"ID" : "163", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "159", "Child" : ["164"],
		"CDFG" : "hysteresis_3_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "hyst2_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "hyst2_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "164", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "163"},
	{"ID" : "165", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "159", "Child" : ["166", "167", "168", "169", "170"],
		"CDFG" : "hysteresis_3_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "166", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U290", "Parent" : "165"},
	{"ID" : "167", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U291", "Parent" : "165"},
	{"ID" : "168", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U292", "Parent" : "165"},
	{"ID" : "169", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_x_U293", "Parent" : "165"},
	{"ID" : "170", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.grp_hysteresis_3_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "165"},
	{"ID" : "171", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.srem_10ns_3ns_10_14_seq_1_U308", "Parent" : "159"},
	{"ID" : "172", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U309", "Parent" : "159"},
	{"ID" : "173", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U310", "Parent" : "159"},
	{"ID" : "174", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U311", "Parent" : "159"},
	{"ID" : "175", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U312", "Parent" : "159"},
	{"ID" : "176", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U313", "Parent" : "159"},
	{"ID" : "177", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_3_U0.sparsemux_7_2_8_1_1_U314", "Parent" : "159"},
	{"ID" : "178", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0", "Parent" : "0", "Child" : ["179", "180", "181", "182", "184", "189", "190", "191", "192", "193", "194", "195"],
		"CDFG" : "hysteresis_4_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1540", "EstimateLatencyMax" : "536086",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "159",
		"StartFifo" : "start_for_hysteresis_4_U0_U",
		"Port" : [
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["159"], "DependentChan" : "206", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "182", "SubInstance" : "grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165", "Port" : "hyst3_out", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "hyst4_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["196"], "DependentChan" : "207", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "184", "SubInstance" : "grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175", "Port" : "hyst4_out", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "179", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.buffer_U", "Parent" : "178"},
	{"ID" : "180", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.buffer_1_U", "Parent" : "178"},
	{"ID" : "181", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.buffer_2_U", "Parent" : "178"},
	{"ID" : "182", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165", "Parent" : "178", "Child" : ["183"],
		"CDFG" : "hysteresis_4_Pipeline_VITIS_LOOP_78_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "hyst3_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "hyst3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "183", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_78_2_fu_165.flow_control_loop_pipe_sequential_init_U", "Parent" : "182"},
	{"ID" : "184", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175", "Parent" : "178", "Child" : ["185", "186", "187", "188"],
		"CDFG" : "hysteresis_4_Pipeline_VITIS_LOOP_143_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasBottom", "Type" : "None", "Direction" : "I"},
			{"Name" : "hasTop", "Type" : "None", "Direction" : "I"},
			{"Name" : "hyst4_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "hyst4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "select_ln12", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "185", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U322", "Parent" : "184"},
	{"ID" : "186", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U323", "Parent" : "184"},
	{"ID" : "187", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.sparsemux_7_2_8_1_1_U324", "Parent" : "184"},
	{"ID" : "188", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.grp_hysteresis_4_Pipeline_VITIS_LOOP_143_5_fu_175.flow_control_loop_pipe_sequential_init_U", "Parent" : "184"},
	{"ID" : "189", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.srem_10ns_3ns_10_14_seq_1_U339", "Parent" : "178"},
	{"ID" : "190", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U340", "Parent" : "178"},
	{"ID" : "191", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U341", "Parent" : "178"},
	{"ID" : "192", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U342", "Parent" : "178"},
	{"ID" : "193", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U343", "Parent" : "178"},
	{"ID" : "194", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U344", "Parent" : "178"},
	{"ID" : "195", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.hysteresis_4_U0.sparsemux_7_2_8_1_1_U345", "Parent" : "178"},
	{"ID" : "196", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_frame_U0", "Parent" : "0", "Child" : ["197"],
		"CDFG" : "write_frame",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "262216", "EstimateLatencyMax" : "262216",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "4",
		"StartFifo" : "start_for_write_frame_U0_U",
		"Port" : [
			{"Name" : "hyst4_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["178"], "DependentChan" : "207", "DependentChanDepth" : "1024", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "hyst4_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "out_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["4"], "DependentChan" : "198", "DependentChanDepth" : "11", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_7_1_VITIS_LOOP_8_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter71", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter71", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "197", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_frame_U0.flow_control_loop_delay_pipe_U", "Parent" : "196"},
	{"ID" : "198", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_c_U", "Parent" : "0"},
	{"ID" : "199", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gray_out_U", "Parent" : "0"},
	{"ID" : "200", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gauss_out_U", "Parent" : "0"},
	{"ID" : "201", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sobel_out_U", "Parent" : "0"},
	{"ID" : "202", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.nms_out_U", "Parent" : "0"},
	{"ID" : "203", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.thresh_out_U", "Parent" : "0"},
	{"ID" : "204", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst1_out_U", "Parent" : "0"},
	{"ID" : "205", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst2_out_U", "Parent" : "0"},
	{"ID" : "206", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst3_out_U", "Parent" : "0"},
	{"ID" : "207", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hyst4_out_U", "Parent" : "0"},
	{"ID" : "208", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_frame_U0_U", "Parent" : "0"},
	{"ID" : "209", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_gaussian_blur_U0_U", "Parent" : "0"},
	{"ID" : "210", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_sobel_U0_U", "Parent" : "0"},
	{"ID" : "211", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_non_maximum_suppression_U0_U", "Parent" : "0"},
	{"ID" : "212", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_double_threshold_U0_U", "Parent" : "0"},
	{"ID" : "213", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_1_U0_U", "Parent" : "0"},
	{"ID" : "214", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_2_U0_U", "Parent" : "0"},
	{"ID" : "215", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_3_U0_U", "Parent" : "0"},
	{"ID" : "216", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_hysteresis_4_U0_U", "Parent" : "0"}]}
