

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4"],
		"CDFG" : "canny_top",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "831702", "EstimateLatencyMax" : "2402331",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0"}],
		"OutputProcess" : [
			{"ID" : "4", "Name" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0"}],
		"Port" : [
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "gmem_in"}]},
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "gmem_out"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_rowsReceived", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_rowsReceived"}]},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_0"}]},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_1"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_2", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_rowsReceived_2"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_16_0"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_16_1"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_3", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_rowsReceived_3"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_direction", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_direction"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_0"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_1"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_1", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_rowsReceived_1"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_6_0"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "p_anonymous_namespace_lineBuffer_6_1"}]},
			{"Name" : "rowsReceived", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Port" : "rowsReceived"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_7_1", "PipelineType" : "dataflow",
				"LoopDec" : {"InfiniteLoop" : "0", "BodyInst" : "dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "has_continue" : "1"}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_in_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0", "Parent" : "0", "Child" : ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "20", "32", "50", "61", "64", "74", "77", "78", "79", "80", "81", "82", "83"],
		"CDFG" : "dataflow_in_loop_VITIS_LOOP_7_1_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2179", "EstimateLatencyMax" : "14314",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "12", "Name" : "entry_proc_U0"},
			{"ID" : "13", "Name" : "dataflow_in_loop_VITIS_LOOP_7_1_1_Block_newFuncRoot_proc_U0"},
			{"ID" : "14", "Name" : "grayscale_U0"}],
		"OutputProcess" : [
			{"ID" : "74", "Name" : "output_row_U0"}],
		"Port" : [
			{"Name" : "i_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grayscale_U0", "Port" : "gmem_in"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "74", "SubInstance" : "output_row_U0", "Port" : "gmem_out"}]},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_rowsReceived", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "gaussian_blur_U0", "Port" : "p_anonymous_namespace_rowsReceived"}]},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "gaussian_blur_U0", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_0"}]},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "gaussian_blur_U0", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_1"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_2", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "32", "SubInstance" : "sobel_U0", "Port" : "p_anonymous_namespace_rowsReceived_2"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "32", "SubInstance" : "sobel_U0", "Port" : "p_anonymous_namespace_lineBuffer_16_0"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "32", "SubInstance" : "sobel_U0", "Port" : "p_anonymous_namespace_lineBuffer_16_1"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_3", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "non_maximum_suppression_U0", "Port" : "p_anonymous_namespace_rowsReceived_3"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_direction", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "non_maximum_suppression_U0", "Port" : "p_anonymous_namespace_lineBuffer_direction"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "non_maximum_suppression_U0", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_0"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "non_maximum_suppression_U0", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_1"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_1", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "hysteresis_U0", "Port" : "p_anonymous_namespace_rowsReceived_1"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "hysteresis_U0", "Port" : "p_anonymous_namespace_lineBuffer_6_0"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "64", "SubInstance" : "hysteresis_U0", "Port" : "p_anonymous_namespace_lineBuffer_6_1"}]},
			{"Name" : "rowsReceived", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "74", "SubInstance" : "output_row_U0", "Port" : "rowsReceived"}]}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_hysteresis_U", "Parent" : "4"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_double_U", "Parent" : "4"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_nonmax_U", "Parent" : "4"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_sobel_direction_U", "Parent" : "4"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_sobel_magnitude_U", "Parent" : "4"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_gaussian_U", "Parent" : "4"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_grayscale_U", "Parent" : "4"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.entry_proc_U0", "Parent" : "4",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["74"], "DependentChan" : "77", "DependentChanDepth" : "9", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.dataflow_in_loop_VITIS_LOOP_7_1_1_Block_newFuncRoot_proc_U0", "Parent" : "4",
		"CDFG" : "dataflow_in_loop_VITIS_LOOP_7_1_1_Block_newFuncRoot_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "i_0", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.grayscale_U0", "Parent" : "4", "Child" : ["15"],
		"CDFG" : "grayscale",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1616", "EstimateLatencyMax" : "1616",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["13"], "DependentChan" : "78", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50", "Port" : "gmem_in", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_grayscale", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["20"], "DependentChan" : "11",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50", "Port" : "out_grayscale", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}]},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.grayscale_U0.grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50", "Parent" : "14", "Child" : ["16", "17", "18", "19"],
		"CDFG" : "grayscale_Pipeline_VITIS_LOOP_7_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1614", "EstimateLatencyMax" : "1614",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_in_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "out_grayscale", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_7_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter26", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter26", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "16", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.grayscale_U0.grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50.mul_8ns_8ns_15_1_1_U4", "Parent" : "15"},
	{"ID" : "17", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.grayscale_U0.grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50.mac_muladd_8ns_5ns_15s_15_4_1_U5", "Parent" : "15"},
	{"ID" : "18", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.grayscale_U0.grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50.mac_muladd_8ns_8ns_15ns_16_4_1_U6", "Parent" : "15"},
	{"ID" : "19", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.grayscale_U0.grp_grayscale_Pipeline_VITIS_LOOP_7_1_fu_50.flow_control_loop_pipe_sequential_init_U", "Parent" : "15"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0", "Parent" : "4", "Child" : ["21", "22", "23", "25", "27", "28", "29", "30", "31"],
		"CDFG" : "gaussian_blur",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "551", "EstimateLatencyMax" : "4654",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["14"], "DependentChan" : "11",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_46_1_fu_54", "Port" : "input_r", "Inst_start_state" : "36", "Inst_end_state" : "37"}]},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["32"], "DependentChan" : "10",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_46_1_fu_54", "Port" : "output_r", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "25", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_64_2_fu_67", "Port" : "output_r", "Inst_start_state" : "72", "Inst_end_state" : "73"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_46_1_fu_54", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "25", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_64_2_fu_67", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Inst_start_state" : "72", "Inst_end_state" : "73"}]},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_46_1_fu_54", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "25", "SubInstance" : "grp_gaussian_blur_Pipeline_VITIS_LOOP_64_2_fu_67", "Port" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Inst_start_state" : "72", "Inst_end_state" : "73"}]}]},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.p_ZN12_GLOBAL_N_110lineBufferE_0_U", "Parent" : "20"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.p_ZN12_GLOBAL_N_110lineBufferE_1_U", "Parent" : "20"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_46_1_fu_54", "Parent" : "20", "Child" : ["24"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_46_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_46_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "24", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_46_1_fu_54.flow_control_loop_pipe_sequential_init_U", "Parent" : "23"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_64_2_fu_67", "Parent" : "20", "Child" : ["26"],
		"CDFG" : "gaussian_blur_Pipeline_VITIS_LOOP_64_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4068", "EstimateLatencyMax" : "4068",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "select_ln22", "Type" : "None", "Direction" : "I"},
			{"Name" : "result_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln22_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln22_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln22_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZN12_GLOBAL_N_110lineBufferE_1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_64_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "8", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "26", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.grp_gaussian_blur_Pipeline_VITIS_LOOP_64_2_fu_67.flow_control_loop_pipe_sequential_init_U", "Parent" : "25"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.srem_32ns_4ns_32_36_seq_1_U30", "Parent" : "20"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.srem_32ns_4ns_32_36_seq_1_U31", "Parent" : "20"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.urem_32ns_4ns_3_36_seq_1_U32", "Parent" : "20"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.srem_32ns_4ns_32_36_seq_1_U33", "Parent" : "20"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_blur_U0.srem_32ns_4ns_32_36_seq_1_U34", "Parent" : "20"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0", "Parent" : "4", "Child" : ["33", "34", "35", "37", "47", "48", "49"],
		"CDFG" : "sobel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "2187",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["20"], "DependentChan" : "79", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "out_gaussian", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["20"], "DependentChan" : "10",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75", "Port" : "out_gaussian", "Inst_start_state" : "36", "Inst_end_state" : "37"}]},
			{"Name" : "out_sobel_magnitude", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["50"], "DependentChan" : "9",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75", "Port" : "out_sobel_magnitude", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "37", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90", "Port" : "out_sobel_magnitude", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "out_sobel_direction", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["50"], "DependentChan" : "8",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75", "Port" : "out_sobel_direction", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "37", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90", "Port" : "out_sobel_direction", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75", "Port" : "p_anonymous_namespace_lineBuffer_16_0", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "37", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90", "Port" : "p_anonymous_namespace_lineBuffer_16_0", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75", "Port" : "p_anonymous_namespace_lineBuffer_16_1", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "37", "SubInstance" : "grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90", "Port" : "p_anonymous_namespace_lineBuffer_16_1", "Inst_start_state" : "71", "Inst_end_state" : "72"}]}]},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.p_anonymous_namespace_lineBuffer_16_0_U", "Parent" : "32"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.p_anonymous_namespace_lineBuffer_16_1_U", "Parent" : "32"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75", "Parent" : "32", "Child" : ["36"],
		"CDFG" : "sobel_Pipeline_VITIS_LOOP_89_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_sobel_magnitude", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_sobel_direction", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "writeSlot", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_gaussian", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_89_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "36", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_89_1_fu_75.flow_control_loop_pipe_sequential_init_U", "Parent" : "35"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90", "Parent" : "32", "Child" : ["38", "39", "40", "41", "42", "43", "44", "45", "46"],
		"CDFG" : "sobel_Pipeline_VITIS_LOOP_118_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1602", "EstimateLatencyMax" : "1602",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "result", "Type" : "None", "Direction" : "I"},
			{"Name" : "writeSlot", "Type" : "None", "Direction" : "I"},
			{"Name" : "result_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_sobel_magnitude", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "out_sobel_direction", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_16_1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_118_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter24", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter24", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "38", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.sitodp_32s_64_6_no_dsp_1_U46", "Parent" : "37"},
	{"ID" : "39", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.dsqrt_64ns_64ns_64_57_no_dsp_1_U47", "Parent" : "37"},
	{"ID" : "40", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.mul_10ns_11ns_20_1_1_U48", "Parent" : "37"},
	{"ID" : "41", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.mul_11s_11s_22_1_1_U49", "Parent" : "37"},
	{"ID" : "42", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.mul_10ns_10ns_19_1_1_U50", "Parent" : "37"},
	{"ID" : "43", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.mul_10ns_13ns_22_1_1_U51", "Parent" : "37"},
	{"ID" : "44", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.sparsemux_9_3_2_1_1_U52", "Parent" : "37"},
	{"ID" : "45", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.mac_muladd_11s_11s_22s_22_4_1_U53", "Parent" : "37"},
	{"ID" : "46", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.grp_sobel_Pipeline_VITIS_LOOP_118_2_fu_90.flow_control_loop_pipe_sequential_init_U", "Parent" : "37"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.srem_32ns_3ns_2_36_seq_1_U69", "Parent" : "32"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.urem_31ns_3ns_2_35_seq_1_U70", "Parent" : "32"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_U0.urem_31ns_3ns_2_35_seq_1_U71", "Parent" : "32"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0", "Parent" : "4", "Child" : ["51", "52", "53", "54", "56", "58", "59", "60"],
		"CDFG" : "non_maximum_suppression",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1608",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["32"], "DependentChan" : "80", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "out_sobel_magnitude", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["32"], "DependentChan" : "9",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Port" : "out_sobel_magnitude", "Inst_start_state" : "36", "Inst_end_state" : "37"}]},
			{"Name" : "out_sobel_direction", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["32"], "DependentChan" : "8",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Port" : "out_sobel_direction", "Inst_start_state" : "36", "Inst_end_state" : "37"}]},
			{"Name" : "out_nonmax", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["61"], "DependentChan" : "7",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Port" : "out_nonmax", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "56", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2_fu_99", "Port" : "out_nonmax", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_anonymous_namespace_lineBuffer_direction", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Port" : "p_anonymous_namespace_lineBuffer_direction", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "56", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2_fu_99", "Port" : "p_anonymous_namespace_lineBuffer_direction", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "56", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2_fu_99", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "56", "SubInstance" : "grp_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2_fu_99", "Port" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Inst_start_state" : "71", "Inst_end_state" : "72"}]}]},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.p_anonymous_namespace_lineBuffer_direction_U", "Parent" : "50"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.p_anonymous_namespace_lineBuffer_11_magnitude_0_U", "Parent" : "50"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.p_anonymous_namespace_lineBuffer_11_magnitude_1_U", "Parent" : "50"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81", "Parent" : "50", "Child" : ["55"],
		"CDFG" : "non_maximum_suppression_Pipeline_VITIS_LOOP_45_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_nonmax", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "zext_ln46", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_sobel_magnitude", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_sobel_direction", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_direction", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_45_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "55", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_45_1_fu_81.flow_control_loop_pipe_sequential_init_U", "Parent" : "54"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2_fu_99", "Parent" : "50", "Child" : ["57"],
		"CDFG" : "non_maximum_suppression_Pipeline_VITIS_LOOP_81_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1023", "EstimateLatencyMax" : "1023",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_nonmax", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "result_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "result", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_11_magnitude_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_direction", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_81_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "57", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.grp_non_maximum_suppression_Pipeline_VITIS_LOOP_81_2_fu_99.flow_control_loop_pipe_sequential_init_U", "Parent" : "56"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.srem_32ns_3ns_2_36_seq_1_U94", "Parent" : "50"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.urem_31ns_3ns_2_35_seq_1_U95", "Parent" : "50"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.non_maximum_suppression_U0.urem_31ns_3ns_2_35_seq_1_U96", "Parent" : "50"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.double_threshold_U0", "Parent" : "4", "Child" : ["62"],
		"CDFG" : "double_threshold",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["50"], "DependentChan" : "81", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "out_nonmax", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["50"], "DependentChan" : "7",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32", "Port" : "out_nonmax", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_double", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["64"], "DependentChan" : "6",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32", "Port" : "out_double", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.double_threshold_U0.grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32", "Parent" : "61", "Child" : ["63"],
		"CDFG" : "double_threshold_Pipeline_VITIS_LOOP_16_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_nonmax", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_double", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_16_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "63", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.double_threshold_U0.grp_double_threshold_Pipeline_VITIS_LOOP_16_1_fu_32.flow_control_loop_pipe_sequential_init_U", "Parent" : "62"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0", "Parent" : "4", "Child" : ["65", "66", "67", "69", "71", "72", "73"],
		"CDFG" : "hysteresis",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "3141",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["61"], "DependentChan" : "82", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "out_double", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["61"], "DependentChan" : "6",
				"SubConnect" : [
					{"ID" : "67", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_60_1_fu_73", "Port" : "out_double", "Inst_start_state" : "36", "Inst_end_state" : "37"}]},
			{"Name" : "out_hysteresis", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["74"], "DependentChan" : "5",
				"SubConnect" : [
					{"ID" : "67", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_60_1_fu_73", "Port" : "out_hysteresis", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "69", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_108_2_fu_86", "Port" : "out_hysteresis", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_rowsReceived_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "67", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_60_1_fu_73", "Port" : "p_anonymous_namespace_lineBuffer_6_0", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "69", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_108_2_fu_86", "Port" : "p_anonymous_namespace_lineBuffer_6_0", "Inst_start_state" : "71", "Inst_end_state" : "72"}]},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "67", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_60_1_fu_73", "Port" : "p_anonymous_namespace_lineBuffer_6_1", "Inst_start_state" : "36", "Inst_end_state" : "37"},
					{"ID" : "69", "SubInstance" : "grp_hysteresis_Pipeline_VITIS_LOOP_108_2_fu_86", "Port" : "p_anonymous_namespace_lineBuffer_6_1", "Inst_start_state" : "71", "Inst_end_state" : "72"}]}]},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.p_anonymous_namespace_lineBuffer_6_0_U", "Parent" : "64"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.p_anonymous_namespace_lineBuffer_6_1_U", "Parent" : "64"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.grp_hysteresis_Pipeline_VITIS_LOOP_60_1_fu_73", "Parent" : "64", "Child" : ["68"],
		"CDFG" : "hysteresis_Pipeline_VITIS_LOOP_60_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "514", "EstimateLatencyMax" : "514",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_hysteresis", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "writeSlot", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_double", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_60_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "68", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.grp_hysteresis_Pipeline_VITIS_LOOP_60_1_fu_73.flow_control_loop_pipe_sequential_init_U", "Parent" : "67"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.grp_hysteresis_Pipeline_VITIS_LOOP_108_2_fu_86", "Parent" : "64", "Child" : ["70"],
		"CDFG" : "hysteresis_Pipeline_VITIS_LOOP_108_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2556", "EstimateLatencyMax" : "2556",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_hysteresis", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "result_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "result", "Type" : "None", "Direction" : "I"},
			{"Name" : "writeSlot", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_anonymous_namespace_lineBuffer_6_1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_108_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage4", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage4_subdone", "QuitState" : "ap_ST_fsm_pp0_stage4", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage4_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "70", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.grp_hysteresis_Pipeline_VITIS_LOOP_108_2_fu_86.flow_control_loop_pipe_sequential_init_U", "Parent" : "69"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.srem_32ns_3ns_2_36_seq_1_U119", "Parent" : "64"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.urem_31ns_3ns_2_35_seq_1_U120", "Parent" : "64"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_U0.urem_31ns_3ns_2_35_seq_1_U121", "Parent" : "64"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.output_row_U0", "Parent" : "4", "Child" : ["75"],
		"CDFG" : "output_row",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "586",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "83", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "out_hysteresis", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["64"], "DependentChan" : "5",
				"SubConnect" : [
					{"ID" : "75", "SubInstance" : "grp_output_row_Pipeline_VITIS_LOOP_20_1_fu_84", "Port" : "out_hysteresis", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_out_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "75", "SubInstance" : "grp_output_row_Pipeline_VITIS_LOOP_20_1_fu_84", "Port" : "gmem_out", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["12"], "DependentChan" : "77", "DependentChanDepth" : "9", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "rowsReceived", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.output_row_U0.grp_output_row_Pipeline_VITIS_LOOP_20_1_fu_84", "Parent" : "74", "Child" : ["76"],
		"CDFG" : "output_row_Pipeline_VITIS_LOOP_20_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "515", "EstimateLatencyMax" : "515",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln20_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_hysteresis", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_20_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "76", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.output_row_U0.grp_output_row_Pipeline_VITIS_LOOP_20_1_fu_84.flow_control_loop_pipe_sequential_init_U", "Parent" : "75"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.out_c_U", "Parent" : "4"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.cond_loc_channel_U", "Parent" : "4"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.gaussian_valid_U", "Parent" : "4"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.sobel_valid_U", "Parent" : "4"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.nonmax_valid_U", "Parent" : "4"},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.double_valid_U", "Parent" : "4"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.dataflow_in_loop_VITIS_LOOP_7_1_1_U0.hysteresis_valid_U", "Parent" : "4"}]}
