// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module canny_top_gaussian_blur_Pipeline_VITIS_LOOP_82_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        row_in_load,
        row_in_load_1,
        row_in_load_2,
        row_in_address0,
        row_in_ce0,
        row_in_q0,
        lineBuffer_4_address0,
        lineBuffer_4_ce0,
        lineBuffer_4_we0,
        lineBuffer_4_d0,
        lineBuffer_3_address0,
        lineBuffer_3_ce0,
        lineBuffer_3_we0,
        lineBuffer_3_d0,
        lineBuffer_2_address0,
        lineBuffer_2_ce0,
        lineBuffer_2_we0,
        lineBuffer_2_d0,
        lineBuffer_1_address0,
        lineBuffer_1_ce0,
        lineBuffer_1_we0,
        lineBuffer_1_d0,
        lineBuffer_address0,
        lineBuffer_ce0,
        lineBuffer_we0,
        lineBuffer_d0,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] row_in_load;
input  [7:0] row_in_load_1;
input  [7:0] row_in_load_2;
output  [8:0] row_in_address0;
output   row_in_ce0;
input  [7:0] row_in_q0;
output  [8:0] lineBuffer_4_address0;
output   lineBuffer_4_ce0;
output   lineBuffer_4_we0;
output  [11:0] lineBuffer_4_d0;
output  [8:0] lineBuffer_3_address0;
output   lineBuffer_3_ce0;
output   lineBuffer_3_we0;
output  [11:0] lineBuffer_3_d0;
output  [8:0] lineBuffer_2_address0;
output   lineBuffer_2_ce0;
output   lineBuffer_2_we0;
output  [11:0] lineBuffer_2_d0;
output  [8:0] lineBuffer_1_address0;
output   lineBuffer_1_ce0;
output   lineBuffer_1_we0;
output  [11:0] lineBuffer_1_d0;
output  [8:0] lineBuffer_address0;
output   lineBuffer_ce0;
output   lineBuffer_we0;
output  [11:0] lineBuffer_d0;
input  [2:0] empty;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln82_fu_235_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] tmp_reg_485;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] column_reg_489;
reg   [9:0] column_reg_489_pp0_iter1_reg;
reg   [0:0] icmp_ln82_reg_494;
wire   [11:0] add_ln89_2_fu_404_p2;
reg   [11:0] add_ln89_2_reg_503;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln102_1_fu_299_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln82_fu_435_p1;
reg   [7:0] empty_96_fu_76;
wire    ap_loop_init;
reg   [9:0] column_13_fu_80;
wire   [9:0] add_ln82_fu_241_p2;
reg   [9:0] ap_sig_allocacmp_column;
reg   [7:0] empty_97_fu_84;
reg   [7:0] empty_98_fu_88;
reg   [7:0] empty_99_fu_92;
reg   [7:0] empty_100_fu_96;
reg    row_in_ce0_local;
reg    lineBuffer_3_we0_local;
reg    lineBuffer_3_ce0_local;
reg    lineBuffer_2_we0_local;
reg    lineBuffer_2_ce0_local;
reg    lineBuffer_1_we0_local;
reg    lineBuffer_1_ce0_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_4_we0_local;
reg    lineBuffer_4_ce0_local;
wire   [8:0] trunc_ln102_fu_259_p1;
wire   [9:0] zext_ln102_fu_263_p1;
wire   [9:0] add_ln102_fu_267_p2;
wire   [8:0] trunc_ln26_fu_273_p1;
wire   [0:0] tmp_46_fu_277_p3;
wire   [8:0] sub_ln28_fu_285_p2;
wire   [8:0] select_ln27_fu_291_p3;
wire   [8:0] tmp_45_fu_340_p3;
wire   [10:0] p_shl_fu_332_p3;
wire   [10:0] zext_ln89_4_fu_348_p1;
wire   [8:0] p_cast13_fu_362_p1;
wire   [8:0] p_cast14_fu_358_p1;
wire   [8:0] tmp4_fu_366_p2;
wire   [10:0] tmp1_fu_372_p3;
wire   [8:0] zext_ln89_fu_328_p1;
wire   [8:0] zext_ln90_fu_324_p1;
wire   [8:0] add_ln89_fu_384_p2;
wire   [10:0] zext_ln89_3_fu_390_p1;
wire   [10:0] sub_ln89_fu_352_p2;
wire   [10:0] add_ln89_1_fu_394_p2;
wire   [11:0] zext_ln89_2_fu_400_p1;
wire   [11:0] zext_ln89_1_fu_380_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 empty_96_fu_76 = 8'd0;
#0 column_13_fu_80 = 10'd0;
#0 empty_97_fu_84 = 8'd0;
#0 empty_98_fu_88 = 8'd0;
#0 empty_99_fu_92 = 8'd0;
#0 empty_100_fu_96 = 8'd0;
#0 ap_done_reg = 1'b0;
end

canny_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln82_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            column_13_fu_80 <= add_ln82_fu_241_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            column_13_fu_80 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_100_fu_96 <= row_in_load;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln82_reg_494 == 1'd0))) begin
            empty_100_fu_96 <= row_in_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_96_fu_76 <= row_in_load;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln82_reg_494 == 1'd0))) begin
            empty_96_fu_76 <= empty_97_fu_84;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_97_fu_84 <= row_in_load_1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln82_reg_494 == 1'd0))) begin
            empty_97_fu_84 <= empty_98_fu_88;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_98_fu_88 <= row_in_load_2;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln82_reg_494 == 1'd0))) begin
            empty_98_fu_88 <= empty_99_fu_92;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_99_fu_92 <= row_in_load_1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln82_reg_494 == 1'd0))) begin
            empty_99_fu_92 <= empty_100_fu_96;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln89_2_reg_503 <= add_ln89_2_fu_404_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        column_reg_489 <= ap_sig_allocacmp_column;
        column_reg_489_pp0_iter1_reg <= column_reg_489;
        icmp_ln82_reg_494 <= icmp_ln82_fu_235_p2;
    end
end

always @ (*) begin
    if (((icmp_ln82_fu_235_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_reg_494 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_column = 10'd0;
    end else begin
        ap_sig_allocacmp_column = column_13_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_1_ce0_local = 1'b1;
    end else begin
        lineBuffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_485 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_1_we0_local = 1'b1;
    end else begin
        lineBuffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_2_ce0_local = 1'b1;
    end else begin
        lineBuffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_485 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_2_we0_local = 1'b1;
    end else begin
        lineBuffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_3_ce0_local = 1'b1;
    end else begin
        lineBuffer_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_485 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_3_we0_local = 1'b1;
    end else begin
        lineBuffer_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_4_ce0_local = 1'b1;
    end else begin
        lineBuffer_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(tmp_reg_485 == 3'd0) & ~(tmp_reg_485 == 3'd1) & ~(tmp_reg_485 == 3'd2) & ~(tmp_reg_485 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_4_we0_local = 1'b1;
    end else begin
        lineBuffer_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_485 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_in_ce0_local = 1'b1;
    end else begin
        row_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln102_fu_267_p2 = (zext_ln102_fu_263_p1 + 10'd3);

assign add_ln82_fu_241_p2 = (ap_sig_allocacmp_column + 10'd1);

assign add_ln89_1_fu_394_p2 = (zext_ln89_3_fu_390_p1 + sub_ln89_fu_352_p2);

assign add_ln89_2_fu_404_p2 = (zext_ln89_2_fu_400_p1 + zext_ln89_1_fu_380_p1);

assign add_ln89_fu_384_p2 = (zext_ln89_fu_328_p1 + zext_ln90_fu_324_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln82_fu_235_p2 = ((ap_sig_allocacmp_column == 10'd512) ? 1'b1 : 1'b0);

assign lineBuffer_1_address0 = zext_ln82_fu_435_p1;

assign lineBuffer_1_ce0 = lineBuffer_1_ce0_local;

assign lineBuffer_1_d0 = add_ln89_2_reg_503;

assign lineBuffer_1_we0 = lineBuffer_1_we0_local;

assign lineBuffer_2_address0 = zext_ln82_fu_435_p1;

assign lineBuffer_2_ce0 = lineBuffer_2_ce0_local;

assign lineBuffer_2_d0 = add_ln89_2_reg_503;

assign lineBuffer_2_we0 = lineBuffer_2_we0_local;

assign lineBuffer_3_address0 = zext_ln82_fu_435_p1;

assign lineBuffer_3_ce0 = lineBuffer_3_ce0_local;

assign lineBuffer_3_d0 = add_ln89_2_reg_503;

assign lineBuffer_3_we0 = lineBuffer_3_we0_local;

assign lineBuffer_4_address0 = zext_ln82_fu_435_p1;

assign lineBuffer_4_ce0 = lineBuffer_4_ce0_local;

assign lineBuffer_4_d0 = add_ln89_2_reg_503;

assign lineBuffer_4_we0 = lineBuffer_4_we0_local;

assign lineBuffer_address0 = zext_ln82_fu_435_p1;

assign lineBuffer_ce0 = lineBuffer_ce0_local;

assign lineBuffer_d0 = add_ln89_2_reg_503;

assign lineBuffer_we0 = lineBuffer_we0_local;

assign p_cast13_fu_362_p1 = empty_97_fu_84;

assign p_cast14_fu_358_p1 = empty_99_fu_92;

assign p_shl_fu_332_p3 = {{empty_98_fu_88}, {3'd0}};

assign row_in_address0 = zext_ln102_1_fu_299_p1;

assign row_in_ce0 = row_in_ce0_local;

assign select_ln27_fu_291_p3 = ((tmp_46_fu_277_p3[0:0] == 1'b1) ? sub_ln28_fu_285_p2 : trunc_ln26_fu_273_p1);

assign sub_ln28_fu_285_p2 = ($signed(9'd510) - $signed(trunc_ln26_fu_273_p1));

assign sub_ln89_fu_352_p2 = (p_shl_fu_332_p3 - zext_ln89_4_fu_348_p1);

assign tmp1_fu_372_p3 = {{tmp4_fu_366_p2}, {2'd0}};

assign tmp4_fu_366_p2 = (p_cast13_fu_362_p1 + p_cast14_fu_358_p1);

assign tmp_45_fu_340_p3 = {{empty_98_fu_88}, {1'd0}};

assign tmp_46_fu_277_p3 = add_ln102_fu_267_p2[32'd9];

assign tmp_reg_485 = empty;

assign trunc_ln102_fu_259_p1 = ap_sig_allocacmp_column[8:0];

assign trunc_ln26_fu_273_p1 = add_ln102_fu_267_p2[8:0];

assign zext_ln102_1_fu_299_p1 = select_ln27_fu_291_p3;

assign zext_ln102_fu_263_p1 = trunc_ln102_fu_259_p1;

assign zext_ln82_fu_435_p1 = column_reg_489_pp0_iter1_reg;

assign zext_ln89_1_fu_380_p1 = tmp1_fu_372_p3;

assign zext_ln89_2_fu_400_p1 = add_ln89_1_fu_394_p2;

assign zext_ln89_3_fu_390_p1 = add_ln89_fu_384_p2;

assign zext_ln89_4_fu_348_p1 = tmp_45_fu_340_p3;

assign zext_ln89_fu_328_p1 = empty_100_fu_96;

assign zext_ln90_fu_324_p1 = empty_96_fu_76;

endmodule //canny_top_gaussian_blur_Pipeline_VITIS_LOOP_82_4
