// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module canny_top_canny_top_Pipeline_VITIS_LOOP_79_1_VITIS_LOOP_80_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_anonymous_namespace_lineBuffer_32_0_address0,
        p_anonymous_namespace_lineBuffer_32_0_ce0,
        p_anonymous_namespace_lineBuffer_32_0_we0,
        p_anonymous_namespace_lineBuffer_32_0_d0,
        p_anonymous_namespace_lineBuffer_32_1_address0,
        p_anonymous_namespace_lineBuffer_32_1_ce0,
        p_anonymous_namespace_lineBuffer_32_1_we0,
        p_anonymous_namespace_lineBuffer_32_1_d0,
        p_anonymous_namespace_lineBuffer_32_2_address0,
        p_anonymous_namespace_lineBuffer_32_2_ce0,
        p_anonymous_namespace_lineBuffer_32_2_we0,
        p_anonymous_namespace_lineBuffer_32_2_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] p_anonymous_namespace_lineBuffer_32_0_address0;
output   p_anonymous_namespace_lineBuffer_32_0_ce0;
output   p_anonymous_namespace_lineBuffer_32_0_we0;
output  [7:0] p_anonymous_namespace_lineBuffer_32_0_d0;
output  [8:0] p_anonymous_namespace_lineBuffer_32_1_address0;
output   p_anonymous_namespace_lineBuffer_32_1_ce0;
output   p_anonymous_namespace_lineBuffer_32_1_we0;
output  [7:0] p_anonymous_namespace_lineBuffer_32_1_d0;
output  [8:0] p_anonymous_namespace_lineBuffer_32_2_address0;
output   p_anonymous_namespace_lineBuffer_32_2_ce0;
output   p_anonymous_namespace_lineBuffer_32_2_we0;
output  [7:0] p_anonymous_namespace_lineBuffer_32_2_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln79_fu_116_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln80_fu_162_p1;
reg   [9:0] column_8_fu_44;
wire   [9:0] add_ln80_fu_177_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_column_8_load;
reg   [1:0] row_fu_48;
wire   [1:0] select_ln79_1_fu_154_p3;
reg   [1:0] ap_sig_allocacmp_row_load;
reg   [10:0] indvar_flatten6_fu_52;
wire   [10:0] add_ln79_fu_122_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    p_anonymous_namespace_lineBuffer_32_1_we0_local;
reg    p_anonymous_namespace_lineBuffer_32_1_ce0_local;
reg    p_anonymous_namespace_lineBuffer_32_0_we0_local;
reg    p_anonymous_namespace_lineBuffer_32_0_ce0_local;
reg    p_anonymous_namespace_lineBuffer_32_2_we0_local;
reg    p_anonymous_namespace_lineBuffer_32_2_ce0_local;
wire   [0:0] icmp_ln80_fu_134_p2;
wire   [1:0] add_ln79_1_fu_148_p2;
wire   [9:0] select_ln79_fu_140_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 column_8_fu_44 = 10'd0;
#0 row_fu_48 = 2'd0;
#0 indvar_flatten6_fu_52 = 11'd0;
#0 ap_done_reg = 1'b0;
end

canny_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln79_fu_116_p2 == 1'd0)) begin
            column_8_fu_44 <= add_ln80_fu_177_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            column_8_fu_44 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln79_fu_116_p2 == 1'd0)) begin
            indvar_flatten6_fu_52 <= add_ln79_fu_122_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_52 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln79_fu_116_p2 == 1'd0)) begin
            row_fu_48 <= select_ln79_1_fu_154_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_48 <= 2'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_116_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_column_8_load = 10'd0;
    end else begin
        ap_sig_allocacmp_column_8_load = column_8_fu_44;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_row_load = 2'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_anonymous_namespace_lineBuffer_32_0_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_32_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln79_1_fu_154_p3 == 2'd0) & (icmp_ln79_fu_116_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_anonymous_namespace_lineBuffer_32_0_we0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_32_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_anonymous_namespace_lineBuffer_32_1_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_32_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln79_1_fu_154_p3 == 2'd1) & (icmp_ln79_fu_116_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_anonymous_namespace_lineBuffer_32_1_we0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_32_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_anonymous_namespace_lineBuffer_32_2_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_32_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln79_1_fu_154_p3 == 2'd0) & ~(select_ln79_1_fu_154_p3 == 2'd1) & (icmp_ln79_fu_116_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_anonymous_namespace_lineBuffer_32_2_we0_local = 1'b1;
    end else begin
        p_anonymous_namespace_lineBuffer_32_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln79_1_fu_148_p2 = (ap_sig_allocacmp_row_load + 2'd1);

assign add_ln79_fu_122_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 11'd1);

assign add_ln80_fu_177_p2 = (select_ln79_fu_140_p3 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln79_fu_116_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 11'd1536) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_134_p2 = ((ap_sig_allocacmp_column_8_load == 10'd512) ? 1'b1 : 1'b0);

assign p_anonymous_namespace_lineBuffer_32_0_address0 = zext_ln80_fu_162_p1;

assign p_anonymous_namespace_lineBuffer_32_0_ce0 = p_anonymous_namespace_lineBuffer_32_0_ce0_local;

assign p_anonymous_namespace_lineBuffer_32_0_d0 = 8'd0;

assign p_anonymous_namespace_lineBuffer_32_0_we0 = p_anonymous_namespace_lineBuffer_32_0_we0_local;

assign p_anonymous_namespace_lineBuffer_32_1_address0 = zext_ln80_fu_162_p1;

assign p_anonymous_namespace_lineBuffer_32_1_ce0 = p_anonymous_namespace_lineBuffer_32_1_ce0_local;

assign p_anonymous_namespace_lineBuffer_32_1_d0 = 8'd0;

assign p_anonymous_namespace_lineBuffer_32_1_we0 = p_anonymous_namespace_lineBuffer_32_1_we0_local;

assign p_anonymous_namespace_lineBuffer_32_2_address0 = zext_ln80_fu_162_p1;

assign p_anonymous_namespace_lineBuffer_32_2_ce0 = p_anonymous_namespace_lineBuffer_32_2_ce0_local;

assign p_anonymous_namespace_lineBuffer_32_2_d0 = 8'd0;

assign p_anonymous_namespace_lineBuffer_32_2_we0 = p_anonymous_namespace_lineBuffer_32_2_we0_local;

assign select_ln79_1_fu_154_p3 = ((icmp_ln80_fu_134_p2[0:0] == 1'b1) ? add_ln79_1_fu_148_p2 : ap_sig_allocacmp_row_load);

assign select_ln79_fu_140_p3 = ((icmp_ln80_fu_134_p2[0:0] == 1'b1) ? 10'd0 : ap_sig_allocacmp_column_8_load);

assign zext_ln80_fu_162_p1 = select_ln79_fu_140_p3;

endmodule //canny_top_canny_top_Pipeline_VITIS_LOOP_79_1_VITIS_LOOP_80_2
